/* Real temporary write APIs; only PM/translation/candidate facts are synthetic. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {execFileSync}=require('node:child_process');
const fs=require('node:fs/promises');
const path=require('node:path');
(async()=>{
 const base=process.env.BASE_URL,out=process.env.UI_OUTPUT||'/tmp/ai-company-journey-writes';assert.equal(new URL(base).hostname,'127.0.0.1');await fs.mkdir(out,{recursive:true});
 const browser=await chromium.launch({headless:true,chromiumSandbox:true,...(process.env.CHROME_CHANNEL?{channel:process.env.CHROME_CHANNEL}:{}),...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
 const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block',reducedMotion:'reduce'}),page=await context.newPage();page.setDefaultTimeout(12000);
 const errors=[],violations=[],checks=[],writes=[];let currentCase='login';
 await context.route('**/*',route=>{const req=route.request(),url=new URL(req.url());if(url.origin!==base){violations.push(url.pathname);return route.abort();}return route.continue();});
 page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.method()!=='GET')writes.push({path:new URL(request.url()).pathname,method:request.method(),body:/\/api\/(login|password)/.test(request.url())?undefined:request.postDataJSON()});});
 const inject=(action,pid)=>JSON.parse(execFileSync(process.env.PYTHON_EXECUTABLE,['tests/ui/run_journey_writes.py','--fixture-action',action,'--state',process.env.JOURNEY_FIXTURE_STATE,'--project',pid],{encoding:'utf8'}));
 const go=async hash=>{await page.evaluate(value=>{location.hash=value;},hash);await page.waitForTimeout(150);};
 const overview=pid=>page.evaluate(async id=>(await(await fetch('/api/projects/'+id+'/overview')).json()),pid);
 const holdPost=async endpoint=>{
  let release,received;const held=new Promise(resolve=>{received=resolve;}),gate=new Promise(resolve=>{release=resolve;});
  const response=page.waitForResponse(item=>item.request().method()==='POST'&&new URL(item.url()).pathname===endpoint);
  await page.route('**'+endpoint,async handler=>{if(handler.request().method()!=='POST')return handler.continue();const actual=await handler.fetch();received();await gate;await handler.fulfill({response:actual});});
  return {held,release:()=>release(),response,clear:()=>page.unroute('**'+endpoint)};
 };
 const request=(url,body,options={})=>page.evaluate(async({url,body,options})=>{const session=await(await fetch('/api/session')).json();const response=await fetch(url,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.csrf===false?{}:{'X-CSRF-Token':session.csrf_token})},body:JSON.stringify(body)});return {status:response.status,body:await response.json()};},{url,body,options});
 const shot=async name=>{await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile overflow');await page.screenshot({path:path.join(out,'journey-write-'+name+'.png'),fullPage:true});};
 const matrix=async(name,{open,check}={})=>{
  const dismiss=async()=>{if(await page.locator('#dialog[open]').count())await page.locator('#dialog').getByRole('button',{name:'취소',exact:true}).click();};
  for(const width of [320,390,1440])for(const theme of ['light','black']){
   if(open)await dismiss();await page.setViewportSize({width,height:width>700?1000:844});await page.locator(`[data-theme-choice="${theme}"]`).click();if(open)await open();if(check)await check();
   await page.keyboard.press('Tab');if(open)assert.equal(await page.evaluate(()=>document.querySelector('#dialog').contains(document.activeElement)),true,'native keyboard focus stays in the review dialog');
   if(open){const close=await page.locator('#dialog .dialog-head button').boundingBox();assert.ok(close&&close.width>=44&&close.height>=44,'review close target is at least 44 CSS px');}
   await shot(`${name}-${theme}-${width}`);
  }
  if(open)await dismiss();await page.setViewportSize({width:390,height:844});await page.locator('[data-theme-choice="light"]').click();if(open)await open();
 };
 const newProject=async(name,goal)=>{await go('#projects');await page.locator('#project-create').click();await page.locator('#project-name').fill(name);await page.getByLabel('목표',{exact:true}).fill(goal);await page.locator('#create-form button[type=submit]').click();await page.locator('#message-form').waitFor();return new URLSearchParams(new URL(page.url()).hash.split('?')[1]).get('project');};
 try{
  await page.goto(base+'/');await page.getByLabel('비밀번호',{exact:true}).fill(process.env.TEST_PASSWORD);await page.getByRole('button',{name:'로그인',exact:true}).click();await page.getByLabel('현재 비밀번호',{exact:true}).fill(process.env.TEST_PASSWORD);await page.getByLabel('새 비밀번호',{exact:true}).fill('journey-writes-fixture-only-password');await page.getByLabel('새 비밀번호 확인',{exact:true}).fill('journey-writes-fixture-only-password');await page.getByRole('button',{name:'비밀번호 변경 후 계속'}).click();await page.locator('#project-create').waitFor();
  currentCase='natural goal starts PM intent only';const pid=await newProject('내 작은 검증 프로젝트','역할 상태를 읽기 쉽게 집계하고 독립 검사하고 싶어요.');let state=await overview(pid);assert.equal(state.project.goal,'역할 상태를 읽기 쉽게 집계하고 독립 검사하고 싶어요.');assert.equal(state.pm_requests.length,1);assert.equal(state.pm_requests[0].state,'pending');assert.equal(state.plans.length,0);assert.equal(state.runs.length,0);assert.equal(state.tasks.length,0);await shot('natural-goal-pending');
  const creation=writes.find(item=>item.path==='/api/projects').body,retried=await Promise.all([request('/api/projects',creation),request('/api/projects',creation)]);assert.ok(retried.every(result=>result.body.project.id===pid));checks.push('natural name/goal creates one project and one pending PM request; concurrent same-intent creation creates no duplicates or execution');
  currentCase='synthetic proposal and actual specification registration';const initial=inject('proposal',pid).plan;await page.reload();const scopeButton=page.getByRole('button',{name:'실행 범위 확인',exact:true});await scopeButton.focus();await page.keyboard.press('Enter');const execution=page.locator('#execution');assert.ok(await execution.evaluate(el=>el.open));assert.equal(new URL(page.url()).hash.split('?')[0],'#manager','specification is available in the current plan screen');assert.equal(await page.evaluate(()=>document.activeElement===document.querySelector('#execution > summary')),true,'keyboard action focuses the opened specification');
  await matrix('specification',{check:async()=>{assert.ok(await execution.evaluate(el=>el.open));assert.equal(await execution.getByRole('button',{name:'명세 저장',exact:true}).count(),1);}});assert.equal((await overview(pid)).runs.length,0);await execution.getByRole('button',{name:'명세 저장',exact:true}).click();await execution.getByRole('button',{name:'PM에게 새 계획 요청',exact:true}).waitFor();
  state=await overview(pid);assert.equal(state.execution_specs.length,1);assert.equal(state.runs.length,0);assert.equal(state.pm_requests.length,1);const specification=state.execution_specs[0],savedRequest=writes.find(item=>item.path.endsWith('/execution-specs')).body;
  const repeatedSave=await Promise.all([request(`/api/projects/${pid}/execution-specs`,savedRequest),request(`/api/projects/${pid}/execution-specs`,savedRequest)]);assert.ok(repeatedSave.every(result=>result.body.execution_spec.digest===specification.digest));
  const staleProposal=await request(`/api/projects/${pid}/plans/${initial.id}/confirm`,{plan_digest:initial.digest,base_harness_version:initial.base_harness_version,idempotency_key:'cannot-confirm-proposal'});assert.equal(staleProposal.status,409);assert.equal((await overview(pid)).runs.length,0);
  // The manager already contains #message-form. A real held POST response is
  // the boundary; navigation during that wait must preserve the chosen scope.
  const initialSnapshot=(await overview(pid)).workspace_graph.snapshots.find(item=>item.plan_id===initial.id&&!item.run_id);assert.ok(initialSnapshot);
  await go(`#manager?project=${pid}&snapshot=${initialSnapshot.id}`);await page.locator('#journey-run').waitFor();await go('#manager?project='+pid);await execution.getByRole('button',{name:'PM에게 새 계획 요청',exact:true}).waitFor();
  const requestedPlan=await holdPost(`/api/projects/${pid}/messages`);await execution.getByRole('button',{name:'PM에게 새 계획 요청',exact:true}).click();await requestedPlan.held;await page.goBack();await page.waitForFunction(id=>new URLSearchParams(location.hash.split('?')[1]).get('snapshot')===id,initialSnapshot.id);requestedPlan.release();const requestedResponse=await requestedPlan.response;assert.equal(requestedResponse.status(),200);const requestedMessage=(await requestedResponse.json()).message;await page.locator('#toast').filter({hasText:'PM에게 새 계획을 요청했습니다'}).waitFor();assert.equal(new URLSearchParams(new URL(page.url()).hash.split('?')[1]).get('snapshot'),initialSnapshot.id);assert.equal(await page.locator('#journey-run').inputValue(),initialSnapshot.id);await requestedPlan.clear();
  state=await overview(pid);assert.equal(state.pm_requests.length,2);assert.equal(state.pm_requests.at(-1).message_id,requestedMessage.id);assert.equal(state.pm_requests.at(-1).state,'pending');assert.equal(state.runs.length,0);await shot('held-pm-preserves-selected-plan');checks.push('real catalog registration stays separate from a fresh PM request and confirmation; held successful PM request preserves a same-project manager snapshot chosen with browser Back; duplicate saves keep one immutable version; obsolete proposal rejected');
  currentCase='saved Korean reading and direct confirmation';const fresh=inject('proposal',pid),plan=fresh.plan;await go('#manager?project='+pid);await page.reload();await page.getByRole('button',{name:'계획 검토·확정',exact:true}).click();const dialog=page.getByRole('dialog'),form=dialog.locator('#plan-form'),reading=dialog.getByRole('region',{name:'계획 내용'});await reading.getByText('작은 함수를 개발하고 독립적으로 검증합니다',{exact:true}).waitFor();
  assert.equal(await form.getAttribute('data-digest'),plan.digest);assert.equal(await form.getAttribute('data-execution-spec'),specification.digest);assert.equal((await overview(pid)).runs.length,0,'opening the review never confirms');await dialog.getByRole('checkbox').check();await reading.getByRole('button',{name:'원문 보기',exact:true}).click();assert.equal(await dialog.getByRole('checkbox').isChecked(),false);await reading.getByText(plan.content.summary,{exact:true}).waitFor();assert.equal(await form.getAttribute('data-translation-id'),'');await reading.getByRole('button',{name:'한국어 보기',exact:true}).click();assert.equal(await form.getAttribute('data-translation-id'),fresh.translation.id);
  await matrix('plan-review',{open:async()=>{await page.getByRole('button',{name:'계획 검토·확정',exact:true}).click();await form.waitFor();},check:async()=>{assert.equal(await form.getAttribute('data-digest'),plan.digest);assert.equal(await form.getAttribute('data-translation-id'),fresh.translation.id);assert.ok(await reading.locator('.report-summary').evaluate(el=>parseFloat(getComputedStyle(el).fontSize)>=16),'Korean main plan text is readable');}});
  const cdp=await context.newCDPSession(page);await cdp.send('Emulation.setDeviceMetricsOverride',{width:720,height:500,deviceScaleFactor:2,mobile:false});await shot('plan-review-200-equivalent');await cdp.send('Emulation.clearDeviceMetricsOverride');await cdp.detach();await page.setViewportSize({width:390,height:844});assert.equal((await overview(pid)).runs.length,0,'theme/width/keyboard review creates no run');await dialog.getByRole('checkbox').focus();await page.keyboard.press('Space');assert.equal(await dialog.getByRole('checkbox').isChecked(),true);checks.push('specification and plan review: Light/Black × 320/390/1440, keyboard opening/focus/acknowledgment, Korean 16px body, 200% equivalent CSS viewport reflow (not physical-device zoom)');
  const confirmedResponse=page.waitForResponse(response=>new URL(response.url()).pathname===`/api/projects/${pid}/plans/${plan.id}/confirm`);await dialog.getByRole('button',{name:'이 계획 확정',exact:true}).click();const confirmed=await(await confirmedResponse).json();await form.waitFor({state:'hidden'});const run=confirmed.run,confirmBody=writes.find(item=>item.path.endsWith(`/plans/${plan.id}/confirm`)).body;
  assert.equal(run.plan_digest,plan.digest);assert.equal(run.execution_spec.digest,specification.digest);assert.deepEqual(confirmBody.displayed_translation,fresh.translation);assert.equal(confirmBody.plan_digest,plan.digest);assert.deepEqual(confirmed.plan.content,plan.content);assert.deepEqual(confirmed.plan.displayed_translation,fresh.translation);await page.waitForFunction(id=>new URLSearchParams(location.hash.split('?')[1]).get('run')===id,run.id);assert.equal(new URL(page.url()).hash.split('?')[0],'#progress','a direct confirmation opens that exact run');
  const concurrent=await Promise.all([request(`/api/projects/${pid}/plans/${plan.id}/confirm`,confirmBody),request(`/api/projects/${pid}/plans/${plan.id}/confirm`,confirmBody)]);assert.ok(concurrent.every(result=>result.status===200&&result.body.run.id===run.id));assert.equal((await overview(pid)).runs.length,1);checks.push('real translated/original review toggle resets acknowledgment; direct click confirms exact original digest/spec/translation; concurrent identical confirmations retain one run');
  currentCase='actual stale plan failure';await request(`/api/projects/${pid}/messages`,{content:'완료 조건을 더 확인하고 싶어요.'});const stale=inject('proposal',pid).plan;await go('#manager?project='+pid);await page.reload();await page.getByRole('button',{name:'계획 검토·확정',exact:true}).click();await request(`/api/projects/${pid}/messages`,{content:'앞선 제안 이후 목표 설명을 보완합니다.'});await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'이 계획 확정',exact:true}).click();await dialog.locator('#plan-error').filter({hasText:/변경|계획/}).waitFor();assert.equal(await dialog.getByRole('button',{name:'이 계획 확정',exact:true}).isDisabled(),true);assert.equal((await overview(pid)).runs.length,1);await dialog.getByRole('button',{name:'취소',exact:true}).click();checks.push('conversation revision while a real review is open rejects stale confirmation without another run');
  currentCase='candidate source and expiry checks';const candidate=inject('approval',pid),approval=candidate.approval;await go('#approvals?project='+pid+'&run='+run.id+'&approval='+approval.id);await page.reload();await page.locator('.approval-reading').waitFor();await matrix('candidate-review',{open:async()=>{await page.locator(`button[data-decision="approve"][data-id="${approval.id}"]`).click();await dialog.locator('#decision-form').waitFor();},check:async()=>{assert.equal(await dialog.locator('#decision-form').getAttribute('data-digest'),approval.subject_digest);assert.equal(await dialog.locator('#decision-form').getAttribute('data-id'),approval.id);}});assert.equal((await overview(pid)).approvals.find(item=>item.id===approval.id).status,'pending','visual review never decides');checks.push('candidate review: same subject/candidate through Light/Black × 320/390/1440 and modal keyboard focus; merely opening never decides');await dialog.getByRole('button',{name:'승인 기록',exact:true}).click();await dialog.locator('#decision-form').waitFor({state:'hidden'});
  const decisionBody=writes.find(item=>item.path.endsWith(`/approvals/${approval.id}/decisions`)).body,replay=await request(`/api/projects/${pid}/approvals/${approval.id}/decisions`,decisionBody);assert.equal(replay.status,200);assert.equal(replay.body.approval.status,'approved');assert.equal((await overview(pid)).runs.length,1);
  const expired=inject('expired-approval',pid).approval;await go('#approvals?project='+pid+'&run='+run.id+'&approval='+expired.id);await page.reload();await page.locator('.approval-reading').waitFor();const expiredButton=page.locator(`button[data-decision="approve"][data-id="${expired.id}"]`);assert.ok(await expiredButton.count()===0||await expiredButton.isDisabled(),'expired approval has no usable accept action');
  const expiredDecision=await request(`/api/projects/${pid}/approvals/${expired.id}/decisions`,{decision:'approve',comment:'fixture only',subject_digest:expired.subject_digest,idempotency_key:'expired-decision-once'});assert.equal(expiredDecision.status,409);assert.equal(expiredDecision.body.error.code,'expired');
  const wrongSubject=await request(`/api/projects/${pid}/approvals/${expired.id}/decisions`,{decision:'approve',comment:'fixture only',subject_digest:'f'.repeat(64),idempotency_key:'changed-subject-once'});assert.equal(wrongSubject.status,409);assert.equal(wrongSubject.body.error.code,'subject_mismatch');checks.push('actual candidate decision preserves original digest and idempotent replay; expired candidate is disabled and refused by server');
  currentCase='message rejection and uncertain delivery keep original draft';await go('#manager?project='+pid);await page.locator('#message-form').waitFor();const draft='응답을 잃어도 이 원문을 보존해 주세요.',messagePath=`/api/projects/${pid}/messages`,beforeMessages=(await overview(pid)).pm_requests.length;await page.locator('#message-content').fill(draft);
  await page.route('**'+messagePath,handler=>handler.fulfill({status:503,contentType:'application/json',json:{error:{code:'fixture_unavailable',message:'일시 오류 시험 · 저장하지 않았습니다.'}}}));await page.locator('#message-form button[type=submit]').click();await page.locator('#message-error').filter({hasText:'전송 결과를 확인하지 못했습니다'}).waitFor();assert.equal(await page.locator('#message-content').inputValue(),draft);assert.equal((await overview(pid)).pm_requests.length,beforeMessages);await page.unroute('**'+messagePath);
  let deliveries=0;await page.route('**'+messagePath,async handler=>{deliveries++;await handler.fetch();await handler.abort('failed');});const lostMessage=page.waitForEvent('requestfailed',request=>request.method()==='POST'&&new URL(request.url()).pathname===messagePath);await page.locator('#message-form button[type=submit]').click();await lostMessage;await page.locator('#message-error').filter({hasText:'전송 결과를 확인하지 못했습니다'}).waitFor();assert.equal(await page.locator('#message-content').inputValue(),draft);await page.waitForTimeout(5500);assert.equal(deliveries,1,'uncertain non-idempotent messages are never automatically replayed');assert.ok((await page.locator('#message-error').textContent()).includes('자동 재전송하지 않습니다'),'polling preserves the uncertain-result guidance');assert.equal((await overview(pid)).pm_requests.length,beforeMessages+1);await page.unroute('**'+messagePath);await page.reload();await page.locator('#message-form').waitFor();assert.equal(await page.locator('#message-content').inputValue(),draft,'original draft survives a fresh page');assert.ok((await overview(pid)).messages.some(message=>message.content===draft));await shot('uncertain-message-draft');checks.push('injected 503 leaves draft and DB unchanged; a real message with lost response remains one delivery, retains original draft through polling/reload and is not automatically resent');
  currentCase='new project response after browser back';await go('#progress?project='+pid+'&run='+run.id);await page.locator('[data-rg-root]').waitFor();await go('#manager?project='+pid);await page.locator('#message-form').waitFor();await page.getByRole('button',{name:'새 프로젝트',exact:true}).click();await page.locator('#project-name').fill('뒤로 가기 중 만든 프로젝트');await page.getByLabel('목표',{exact:true}).fill('이전 실행과 섞이지 않는 새 목표입니다.');
  let release,received;const held=new Promise(resolve=>{received=resolve;}),gate=new Promise(resolve=>{release=resolve;});let newId;
  await page.route('**/api/projects',async handler=>{if(handler.request().method()!=='POST')return handler.continue();const response=await handler.fetch();newId=(await response.json()).project.id;received();await gate;await handler.fulfill({response});});await page.locator('#create-form button[type=submit]').click();await held;await page.goBack();assert.equal(new URLSearchParams(new URL(page.url()).hash.split('?')[1]).get('run'),run.id);release();await page.locator('#message-form').waitFor();await page.waitForFunction(id=>new URLSearchParams(location.hash.split('?')[1]).get('project')===id,newId);const afterCreation=new URLSearchParams(new URL(page.url()).hash.split('?')[1]);assert.equal(afterCreation.get('run'),null);assert.equal(afterCreation.get('snapshot'),null);assert.equal((await overview(newId)).runs.length,0);await page.unroute('**/api/projects');checks.push('held real project creation response after same-project browser back starts the new current PM, with no inherited run or snapshot');
  currentCase='cross-project and authority failures';const foreignPlan=await request(`/api/projects/${newId}/plans/${plan.id}/confirm`,confirmBody);assert.equal(foreignPlan.status,404);const foreignApproval=await request(`/api/projects/${newId}/approvals/${approval.id}/decisions`,decisionBody);assert.equal(foreignApproval.status,404);const noCSRF=await request(`/api/projects/${newId}/messages`,{content:'must not store'},{csrf:false});assert.equal(noCSRF.status,403);
  const wrongOrigin=await context.request.post(base+`/api/projects/${newId}/messages`,{headers:{Origin:'https://foreign.invalid'},data:{content:'must not store'}});assert.equal(wrongOrigin.status(),403);
  const unauthed=await browser.newContext();const denied=await unauthed.request.get(base+'/api/projects');assert.equal(denied.status(),401);await unauthed.close();await go('#progress?project='+newId+'&run='+run.id);await page.getByText(/해당 실행을 확인할 수 없/).first().waitFor();assert.equal(await page.locator('.rg-node').count(),0);assert.equal((await overview(newId)).pm_requests.length,1);assert.equal((await overview(newId)).runs.length,0);checks.push('foreign project plan/approval, missing CSRF, foreign Origin and absent login fail; foreign run is not displayed; rejected requests add no PM work');
  currentCase='late confirmation preserves a user-selected earlier run';await request(`/api/projects/${pid}/messages`,{content:'이전 실행과 별도로 다음 작은 계획을 제안해 주세요.'});const later=inject('proposal',pid),laterPlan=later.plan;const earlierSnapshot=(await overview(pid)).workspace_graph.snapshots.find(item=>item.run_id===run.id);assert.ok(earlierSnapshot);
  await go(`#manager?project=${pid}&run=${run.id}&snapshot=${earlierSnapshot.id}`);await page.locator('#journey-run').waitFor();await go('#manager?project='+pid);await page.reload();await page.getByRole('button',{name:'계획 검토·확정',exact:true}).click();await dialog.getByRole('checkbox').check();const heldConfirmation=await holdPost(`/api/projects/${pid}/plans/${laterPlan.id}/confirm`);await dialog.getByRole('button',{name:'이 계획 확정',exact:true}).click();await heldConfirmation.held;await page.goBack();await page.waitForFunction(id=>new URLSearchParams(location.hash.split('?')[1]).get('snapshot')===id,earlierSnapshot.id);heldConfirmation.release();const lateResponse=await heldConfirmation.response;assert.equal(lateResponse.status(),200);const lateResult=await lateResponse.json();await dialog.locator('#plan-form').waitFor({state:'hidden'});await page.locator('#toast').filter({hasText:'계획을 확정했습니다'}).waitFor();
  const retained=new URLSearchParams(new URL(page.url()).hash.split('?')[1]);assert.equal(new URL(page.url()).hash.split('?')[0],'#manager');assert.equal(retained.get('run'),run.id);assert.equal(retained.get('snapshot'),earlierSnapshot.id);assert.equal(await page.locator('#journey-run').inputValue(),earlierSnapshot.id);assert.notEqual(lateResult.run.id,run.id);assert.equal(lateResult.run.plan_id,laterPlan.id);assert.equal(lateResult.run.plan_digest,laterPlan.digest);state=await overview(pid);assert.equal(state.runs.length,2);assert.ok(state.runs.some(item=>item.id===lateResult.run.id));await heldConfirmation.clear();await shot('held-confirmation-preserves-selected-run');checks.push('a second actual confirmation is saved exactly once while its held response preserves the previous run/snapshot chosen by browser Back on the same project and manager view');
  assert.deepEqual(errors,[]);assert.deepEqual(violations,[]);await fs.writeFile(path.join(out,'journey-writes-validation.json'),JSON.stringify({status:'PASS',browser:browser.version(),sandbox:true,source:'actual temporary API and SQLite; PM/translation/candidate facts injected locally; no model, operational master, operational approval or worker execution',project_id:pid,run_id:run.id,plan_id:plan.id,plan_digest:plan.digest,execution_spec_digest:specification.digest,checks,write_paths:writes.map(({path,method})=>({path,method}))},null,2));console.log(JSON.stringify({status:'PASS',checks}));
 }catch(error){await fs.writeFile(path.join(out,'journey-writes-failure.json'),JSON.stringify({case:currentCase,error:error.message,checks,errors,violations},null,2));await page.screenshot({path:path.join(out,'journey-writes-failure.png'),fullPage:true}).catch(()=>{});throw error;}
 finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
