import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../../src/ai_company/web/manager-ui.js',import.meta.url),'utf8');
const {managerSnapshot,createManagerUI,executionReferenceMatches}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const plan={id:'p',digest:'current',request_revision:2,status:'proposed',content:{summary:'Long original English specification',roles:[{key:'implementation',name:'Implement component',depends_on:[]},{key:'tests',name:'Test component',depends_on:[]},{key:'reviewer',name:'Review',depends_on:['implementation','tests']}],completion_criteria:['Do not deploy']}};
const overview={project:{id:'project',request_revision:2},plans:[plan],pm_requests:[{request_revision:2,state:'completed'}],runs:[{plan_id:'p',plan_digest:'old',state:'completed'}]};
assert.equal(managerSnapshot(overview).run,undefined,'a success for a different plan digest cannot advance this plan');
assert.equal(managerSnapshot(overview).independent,2,'dependency-bound review is not counted as an independent role');
assert.equal(managerSnapshot({...overview,project:{id:'project',request_revision:3},pm_requests:[{request_revision:3,state:'waiting_quota'}]}).plan,undefined,'a new request cannot offer the old plan for confirmation');
assert.equal(managerSnapshot({...overview,plans:[{...plan,status:'stale'}]}).plan,undefined);
const stalePolicy={...overview,plans:[{...plan,status:'stale',stale_reason:'검수 기준이 변경되어 새 계획이 필요합니다.'}],runs:[]};
const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const ui=createManagerUI({esc,badge:esc,label:esc,stamp:String,documents:{text:(id,field,fallback)=>fallback,meta:()=>''},planContent:()=>'<p>Full original constraints</p>'});
const options={connected:true,composer:'',history:'',technical:'',archive:''};
assert.match(ui.render(stalePolicy,options),/검수 기준이 변경되어 새 계획이 필요합니다/);
assert.match(ui.render(stalePolicy,options),/새 계획 요청/);
assert.doesNotMatch(ui.render(stalePolicy,options),/data-action="review-plan"/);
const before=JSON.stringify(overview),html=ui.render(overview,options);
assert.equal(JSON.stringify(overview),before,'overview rendering cannot mutate persisted data');
assert.ok(!html.includes('Long original English specification'),'untranslated prose is not the headline');
assert.match(html,/확정 전에는 이 계획의 작업을 시작하지 않습니다/);
assert.match(html,/details class="manager-plan-detail"/,'full original plan remains available');
assert.doesNotMatch(ui.render(overview,{...options,connected:false}),/data-action="review-plan"[^>]+(?<!disabled)>/);
const current={plan_id:'p',plan_digest:'current',state:'awaiting_approval',candidate_sha:'candidate',approval_id:'result-approval'};
assert.match(ui.render({...overview,runs:[{...current,roles:{implementation:{status:'RUNNING'}}}],roles:[{id:'live-role',plan_id:'p',key:'implementation',status:'WAITING_QUOTA'}]},options),/WAITING_QUOTA/,'current session quota state is visible before the coordinator updates its run summary');
assert.doesNotMatch(ui.render({...overview,runs:[current],approvals:[{status:'pending',artifact_sha:'unrelated'}]},options),/승인 요청 확인/,'unrelated approvals cannot become the next action for this run');
assert.match(ui.render({...overview,runs:[current],approvals:[{id:'result-approval',status:'pending',artifact_sha:'candidate'}]},options),/승인 요청 확인/);
assert.doesNotMatch(ui.render({...overview,runs:[current],approvals:[{id:'different-operation',status:'pending',artifact_sha:'candidate'}]},options),/승인 요청 확인/,'the same artifact cannot substitute another operation approval');
assert.doesNotMatch(ui.render({...overview,runs:[{...current,state:'running'}],approvals:[{id:'result-approval',status:'pending',artifact_sha:'candidate'}]},options),/승인 요청 확인|같은 후보의 검수가 끝났습니다/,'an active run cannot be promoted to completed review by a pending approval');
assert.match(ui.render({...overview,runs:[{...current,state:'pending'}]},options),/실행 준비/,'a queued execution is not presented as already running');
const quotaRequest={...overview,plans:[],runs:[],pm_requests:[{request_revision:2,state:'running',updated_at:1000,
  execution:{status:'WAITING_CAPACITY',reason:'공유 계정 사용량이 회복될 때까지 기다립니다.',resume_at:2100}}]};
const quotaHTML=ui.render(quotaRequest,options);
assert.doesNotMatch(quotaHTML,/PM 답변 작성 중|PM이 답변을 작성하고 있습니다/,'persisted PM request running does not override its actual execution wait');
assert.match(quotaHTML,/공유 계정 사용량이 회복될 때까지 기다립니다/,'nested execution wait reason is visible');
assert.match(quotaHTML,/2100/,'the recorded nested execution resume time is visible');
const reconciliationRequest={...quotaRequest,pm_requests:[{...quotaRequest.pm_requests[0],execution:{status:'NEEDS_RECONCILIATION',reason:'종료·결과 대조를 먼저 수행해야 합니다.',resume_at:null}}]};
const reconciliationBefore=JSON.stringify(reconciliationRequest),reconciliationHTML=ui.render(reconciliationRequest,options);
assert.match(reconciliationHTML,/PM이 계획을 준비하지 못했습니다|확인이 필요합니다/,'PM execution reconciliation requires action');
assert.doesNotMatch(reconciliationHTML,/답변이 도착하면 팀과 계획|PM이 답변을 작성/,'PM reconciliation is not normal response waiting');
assert.match(reconciliationHTML,/종료·결과 대조를 먼저 수행해야 합니다/);
assert.equal(JSON.stringify(reconciliationRequest),reconciliationBefore);
const questionRequest={...quotaRequest,pm_requests:[{request_revision:2,state:'answer_needed',requirements_feedback:{questions:[{
  id:'Q1',status:'open',prompt:'첫 업무를 정할까요? <script>unsafe</script>',recommendation:'웹사이트 제작부터 시작하는 안을 권합니다.'}]}}]};
const questionHTML=ui.render(questionRequest,options);
assert.match(questionHTML,/답변 필요/);assert.match(questionHTML,/첫 업무를 정할까요/);
assert.match(questionHTML,/웹사이트 제작부터 시작/);assert.doesNotMatch(questionHTML,/<script>unsafe<\/script>/);
assert.doesNotMatch(questionHTML,/계획 검토·확정/,'an unanswered question cannot expose confirmation');
assert.match(ui.render({...overview,plans:[{...plan,status:'reviewing'}],runs:[]},options),/계획 검토 중/);
assert.doesNotMatch(ui.render({...overview,plans:[{...plan,status:'reviewing'}],runs:[]},options),/data-action="review-plan"/);
assert.match(ui.render({...overview,plans:[{...plan,status:'reviewing',review_problem:'계정 인증 실패'}],runs:[]},options),/계획 검토 확인 필요/);
assert.match(ui.render({...overview,plans:[{...plan,status:'reviewing',review_problem:'계정 인증 실패'}],runs:[]},options),/계정 인증 실패/);
assert.match(ui.render({...overview,plans:[{...plan,status:'needs_revision'}],runs:[]},options),/계획 수정 필요/);
console.log('PASS: current revision/digest, dependency counts, read-only projection, original access, disconnected confirmation and candidate-bound next action');
const planSource=await readFile(new URL('../../src/ai_company/web/plan-ui.js',import.meta.url),'utf8');
const {createPlanUI}=await import('data:text/javascript;base64,'+Buffer.from(planSource).toString('base64'));
const planUI=createPlanUI({esc,documents:{text:(id,field,fallback)=>fallback,meta:()=>''}});
const requirements={version:2,problem:'첫 화면 준비',users_and_flow:'초보자가 목표를 입력합니다',scope:['목표 입력'],exclusions:[],assumptions:[],
  requirements:[{id:'R1',source:'마스터 목표',acceptance:'목표를 저장합니다',verification:'저장 후 새로고침으로 확인합니다',role_keys:['implementation']}],
  questions:[{id:'Q1',prompt:'대표 업무는 무엇인가요?',status:'answered',resolution:'웹사이트 제작'}],findings:[]};
const planHTML=planUI.render({...plan,content:{...plan.content,requirements_review:requirements},review:{verdict:'PASS',mode:'fixture',summary:'계획을 확인했습니다',findings:[]}});
assert.match(planHTML,/요구사항 · 검증/);assert.match(planHTML,/대표 업무는 무엇인가요/);
assert.match(planHTML,/출처: 마스터 목표/);
assert.match(planHTML,/계획 검수 · 통과 · 모의/);
const executionSource=await readFile(new URL('../../src/ai_company/web/execution-ui.js',import.meta.url),'utf8');
const {createExecutionUI,currentExecutionProposal}=await import('data:text/javascript;base64,'+Buffer.from(executionSource).toString('base64'));
const executionUI=createExecutionUI({esc,stamp:String});
const selection={catalog_id:'catalog',catalog_digest:'a'.repeat(64),allowed_paths:['src/only.py'],candidates:{developer:['dev']},role_candidates:{implementation:['dev']},budget:{max_cost_usd:.5}};
const entry={catalog_id:'catalog',catalog_digest:'a'.repeat(64),repository:'company/repo',base_branch:'main',base_sha:'b'.repeat(40),allowed_paths:['src/','tests/'],candidates:{developer:['dev'],final:['final']},agents:[{agent_id:'dev',model:'Claude <unsafe>',reasoning_effort:'xhigh',ultracode_enabled:true}],checks:{unit:{argv:['python','-m','unittest']}},budget:{max_cost_usd:1,max_runtime_seconds:300,max_executions:5,max_repairs:1},max_parallel:2,mode:'fixture',limitations:[]};
const proposed={...overview,plans:[{...plan,content:{...plan.content,execution_spec_proposal:selection}}]};
const proposedBefore=JSON.stringify(proposed);
const scopeHTML=executionUI.render(proposed,{entries:[entry],loaded:true});
assert.match(scopeHTML,/명세 저장/);assert.match(scopeHTML,/명세 저장은 계획 확정이나 실행 승인이 아닙니다/);
assert.match(scopeHTML,/Claude &lt;unsafe&gt;/);assert.doesNotMatch(scopeHTML,/<unsafe>/);
assert.match(scopeHTML,/USD 0.5/);assert.match(scopeHTML,/src\/only.py/);
assert.equal(JSON.stringify(proposed),proposedBefore);
assert.equal(currentExecutionProposal({...proposed,project:{...proposed.project,request_revision:3}}),null);
assert.match(executionUI.render(proposed,{entries:[{...entry,catalog_digest:'changed'}],loaded:true}),/data-action="save-execution-spec" disabled/);
assert.match(executionUI.render(proposed,{entries:[entry],loaded:true,connected:false}),/data-action="save-execution-spec" disabled/);
assert.match(executionUI.render(overview,{entries:[],loaded:true}),/두 파일/);
assert.doesNotMatch(ui.render(proposed,options),/data-action="review-plan"/);
assert.match(ui.render(proposed,options),/실행 범위 확인/);
const spec={version:1,digest:'c'.repeat(64),resolved:entry};
assert.match(executionUI.confirmation({...plan,execution_spec:{version:1,digest:spec.digest}},[spec]),/확정할 실행 범위/);
assert.match(executionUI.confirmation({...plan,execution_spec:{version:1,digest:'wrong'}},[spec]),/읽지 못했습니다/);
const reference={version:1,digest:spec.digest,catalog_id:entry.catalog_id,catalog_digest:entry.catalog_digest};
const newReference={...reference,version:2,digest:'d'.repeat(64)};
const replaced={...overview,project:{...overview.project,execution_spec:newReference},plans:[{...plan,execution_spec:reference}],pm_requests:[{request_revision:2,state:'completed',execution_spec:reference}]};
assert.equal(executionReferenceMatches(replaced.project,replaced.plans[0]),false);
assert.equal(managerSnapshot(replaced).plan,undefined,'a proposed old plan cannot remain current after a different specification is registered');
assert.doesNotMatch(ui.render(replaced,options),/data-action="review-plan"/);
assert.match(ui.render(replaced,options),/실행 명세가 바뀌었습니다/);
assert.match(ui.render(replaced,options),/새 계획 요청/);
assert.equal(executionReferenceMatches({execution_spec:reference},{execution_spec:{...reference,catalog_digest:'different'}}),false,'catalog binding belongs to the exact specification reference');
const pending={body:{selection},catalog:entry};
const newerProposal={...proposed,plans:[{...plan,content:{...plan.content,execution_spec_proposal:{...selection,allowed_paths:['src/newer.py']}}}]};
const pendingHTML=executionUI.render(newerProposal,{entries:[entry],loaded:true,intent:pending});
assert.match(pendingHTML,/이전 명세 요청/);assert.match(pendingHTML,/src\/only.py/);
assert.doesNotMatch(pendingHTML,/src\/newer.py/,'the visible pending request must describe the body that a retry sends');
assert.match(executionUI.render(newerProposal,{entries:[],loaded:false,intent:pending,error:'카탈로그 조회 실패'}),/저장 당시의 범위/,'the saved catalog snapshot remains available after connection loss');
const unavailableHTML=executionUI.render(overview,{entries:[],loaded:false,error:'카탈로그 조회 실패'});
assert.match(unavailableHTML,/카탈로그 조회 실패/);assert.doesNotMatch(unavailableHTML,/두 파일|카탈로그가 등록되지/,'a failed read is not proof of a missing catalog');
assert.match(executionUI.render(proposed,{entries:[{...entry,budget:{...entry.budget,max_cost_usd:null}}],loaded:true}),/지정된 Codex PM·최종 검수는 적격 후보 없음으로 차단/,'a finite PM selection must disclose executor restrictions even when its catalog is unbounded');
console.log('PASS: catalog-bound scope, escaped facts, unavailable catalog, pending-request display, current specification confirmation and finite-budget restriction');
await import('./execution_save_checks.mjs');
