import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../../src/ai_company/web/manager-ui.js',import.meta.url),'utf8');
const {managerSnapshot,createManagerUI}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const plan={id:'p',digest:'current',request_revision:2,status:'proposed',content:{summary:'Long original English specification',roles:[{key:'implementation',name:'Implement component',depends_on:[]},{key:'tests',name:'Test component',depends_on:[]},{key:'reviewer',name:'Review',depends_on:['implementation','tests']}],completion_criteria:['Do not deploy']}};
const overview={project:{id:'project',request_revision:2},plans:[plan],pm_requests:[{request_revision:2,state:'completed'}],runs:[{plan_id:'p',plan_digest:'old',state:'completed'}]};
assert.equal(managerSnapshot(overview).run,undefined,'a success for a different plan digest cannot advance this plan');
assert.equal(managerSnapshot(overview).independent,2,'dependency-bound review is not counted as an independent role');
assert.equal(managerSnapshot({...overview,project:{id:'project',request_revision:3},pm_requests:[{request_revision:3,state:'waiting_quota'}]}).plan,undefined,'a new request cannot offer the old plan for confirmation');
assert.equal(managerSnapshot({...overview,plans:[{...plan,status:'stale'}]}).plan,undefined);
const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const ui=createManagerUI({esc,badge:esc,label:esc,stamp:String,documents:{text:(id,field,fallback)=>fallback,meta:()=>''},planContent:()=>'<p>Full original constraints</p>'});
const options={connected:true,composer:'',history:'',technical:'',archive:''};
const before=JSON.stringify(overview),html=ui.render(overview,options);
assert.equal(JSON.stringify(overview),before,'overview rendering cannot mutate persisted data');
assert.ok(!html.includes('Long original English specification'),'untranslated prose is not the headline');
assert.match(html,/확정 전에는 이 계획의 작업을 시작하지 않습니다/);
assert.match(html,/details class="manager-plan-detail"/,'full original plan remains available');
assert.doesNotMatch(ui.render(overview,{...options,connected:false}),/data-action="review-plan"[^>]+(?<!disabled)>/);
const current={plan_id:'p',plan_digest:'current',state:'awaiting_approval',candidate_sha:'candidate',approval_id:'result-approval'};
assert.match(ui.render({...overview,runs:[{...current,roles:{implementation:{status:'RUNNING'}}}],roles:[{id:'live-role',plan_id:'p',key:'implementation',status:'WAITING_QUOTA'}]},options),/WAITING_QUOTA/,'current session quota state is visible before the coordinator updates its run summary');
assert.doesNotMatch(ui.render({...overview,runs:[current],approvals:[{status:'pending',artifact_sha:'unrelated'}]},options),/승인 요청 확인/,'unrelated approvals cannot become the next action for this run');
assert.match(ui.render({...overview,runs:[current],approvals:[{id:'result-approval',status:'pending',artifact_sha:'candidate'}]},options),/승인 요청 확인/);
assert.doesNotMatch(ui.render({...overview,runs:[current],approvals:[{id:'different-operation',status:'pending',artifact_sha:'candidate'}]},options),/승인 요청 확인/,'the same artifact cannot substitute another operation approval');
assert.doesNotMatch(ui.render({...overview,runs:[{...current,state:'running'}],approvals:[{id:'result-approval',status:'pending',artifact_sha:'candidate'}]},options),/승인 요청 확인|같은 후보의 검수가 끝났습니다/,'an active run cannot be promoted to completed review by a pending approval');
assert.match(ui.render({...overview,runs:[{...current,state:'pending'}]},options),/실행 준비/,'a queued execution is not presented as already running');
const quotaRequest={...overview,plans:[],runs:[],pm_requests:[{request_revision:2,state:'running',updated_at:1000,
  execution:{status:'WAITING_CAPACITY',reason:'공유 계정 사용량이 회복될 때까지 기다립니다.',resume_at:2100}}]};
const quotaHTML=ui.render(quotaRequest,options);
assert.doesNotMatch(quotaHTML,/PM 답변 작성 중|PM이 답변을 작성하고 있습니다/,'persisted PM request running does not override its actual execution wait');
assert.match(quotaHTML,/공유 계정 사용량이 회복될 때까지 기다립니다/,'nested execution wait reason is visible');
assert.match(quotaHTML,/2100/,'the recorded nested execution resume time is visible');
console.log('PASS: current revision/digest, dependency counts, read-only projection, original access, disconnected confirmation and candidate-bound next action');
