/* Real read API, temporary SQLite fixture. No operational state or models. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const {createHash}=require('node:crypto');
(async()=>{
 const base=process.env.BASE_URL,fixtures=JSON.parse(process.env.GRAPH_FIXTURES),out=process.env.UI_OUTPUT||'/tmp/ai-company-graph-ui';
 await fs.mkdir(out,{recursive:true});
 const browser=await chromium.launch({headless:true,chromiumSandbox:true,...(process.env.CHROME_CHANNEL?{channel:process.env.CHROME_CHANNEL}:{}),...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block',reducedMotion:'reduce'}),page=await context.newPage();page.setDefaultTimeout(8000);
 const errors=[],writes=[],checks=[],cameraReadings=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('request',r=>{if(r.method()!=='GET')writes.push(new URL(r.url()).pathname);});
 const action=name=>page.locator(`[data-rg-action="${name}"]`).click();
 const go=async(hash)=>{await page.evaluate(value=>{location.hash=value;},hash);await page.waitForTimeout(250);};
 const shot=async name=>{await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,`workspace-graph-${name}.png`),fullPage:true});};
 const graph=()=>page.locator('[data-rg-root]');
 const pointerCenter=async locator=>{
  // Move only the page. Scrolling a node's ancestors must not create a second,
  // untracked camera inside the transform-controlled graph viewport.
  await locator.evaluate(node=>{
   const viewport=node.closest('.rg-viewport').getBoundingClientRect();
   window.scrollBy(0,viewport.top+Math.min(viewport.height,innerHeight)/2-innerHeight/2);
  });
  return locator.evaluate(node=>{
   const box=node.getBoundingClientRect(),viewport=node.closest('.rg-viewport').getBoundingClientRect();
   const left=Math.max(0,box.left,viewport.left),right=Math.min(innerWidth,box.right,viewport.right);
   const top=Math.max(0,box.top,viewport.top),bottom=Math.min(innerHeight,box.bottom,viewport.bottom);
   if(right<=left||bottom<=top)throw new Error('Pointer target is outside the visible graph');
   const point={x:(left+right)/2,y:(top+bottom)/2};
   if(document.elementFromPoint(point.x,point.y)?.closest('[data-rg-node]')!==node)throw new Error('Pointer target is covered');
   return point;
  });
 };
 const snapshot=async id=>{await page.locator('#rg-snapshot').selectOption(id);};
 const overflow=async label=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),label+' page overflow');
 try{
  await page.goto(base+'/?workspace=integrated#projects');
  await page.getByLabel('비밀번호',{exact:true}).fill(process.env.TEST_PASSWORD);
  await page.getByRole('button',{name:'로그인',exact:true}).click();
  await page.getByLabel('현재 비밀번호',{exact:true}).fill(process.env.TEST_PASSWORD);
  await page.getByLabel('새 비밀번호',{exact:true}).fill('graph-browser-only-strong-password');
  await page.getByLabel('새 비밀번호 확인',{exact:true}).fill('graph-browser-only-strong-password');
  await page.getByRole('button',{name:'비밀번호 변경 후 계속'}).click();await page.locator('.nav').waitFor();await page.waitForTimeout(4200);
  const envelope=await page.evaluate(async id=>(await(await fetch('/api/projects/'+id+'/overview')).json()).workspace_graph,fixtures.project_id);
  assert.equal(envelope.project_id,fixtures.project_id);assert.ok(envelope.snapshots.every(s=>s.source==='fixture'));
  const current=envelope.snapshots.find(s=>s.run_id===fixtures.run_ids[1]),old=envelope.snapshots.find(s=>s.run_id===fixtures.run_ids[0]),planned=envelope.snapshots.find(s=>!s.run_id);
  assert.ok(current&&old&&planned);assert.equal(current.approval_refs.length,0);assert.equal(old.approval_refs.length,1);
  await go('#progress?project='+fixtures.project_id);await graph().waitFor();
  for(const width of [1440,390,320])for(const theme of ['light','black']){
   await page.setViewportSize({width,height:width>700?1000:844});await page.locator(`[data-theme-choice=${theme}]`).click();
   await snapshot(current.id);await action('graph');await overflow(`${width}/${theme}`);
   assert.equal(await page.locator('.rg-node').count(),current.nodes.length);
   assert.equal(await page.locator('.rg-edge-hit').count(),current.edges.length);
   assert.ok(await page.locator('.rg-lines').isVisible());
   const reading=await page.locator('.rg-viewport').evaluate(viewport=>{
    const bounds=element=>{const r=element.getBoundingClientRect();return {left:r.left,right:r.right,width:r.width};};
    return {viewport:bounds(viewport),first:bounds(viewport.querySelector('.rg-node')),clientWidth:viewport.clientWidth,scrollLeft:viewport.scrollLeft,scrollTop:viewport.scrollTop,transform:viewport.querySelector('.rg-scene').style.transform};
   });
   cameraReadings.push({width,theme,...reading});
   assert.ok(reading.first.left>=reading.viewport.left-1&&reading.first.right<=reading.viewport.right+1,`initial ${width}/${theme} role must be fully visible horizontally: ${JSON.stringify(reading)}`);
   assert.equal(reading.scrollLeft,0,'native horizontal scrolling must not move the graph');
   assert.equal(reading.scrollTop,0,'native vertical scrolling must not move the graph');
   await shot(`${theme}-${width}`);
   const first=page.locator('.rg-node').first();await first.click();await page.locator('.rg-detail h3').waitFor();await overflow('detail');
   await shot(`${theme}-${width}-detail`);await action('clear');
   const sizes=await page.locator('.rg-tools button,.rg-header select').evaluateAll(nodes=>nodes.map(n=>({w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height})));
   assert.ok(sizes.every(b=>b.w>=44&&b.h>=44));
  }
  checks.push('Light/Black × 320/390/1440; Korean render; graph visible, no page overflow, 44px controls');
  await page.setViewportSize({width:1440,height:1000});await page.locator('[data-theme-choice=light]').click();await snapshot(current.id);
  const firstId=current.nodes[0].id;const first=()=>page.locator(`[data-rg-node="${firstId}"]`);
  await first().click();const selection=await page.locator('.rg-detail h3').textContent();
  await first().press('Alt+ArrowRight');const pos=await first().getAttribute('style');
  await action('zoom-in');const transform=await page.locator('.rg-scene').getAttribute('style');
  await first().focus();
  await page.waitForTimeout(5500);
  assert.equal(await first().getAttribute('style'),pos);assert.equal(await page.locator('.rg-scene').getAttribute('style'),transform);
  assert.equal(await page.locator('.rg-detail h3').textContent(),selection);assert.equal(await page.evaluate(()=>document.activeElement.dataset.rgNode),firstId);
  await snapshot(old.id);await snapshot(current.id);assert.equal(await first().getAttribute('style'),pos);
  checks.push('5-second actual API refresh preserves selection, focus, position, zoom; past run switch does not overwrite current view');
  await action('clear');await action('list');
  const transfer=current.edges.find(e=>e.artifact_refs.length);assert.ok(transfer);
  await page.locator(`[data-rg-edge="${transfer.id}"]`).click();assert.ok((await page.locator('.rg-detail').textContent()).includes(transfer.artifact_refs[0].sha));
  await shot('list-transfer');await action('clear');await action('graph');await action('fit');
  await page.locator(`[data-rg-edge="${transfer.id}"]`).focus();await page.keyboard.press('Enter');assert.ok((await page.locator('.rg-detail').textContent()).includes(transfer.artifact_refs[0].sha));
  await shot('graph-transfer');await action('clear');
  await snapshot(planned.id);assert.ok(await graph().getByText('예시 기록 · 실제 실행 아님',{exact:true}).count());
  assert.ok(await page.locator('.rg-node.is-planned').count());assert.equal(await page.locator('.rg-reference-links a').count(),0);
  await snapshot(old.id);await page.locator('.rg-reference-links a[href^="#approvals"]').click();await page.locator('.approval-reading').waitFor();
  assert.ok(page.url().includes('run='+encodeURIComponent(fixtures.run_ids[0])));assert.ok((await page.locator('.approval-reading').textContent()).includes('이전 예시 후보 수용'));
  await shot('approval-light-1440');
  await go('#reports?project='+fixtures.project_id+'&run='+fixtures.run_ids[0]);
  await page.locator('.nav a[aria-label="승인"]').click();await page.waitForTimeout(300);assert.ok(!new URL(page.url()).hash.includes('run='),'global nav clears run filter');
  await go('#approvals?project='+fixtures.project_id+'&run='+fixtures.run_ids[1]);assert.equal(await page.locator('.approval-reading').count(),0);assert.ok((await page.locator('#main').textContent()).includes('승인 요청'));
  checks.push('graph/list identical artifact; keyboard edge activation; planned vs recorded; exact-run approval; global navigation clears filter');
  await go('#progress?project='+fixtures.other_project_id);await graph().waitFor();assert.equal(await page.locator('.rg-node').count(),0);
  await go('#progress?project='+fixtures.project_id);await graph().waitFor();assert.equal(await page.locator('#rg-snapshot').inputValue(),old.id);
  await snapshot(current.id);await action('list');
  await context.setOffline(true);await page.evaluate(()=>window.dispatchEvent(new Event('offline')));await page.getByText('연결이 끊겼습니다. 마지막 조회 자료를 표시합니다.',{exact:true}).waitFor();
  assert.equal(await page.locator('.rg-list [data-rg-node]').count(),current.nodes.length);
  await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.getByText('연결이 끊겼습니다. 마지막 조회 자료를 표시합니다.',{exact:true}).waitFor({state:'hidden'});
  checks.push('project isolation, selected run restoration, offline read preservation, reconnect');
  await page.setViewportSize({width:390,height:844});await action('list');
  const readingNode=current.nodes.find(n=>n.kind==='role');
  await page.locator(`[data-rg-node="${readingNode.id}"]`).click();
  assert.equal(await page.evaluate(()=>document.activeElement.id),'rg-detail-heading');
  await page.locator('.rg-detail details').first().locator('summary').click();
  await page.locator('.rg-detail').evaluate(panel=>{panel.scrollTop=180;});
  const readingScroll=await page.locator('.rg-detail').evaluate(panel=>panel.scrollTop);
  assert.ok(readingScroll>0);await page.waitForTimeout(5500);
  assert.ok(Math.abs(await page.locator('.rg-detail').evaluate(panel=>panel.scrollTop)-readingScroll)<2);
  assert.equal(await page.locator('.rg-detail details').first().evaluate(d=>d.open),true);
  await page.locator('#rg-detail-heading').focus();await page.keyboard.press('Escape');
  assert.equal(await page.locator('.rg-detail.is-open').count(),0);assert.equal(await page.evaluate(()=>document.activeElement.dataset.rgNode),readingNode.id);
  checks.push('mobile details preserve scroll and expanded evidence through real 5-second refresh; focus enters detail and Escape returns to selected node');
  await action('graph');await action('pan');
  const node=page.locator('.rg-node').first();
  let point=await pointerCenter(node);const tapPosition=await node.getAttribute('style');
  await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+2,point.y+1);await page.mouse.up();
  await page.locator('.rg-detail.is-open').waitFor();
  assert.equal(await node.getAttribute('style'),tapPosition,'a small pointer wobble selects without moving the role');
  await action('clear');point=await pointerCenter(node);const before=await node.getAttribute('style');
  await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+25,point.y+30,{steps:5});await page.mouse.up();assert.notEqual(await node.getAttribute('style'),before);
  assert.equal(await page.locator('.rg-detail.is-open').count(),0,'finishing a drag must not select a role');
  await node.click();await page.locator('.rg-detail.is-open').waitFor();
  checks.push('sub-threshold pointer wobble keeps placement; drag suppresses only its own click; the next tap opens details');
  await action('clear');await action('zoom-in');await node.press('Alt+ArrowRight');
  const mobilePosition=await node.getAttribute('style'),camera=await page.locator('.rg-scene').evaluate(el=>el.style.transform);
  await page.setViewportSize({width:844,height:390});
  await page.waitForFunction(()=>document.querySelector('.rg-node')?.style.width==='206px');
  await pointerCenter(node);
  await node.press('Alt+ArrowDown');const widePosition=await node.getAttribute('style'),wideCamera=await page.locator('.rg-scene').evaluate(el=>el.style.transform);
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.querySelector('.rg-node')?.style.width==='132px');
  assert.equal(await node.getAttribute('style'),mobilePosition,'returning to mobile restores its custom placement');
  assert.equal(await page.locator('.rg-scene').evaluate(el=>el.style.transform),camera,'returning to mobile restores its own camera');
  await page.setViewportSize({width:844,height:390});
  await page.waitForFunction(()=>document.querySelector('.rg-node')?.style.width==='206px');
  assert.equal(await node.getAttribute('style'),widePosition,'returning to wide layout restores its custom placement');
  assert.equal(await page.locator('.rg-scene').evaluate(el=>el.style.transform),wideCamera,'returning to wide layout restores its own camera');
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.querySelector('.rg-node')?.style.width==='132px');
  checks.push('700px breakpoint restores each width\'s camera and custom placement; role remains a visible pointer target');
  await pointerCenter(node);await shot('motion-mobile-390');
  // An explicitly injected changed read arrives while the physical pointer stays down.
  const overviewPath=`/api/projects/${fixtures.project_id}/overview`;
  const original=await page.evaluate(async url=>(await fetch(url)).json(),overviewPath);
  const updated=structuredClone(original),updatedNode=updated.workspace_graph.snapshots.find(s=>s.id===current.id).nodes[0];
  updatedNode.name='갱신된 역할';
  updated.workspace_graph.fingerprint=createHash('sha256').update(JSON.stringify(updated.workspace_graph.snapshots)).digest('hex');
  await page.route('**'+overviewPath,route=>route.fulfill({status:200,contentType:'application/json',json:updated}));
  await action('fit');point=await pointerCenter(node);
  await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+15,point.y+15);
  const held=await node.elementHandle(),positionDuringDrag=await node.getAttribute('style');
  const changedRead=await page.waitForResponse(response=>new URL(response.url()).pathname===overviewPath,{timeout:12000});
  await changedRead.finished();await page.waitForTimeout(150);
  assert.ok(await held.evaluate(el=>el.isConnected),'a changed poll must not replace the active drag target');
  assert.notEqual(await node.locator('strong').textContent(),updatedNode.name,'read is applied after the gesture');
  await page.mouse.move(point.x+25,point.y+25);
  assert.notEqual(await node.getAttribute('style'),positionDuringDrag,'the original pointer still moves the role');
  await page.mouse.up();await node.locator('strong').filter({hasText:updatedNode.name}).waitFor();
  assert.equal(await page.locator('.rg-detail.is-open').count(),0,'the completed drag stays unselected after the queued update');
  // A queued response after a mobile tap must leave focus in the opened details.
  updatedNode.name='탭으로 연 역할';
  updated.workspace_graph.fingerprint=createHash('sha256').update(JSON.stringify(updated.workspace_graph.snapshots)).digest('hex');
  point=await pointerCenter(node);await page.mouse.move(point.x,point.y);await page.mouse.down();
  await (await page.waitForResponse(response=>new URL(response.url()).pathname===overviewPath,{timeout:12000})).finished();
  await page.mouse.up();await page.locator('#rg-detail-heading').filter({hasText:updatedNode.name}).waitFor();
  assert.equal(await page.evaluate(()=>document.activeElement.id),'rg-detail-heading','queued mobile tap update retains detail focus');
  await action('clear');
  // Offline must settle a queued replacement snapshot before rendering its geometry.
  const replacement=structuredClone(updated.workspace_graph.snapshots.find(s=>s.id===current.id));
  replacement.id='gesture-replacement-snapshot';replacement.nodes[0].name='연결 전 마지막 역할';
  updated.workspace_graph.snapshots=[replacement];updated.workspace_graph.default_snapshot_id=replacement.id;
  updated.workspace_graph.fingerprint=createHash('sha256').update(JSON.stringify(updated.workspace_graph.snapshots)).digest('hex');
  point=await pointerCenter(node);await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+10,point.y+10);
  const beforeDisconnect=await node.elementHandle();
  await (await page.waitForResponse(response=>new URL(response.url()).pathname===overviewPath,{timeout:12000})).finished();
  await page.waitForTimeout(150);await context.setOffline(true);await page.evaluate(()=>window.dispatchEvent(new Event('offline')));
  await page.getByText('연결이 끊겼습니다. 마지막 조회 자료를 표시합니다.',{exact:true}).waitFor();
  assert.equal(await page.locator('[data-rg-root]').getAttribute('data-snapshot'),replacement.id,'offline render uses the queued replacement snapshot');
  assert.ok(await page.locator('.rg-node').count(),'replacement snapshot has mounted geometry');
  assert.equal(await beforeDisconnect.evaluate(el=>el.isConnected),false,'offline is not deferred behind the held pointer');
  await page.mouse.up();await action('list');
  await page.getByText('연결이 끊겼습니다. 마지막 조회 자료를 표시합니다.',{exact:true}).waitFor();
  await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event('online')));
  await page.getByText('연결이 끊겼습니다. 마지막 조회 자료를 표시합니다.',{exact:true}).waitFor({state:'hidden'});
  await action('graph');
  await page.unroute('**'+overviewPath);
  checks.push('queued response retains drag and mobile tap focus; offline switches to a replacement snapshot without geometry error and preserves disconnected state');
  if(await page.locator('[data-rg-action=pan]').getAttribute('aria-pressed')==='true')await action('pan');
  assert.equal(await page.locator('.rg-viewport').evaluate(el=>getComputedStyle(el).touchAction),'pan-y');
  const cdp=await context.newCDPSession(page);
  await cdp.send('Emulation.setDeviceMetricsOverride',{width:720,height:500,deviceScaleFactor:2,mobile:false});
  await overflow('200% equivalent CSS viewport reflow');await shot('zoom-200-equivalent');
  await cdp.send('Emulation.clearDeviceMetricsOverride');await cdp.detach();await page.setViewportSize({width:390,height:844});
  await go('#manager?project='+fixtures.project_id);await page.locator('.manager-home').waitFor();await shot('manager-light-390');await overflow('manager');
  await go('#approvals?project='+fixtures.project_id+'&run='+fixtures.run_ids[0]);await page.locator('.approval-reading').waitFor();await shot('approval-light-390');await overflow('approval');
  checks.push('mobile drag and normal page scroll; reduced motion; 200% equivalent viewport reflow; dialogue and approval composition');
  await go('#progress?project='+fixtures.project_id);await graph().waitFor();
  if(await page.locator('[data-rg-action=pan]').getAttribute('aria-pressed')!=='true')await action('pan');
  await action('fit');const expiryNode=page.locator('.rg-node').first(),expiryPoint=await pointerCenter(expiryNode);
  await page.route('**'+overviewPath,route=>route.fulfill({status:401,contentType:'application/json',json:{error:{code:'unauthorized'}}}));
  await page.mouse.move(expiryPoint.x,expiryPoint.y);await page.mouse.down();await page.mouse.move(expiryPoint.x+10,expiryPoint.y+10);
  const authenticatedNode=await expiryNode.elementHandle();
  await page.getByRole('button',{name:'로그인',exact:true}).waitFor({timeout:12000});
  assert.equal(await authenticatedNode.evaluate(el=>el.isConnected),false,'authentication expiry is never held behind a gesture');
  await page.mouse.up();
  checks.push('injected 401 during held drag immediately removes the authenticated graph and clears interaction state');
  assert.deepEqual(writes,['/api/login','/api/password'],'graph interactions never write execution or approvals');assert.deepEqual(errors,[]);
  await fs.writeFile(path.join(out,'workspace-graph-validation.json'),JSON.stringify({status:'PASS',source:'temporary SQLite + actual ManagementHTTPServer; fixture model facts',checks,camera_readings:cameraReadings,write_paths:writes},null,2));
  console.log(JSON.stringify({status:'PASS',checks}));
 }catch(error){await shot('failure').catch(()=>{});console.error({url:page.url(),errors});throw error;}
 finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
