/* Tests the preview's rehearsal state only; production contracts have separate tests. */
const assert=require('node:assert/strict');
const {webcrypto}=require('node:crypto');
globalThis.crypto ||= webcrypto;
const data=require('../../src/ai_company/web/workspace-preview/data.js');
const {create}=require('../../src/ai_company/web/workspace-preview/model.js');
(async()=>{
 const m=create(data),id='fixture-pilot';
 await assert.rejects(m.message(id,'hello','fixture-readonly',{readOnly:true}),/권한/);
 await assert.rejects(m.message(id,'hello','fixture-offline',{offline:true}),/연결/);
 assert.equal(m.state.events.length,0);
 await m.message(id,'알 수 없음으로 분류','fixture-answer');
 await assert.rejects(m.saveSpec(id,'fixture-spec',{loseResponse:true}),/응답/);
 const spec=await m.saveSpec(id,'fixture-spec');
 assert.equal(spec.execution_spec.version,1);
 assert.equal(m.project(id).runs.length,0);
 const plans=await Promise.all(Array.from({length:6},()=>m.requestPlan(id,'fixture-plan-key')));
 assert.equal(new Set(plans.map(p=>p.plan_id)).size,1);
 const plan=plans[0];
 const payload={plan_id:plan.plan_id,plan_digest:plan.plan_digest,execution_spec_digest:spec.execution_spec.digest,reviewed:true,idempotency_key:'fixture-confirm'};
 await assert.rejects(m.confirm(id,{...payload,plan_digest:'z'.repeat(64),idempotency_key:'fixture-wrong'}),/바뀌었/);
 await assert.rejects(m.confirm('fixture-notes',payload),/바뀌었/);
 const results=await Promise.all(Array.from({length:6},()=>m.confirm(id,payload)));
 assert.equal(new Set(results.map(r=>r.run_id)).size,1);
 assert.equal(m.project(id).runs.length,1);
 assert.equal(m.project('fixture-notes').runs.length,0);
 const original=JSON.stringify(m.project(id).runs[0]);
 await m.message(id,'다시 검토','fixture-answer2');
 await m.saveSpec(id,'fixture-spec2');
 assert.equal(m.project(id).spec.version,2);
 assert.equal(JSON.stringify(m.project(id).runs[0]),original);
 await assert.rejects(m.confirm(id,{...payload,idempotency_key:'fixture-stale'}),/바뀌었/);
 const a=data.approval,choice={approval_id:a.id,subject_digest:a.subject_digest,artifact_sha:a.artifact_sha,decision:'approve',reviewed:true,idempotency_key:'fixture-choice'};
 await assert.rejects(m.decide('fixture-notes',choice),/대상/);
 await assert.rejects(m.decide(id,{...choice,subject_digest:'wrong'}),/대상/);
 await m.decide(id,choice);
 assert.equal(data.approval.status,'pending');
 assert.equal(m.original.approval.status,'pending');
 const restored=create(data,m.state);
 assert.deepEqual(await restored.confirm(id,payload),results[0]);
 assert.equal(restored.project(id).runs.length,1);
 const creation=await Promise.all(Array.from({length:6},()=>m.createProject('새 프로젝트','자연어 목표','fixture-create')));
 assert.equal(new Set(creation.map(r=>r.project_id)).size,1);
 assert.equal(m.state.projects.length,3);
 await assert.rejects(m.createProject('다른 내용','자연어 목표','fixture-create'),/내용/);
 assert.equal(m.state.events.filter(e=>e.kind==='plan_confirmed').length,1);
 console.log('Preview model: isolation, lost response, concurrent retries, immutable run/spec and candidate binding PASS');
})().catch(error=>{console.error(error);process.exitCode=1;});
