/* Real read API, temporary SQLite fixture. No operational state or models. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
(async()=>{
 const base=process.env.BASE_URL,fixtures=JSON.parse(process.env.GRAPH_FIXTURES),out=process.env.UI_OUTPUT||'/tmp/ai-company-graph-ui';
 await fs.mkdir(out,{recursive:true});
 const browser=await chromium.launch({headless:true,chromiumSandbox:true,...(process.env.CHROME_CHANNEL?{channel:process.env.CHROME_CHANNEL}:{}),...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block',reducedMotion:'reduce'}),page=await context.newPage();page.setDefaultTimeout(8000);
 const errors=[],writes=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('request',r=>{if(r.method()!=='GET')writes.push(new URL(r.url()).pathname);});
 const action=name=>page.locator(`[data-rg-action="${name}"]`).click();
 const go=async(hash)=>{await page.evaluate(value=>{location.hash=value;},hash);await page.waitForTimeout(250);};
 const shot=async name=>{await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,`workspace-graph-${name}.png`),fullPage:true});};
 const graph=()=>page.locator('[data-rg-root]');
 const snapshot=async id=>{await page.locator('#rg-snapshot').selectOption(id);};
 const overflow=async label=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),label+' page overflow');
 try{
  await page.goto(base+'/?workspace=integrated#projects');
  await page.getByLabel('비밀번호',{exact:true}).fill(process.env.TEST_PASSWORD);
  await page.getByRole('button',{name:'로그인',exact:true}).click();
  await page.getByLabel('현재 비밀번호',{exact:true}).fill(process.env.TEST_PASSWORD);
  await page.getByLabel('새 비밀번호',{exact:true}).fill('graph-browser-only-strong-password');
  await page.getByLabel('새 비밀번호 확인',{exact:true}).fill('graph-browser-only-strong-password');
  await page.getByRole('button',{name:'비밀번호 변경 후 계속'}).click();await page.locator('.nav').waitFor();
  const envelope=await page.evaluate(async id=>(await(await fetch('/api/projects/'+id+'/overview')).json()).workspace_graph,fixtures.project_id);
  assert.equal(envelope.project_id,fixtures.project_id);assert.ok(envelope.snapshots.every(s=>s.source==='fixture'));
  const current=envelope.snapshots.find(s=>s.run_id===fixtures.run_ids[1]),old=envelope.snapshots.find(s=>s.run_id===fixtures.run_ids[0]),planned=envelope.snapshots.find(s=>!s.run_id);
  assert.ok(current&&old&&planned);assert.equal(current.approval_refs.length,0);assert.equal(old.approval_refs.length,1);
  await go('#progress?project='+fixtures.project_id);await graph().waitFor();
  for(const width of [1440,390,320])for(const theme of ['light','black']){
   await page.setViewportSize({width,height:width>700?1000:844});await page.locator(`[data-theme-choice=${theme}]`).click();
   await snapshot(current.id);await action('graph');await overflow(`${width}/${theme}`);
   assert.equal(await page.locator('.rg-node').count(),current.nodes.length);
   assert.equal(await page.locator('.rg-edge-hit').count(),current.edges.length);
   assert.ok(await page.locator('.rg-lines').isVisible());
   await shot(`${theme}-${width}`);
   const first=page.locator('.rg-node').first();await first.click();await page.locator('.rg-detail h3').waitFor();await overflow('detail');
   await shot(`${theme}-${width}-detail`);await action('clear');
   const sizes=await page.locator('.rg-tools button,.rg-header select').evaluateAll(nodes=>nodes.map(n=>({w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height})));
   assert.ok(sizes.every(b=>b.w>=44&&b.h>=44));
  }
  checks.push('Light/Black × 320/390/1440; Korean render; graph visible, no page overflow, 44px controls');
  await page.setViewportSize({width:1440,height:1000});await page.locator('[data-theme-choice=light]').click();await snapshot(current.id);
  const firstId=current.nodes[0].id;const first=()=>page.locator(`[data-rg-node="${firstId}"]`);
  await first().click();const selection=await page.locator('.rg-detail h3').textContent();
  await first().press('Alt+ArrowRight');const pos=await first().getAttribute('style');
  await action('zoom-in');const transform=await page.locator('.rg-scene').getAttribute('style');
  await first().focus();
  await page.waitForTimeout(5500);
  assert.equal(await first().getAttribute('style'),pos);assert.equal(await page.locator('.rg-scene').getAttribute('style'),transform);
  assert.equal(await page.locator('.rg-detail h3').textContent(),selection);assert.equal(await page.evaluate(()=>document.activeElement.dataset.rgNode),firstId);
  await snapshot(old.id);await snapshot(current.id);assert.equal(await first().getAttribute('style'),pos);
  checks.push('5-second actual API refresh preserves selection, focus, position, zoom; past run switch does not overwrite current view');
  await action('clear');await action('list');
  const transfer=current.edges.find(e=>e.artifact_refs.length);assert.ok(transfer);
  await page.locator(`[data-rg-edge="${transfer.id}"]`).click();assert.ok((await page.locator('.rg-detail').textContent()).includes(transfer.artifact_refs[0].sha));
  await shot('list-transfer');await action('clear');await action('graph');await action('fit');
  await page.locator(`[data-rg-edge="${transfer.id}"]`).focus();await page.keyboard.press('Enter');assert.ok((await page.locator('.rg-detail').textContent()).includes(transfer.artifact_refs[0].sha));
  await shot('graph-transfer');await action('clear');
  await snapshot(planned.id);assert.ok(await graph().getByText('예시 기록 · 실제 실행 아님',{exact:true}).count());
  assert.ok(await page.locator('.rg-node.is-planned').count());assert.equal(await page.locator('.rg-reference-links a').count(),0);
  await snapshot(old.id);await page.locator('.rg-reference-links a[href^="#approvals"]').click();await page.locator('.approval-reading').waitFor();
  assert.ok(page.url().includes('run='+encodeURIComponent(fixtures.run_ids[0])));assert.ok((await page.locator('.approval-reading').textContent()).includes('이전 예시 후보 수용'));
  await shot('approval-light-1440');
  await go('#reports?project='+fixtures.project_id+'&run='+fixtures.run_ids[0]);
  await page.locator('.nav a[aria-label="승인"]').click();await page.waitForTimeout(300);assert.ok(!new URL(page.url()).hash.includes('run='),'global nav clears run filter');
  await go('#approvals?project='+fixtures.project_id+'&run='+fixtures.run_ids[1]);assert.equal(await page.locator('.approval-reading').count(),0);assert.ok((await page.locator('#main').textContent()).includes('승인 요청'));
  checks.push('graph/list identical artifact; keyboard edge activation; planned vs recorded; exact-run approval; global navigation clears filter');
  await go('#progress?project='+fixtures.other_project_id);await graph().waitFor();assert.equal(await page.locator('.rg-node').count(),0);
  await go('#progress?project='+fixtures.project_id);await graph().waitFor();assert.equal(await page.locator('#rg-snapshot').inputValue(),old.id);
  await snapshot(current.id);await action('list');
  await context.setOffline(true);await page.evaluate(()=>window.dispatchEvent(new Event('offline')));await page.getByText('연결이 끊겼습니다. 마지막 조회 자료를 표시합니다.',{exact:true}).waitFor();
  assert.equal(await page.locator('.rg-list [data-rg-node]').count(),current.nodes.length);
  await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.getByText('연결이 끊겼습니다. 마지막 조회 자료를 표시합니다.',{exact:true}).waitFor({state:'hidden'});
  checks.push('project isolation, selected run restoration, offline read preservation, reconnect');
  await page.setViewportSize({width:390,height:844});await action('graph');await action('pan');
  const node=page.locator('.rg-node').first();await node.scrollIntoViewIfNeeded();const box=await node.boundingBox(),before=await node.getAttribute('style');
  await page.mouse.move(box.x+20,box.y+20);await page.mouse.down();await page.mouse.move(box.x+45,box.y+50,{steps:5});await page.mouse.up();assert.notEqual(await node.getAttribute('style'),before);
  await action('pan');assert.equal(await page.locator('.rg-viewport').evaluate(el=>getComputedStyle(el).touchAction),'pan-y');
  await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});await overflow('200%');await page.evaluate(()=>{document.documentElement.style.fontSize='';});
  await go('#manager?project='+fixtures.project_id);await page.locator('.manager-home').waitFor();await shot('manager-light-390');await overflow('manager');
  await go('#approvals?project='+fixtures.project_id+'&run='+fixtures.run_ids[0]);await page.locator('.approval-reading').waitFor();await shot('approval-light-390');await overflow('approval');
  checks.push('mobile drag and normal page scroll; reduced motion; text zoom; dialogue and approval composition');
  assert.deepEqual(writes,['/api/login','/api/password'],'graph interactions never write execution or approvals');assert.deepEqual(errors,[]);
  await fs.writeFile(path.join(out,'workspace-graph-validation.json'),JSON.stringify({status:'PASS',source:'temporary SQLite + actual ManagementHTTPServer; fixture model facts',checks,write_paths:writes},null,2));
  console.log(JSON.stringify({status:'PASS',checks}));
 }catch(error){await shot('failure').catch(()=>{});console.error({url:page.url(),errors});throw error;}
 finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
