/* Standalone design rehearsal: deliberately has no network or production adapter. */
(()=>{
'use strict';
const root=document.querySelector('#workspace-lab'),stage=document.querySelector('#lab-stage'),dialog=document.querySelector('#lab-dialog');
const data=window.WorkspacePreviewData,KEY='ai-company:workspace-design:v1';
let saved;try{saved=JSON.parse(sessionStorage.getItem(KEY)||'null');}catch{}
const model=window.WorkspacePreviewModel.create(data,saved?.model);
const ui={concept:'a',theme:'light',view:'workspace',project:'fixture-pilot',tab:'pm',scenario:'normal',drafts:{},keys:{},...saved?.ui};
let busy=false,lastFocus=null,noticeTimer,resetting=false;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const short=value=>String(value).slice(0,12);
const button=(text,action,extra='')=>`<button type="button" data-action="${action}" ${extra}>${text}</button>`;
const tag=(text,kind='')=>`<span class="tag ${kind}">${esc(text)}</span>`;
const draft=name=>ui.drafts[name]||'';
const next=p=>({question:'PM 질문에 답하기',empty:'목표 구체화하기',proposal:'명세 확인·저장',spec_saved:'새 계획 요청',plan_ready:'계획 검토·확정',running:'진행 확인'}[p.phase]||'상태 확인');
function persist(){if(resetting)return;try{sessionStorage.setItem(KEY,JSON.stringify({model:model.state,ui}));}catch{}}
function announce(text){clearTimeout(noticeTimer);document.querySelector('#lab-notice').textContent=text;noticeTimer=setTimeout(()=>document.querySelector('#lab-notice').textContent='',9000);}
function context(){return {readOnly:ui.scenario==='readonly',offline:ui.scenario==='offline',loseResponse:ui.scenario==='error'};}
function current(){return model.state.projects.find(p=>p.id===ui.project);}
function tabs(){return `<nav class="tabs" aria-label="프로젝트">${[['pm','매니저'],['team','진행'],['approval','승인'],['report','보고']].map(([id,name])=>button(name,'tab',`data-tab="${id}" aria-current="${ui.tab===id?'page':'false'}"`)).join('')}</nav>`;}
function rail(){return `<aside class="rail"><div class="brand">AI Company</div><nav aria-label="전체">${button('프로젝트','projects',`class="${ui.view==='projects'?'selected':''}"`)}${button('작업실','workspace',`class="${ui.view==='workspace'?'selected':''}"`)}</nav><div class="rail-bottom">${button(ui.theme==='light'?'Black':'Light','theme','id="lab-theme" aria-label="테마 전환"')}<span class="account"><span class="avatar">E</span>edward <small>예시</small></span></div></aside>`;}
function technical(p){return `<details class="technical"><summary>실행 범위</summary><p>이 미리보기는 두 파일만 사용하는 검증 프로젝트를 예로 듭니다. 명세 저장은 실행 승인이 아닙니다.</p><dl><dt>저장소 · 기준</dt><dd>${esc(data.catalog.repository)}<br>${esc(data.catalog.branch)}<code>${esc(data.catalog.base_sha)}</code></dd><dt>허용 파일</dt><dd>${data.catalog.paths.map(s=>`<code>${esc(s)}</code>`).join('')}</dd><dt>검증</dt><dd>빈 입력 · 다섯 분류 · 알 수 없는 상태 · 입력 불변<br>격리 검사 → 원격 CI → 독립 검수 → Astra 최종 검수</dd><dt>예산 · 예시 설정</dt><dd>최대 24회 · 30분 · 수정 2회 · 병렬 2개<br>금액 상한 미설정. 운영 예산을 바꾸지 않습니다.</dd><dt>명세</dt><dd>${p.spec?`버전 ${p.spec.version}<code>${esc(p.spec.digest)}</code>`:'아직 저장하지 않음'}</dd><dt>프로젝트</dt><dd><code>${esc(p.id)}</code></dd></dl></details>`;}
function rolePlan(){return data.roles.map(r=>`<div class="plan-role"><div class="row"><h3>${r.name}</h3>${tag('예정','neutral')}</div><p>${esc(r.responsibility)}</p><p class="muted">요청: ${esc(r.provider)} · ${esc(r.model)} · ${esc(r.effort)}<br>실제 적용: 실행 전 · 미확인</p><code>${esc(r.path)}</code></div>`).join('');}
function pm(p){
 if(ui.scenario==='waiting')return `<div class="reading"><div class="pm-byline"><span class="pm-mark">A</span>Astra · PM</div><h2>계획을 작성 중입니다</h2><p class="body-copy">요청은 접수됐습니다. 계획 확정 전에는 개발이 시작되지 않습니다.</p><p class="muted">예시 요청 · 대기 중</p><div class="next-step">${button('보고 보기','tab','data-tab="report"')}${button('승인 보기','tab','data-tab="approval"')}</div>${composer(p)}</div>`;
 const question=p.phase==='question',empty=p.phase==='empty';
 const heading=question?data.pm.question:empty?'어떤 순간에 도움이 되면 좋을까요?':p.phase==='running'?'계획이 확정됐습니다':'개발과 검사를 두 역할로 나눕니다';
 const long=ui.scenario==='long'?'<p class="body-copy">진행 상황을 처음 보는 사람도 현재 무엇이 끝났고 누구의 판단이 필요한지 알 수 있도록 정리합니다. 함수의 입력은 Mapping[str, str]이고, 반환값은 active · waiting · blocked · done · unknown입니다. '+esc('알 수 없는 상태와 긴 프로젝트 이름이 있어도 원문·승인 범위·실행 식별값은 보존합니다. '.repeat(7))+'</p>':'';
 return `<article class="reading"><div class="pm-byline"><span class="pm-mark">A</span><strong>Astra</strong><span class="muted">PM · Ultra 요청</span></div><h2 class="pm-question">${heading}</h2><p class="body-copy">${question?esc(data.pm.body):empty?'이름과 자연어 목표로 대화를 시작하세요. 역할과 기술 설정은 PM이 제안합니다.':'개발과 검사는 같은 입력·출력 기준으로 진행합니다. 담당 업무와 범위를 확인해 주세요.'}</p>${long}${p.messages.map(m=>`<div class="conversation"><small>내 답변 · 예시</small><p>${esc(m.content)}</p></div>`).join('')}${question?button(esc(data.pm.suggested),'suggest','class="suggestion"'):''}${['proposal','spec_saved','plan_ready'].includes(p.phase)?`${rolePlan()}${technical(p)}<div class="next-step">${p.phase==='proposal'?`<p>역할과 범위가 맞으면 명세를 저장하세요.</p>${button('명세 저장','save-spec','class="primary"')}<small>저장 후에도 실행은 시작되지 않습니다.</small>`:p.phase==='spec_saved'?`<p>명세 버전 ${p.spec.version}을 저장했어요.</p>${button('새 계획 요청','request-plan','class="primary"')}<small>저장한 범위로 계획을 다시 작성합니다.</small>`:`<p>저장한 명세로 새 계획이 준비됐어요.</p>${button('계획 검토','review-plan','class="primary"')}<small>확정하면 이 계획과 명세 버전으로 예시 실행 한 건을 만듭니다.</small>`}</div>`:''}${p.phase==='running'?`<div class="result"><strong>예시 실행 1건</strong><p><code>${esc(p.runs.at(-1).id)}</code></p><p>실제 모델 호출이나 작업은 시작하지 않았습니다.</p></div>${button('진행 보기','tab','data-tab="team"')}`:composer(p)}<details class="technical"><summary>대화 정보</summary><p>요청 모델 ${esc(data.pm.model)} · ${data.pm.effort}<br>실제 적용 설정: 미확인 · 예시 응답<br>프로젝트: <code>${esc(p.id)}</code></p></details></article>`;
}
function composer(p){return `<form id="lab-message-form" class="composer"><label for="lab-message">PM에게 답하기</label><textarea id="lab-message" data-draft="message:${esc(p.id)}" maxlength="8000" placeholder="원하는 방식을 편하게 적어 주세요.">${esc(draft('message:'+p.id))}</textarea><div class="row"><small>예시 대화 · 실제 호출 없음</small><button type="submit" class="primary">보내기</button></div></form>`;}
function aside(p){if(p.id!=='fixture-pilot'||p.runs.length)return `<aside class="aside"><section><h3>팀</h3><p class="muted">${p.runs.length?'계획의 역할 2개 · 실제 실행 전':'계획 확정 전 · 실행 없음'}</p>${button('진행 보기 →','tab','data-tab="team" class="quiet plain-link"')}</section><section><h3>결정</h3><p class="muted">${p.id==='fixture-pilot'?'이전 후보의 검토 요청 1건':'이 프로젝트의 요청 없음'}</p>${p.id==='fixture-pilot'?button('이전 후보 보기 →','tab','data-tab="approval" class="quiet plain-link"'):''}</section></aside>`;return `<aside class="aside"><section><div class="row"><h3>팀</h3><small>이전 실행</small></div>${data.roles.map(r=>`<div class="role-mini"><div class="row"><strong>${r.name}</strong>${tag(r.status,r.wait?'wait':'')}</div><p class="muted">${esc(r.task)}</p></div>`).join('')}${button('진행 보기 →','tab','data-tab="team" class="quiet plain-link"')}</section><section><div class="row"><h3>결정</h3>${tag('1건','neutral')}</div><p class="muted">이전 후보가 검토를 기다려요.</p>${button('승인 보기 →','tab','data-tab="approval" class="quiet plain-link"')}</section></aside>`;}
function team(p){const run=p.runs.at(-1);if(!run&&p.id!=='fixture-pilot')return `<div class="empty"><h2>아직 시작하지 않았어요</h2><p>PM과 역할을 정하고 계획을 확정하면 이 프로젝트의 진행을 보여줍니다.</p>${button('PM과 대화','tab','data-tab="pm"')}</div>`;return `<section><div class="row board-head"><div><h2>팀</h2><p class="muted">${run?'방금 확정한 계획 · 실행 대기':'이전 예시 실행 · 진행 1 · 대기 1'}</p></div>${tag(run?'예정된 작업':'예시 실행','neutral')}</div>${run?`<div class="notice-bar">${esc(run.id)} · 명세 ${run.execution_spec.version} 고정. 아래 역할은 계획에 포함됐으며 실제 작업은 시작되지 않았습니다.</div>`:''}${data.roles.map(r=>`<div class="role-lane"><div class="row"><h3>${r.name}</h3>${tag(run?'예정':r.status,!run&&r.wait?'wait':'neutral')}</div><div><h3 class="role-task">${esc(run?r.responsibility:r.task)}</h3><p class="muted">${esc(r.responsibility)}</p>${!run&&r.wait?`<p>${esc(r.wait)}</p><p class="muted">${esc(r.resume)}</p>`:''}<p class="model muted">요청: ${esc(r.provider)} · ${esc(r.model)} · ${esc(r.effort)}<br>실제 적용: ${run?'실행 전':'미확인'}</p></div><div>${button('담당 범위','role',`data-role="${r.id}"`)}<p class="muted">${!run&&r.wait?'이관 후보: 미확인':'독립 작업'}</p></div></div>`).join('')}${run?'<div class="handoff"><p class="muted">전달물은 실제 작업이 시작된 뒤 표시됩니다.</p></div>':`<div class="handoff"><div class="handoff-route">개발 <span aria-hidden="true">→</span> 검사</div><div><div class="row"><h3>${data.transfer.title}</h3>${tag('수신','neutral')}</div><p>${esc(data.transfer.summary)}</p>${button('전달물 보기','artifact')}<small> ${data.transfer.time} · ${short(data.transfer.sha)}</small></div></div>`}<div class="board-bottom"><section><small>PM의 질문</small><h3>${data.pm.question}</h3>${button('답하기','tab','data-tab="pm"')}</section><section><small>별도 후보</small><h3>${p.id==='fixture-pilot'?data.approval.title:'검토 요청 없음'}</h3>${button('승인 보기','tab','data-tab="approval"')}</section></div></section>`;}
function approval(p){if(p.id!==data.approval.project_id)return `<div class="empty"><h2>요청이 없어요</h2><p>이 프로젝트의 승인 요청이 생기면 표시합니다.</p></div>`;const a=data.approval,choice=model.state.decisions.find(d=>d.approval_id===a.id);return `<article class="reading"><div class="approval-meta">${tag('검토 대기','wait')}<span class="muted">이전 후보 · ${a.run_id}</span></div><h2>${a.title}</h2><dl class="facts"><div><dt>대상</dt><dd>${esc(a.action)}<br><code>${a.artifact_sha}</code></dd></div><div><dt>영향</dt><dd>${esc(a.impact)}</dd></div><div><dt>비용</dt><dd>${esc(a.cost)}</dd></div><div><dt>복구</dt><dd>${esc(a.rollback)}</dd></div></dl><h3>검수 근거 <small>모두 예시</small></h3><ul class="evidence-list">${a.evidence.map(s=>`<li><span aria-label="통과">✓</span>${esc(s)}</li>`).join('')}</ul><section class="document"><small>${ui.scenario==='translation'?'읽기용 번역 대기':'한국어 · 읽기용 번역'}</small><p>${ui.scenario==='translation'?'번역이 아직 준비되지 않았습니다. 원문으로 검토하거나 다른 업무를 계속할 수 있습니다.':esc(a.translated)}</p><details><summary>원문과 대상</summary><p lang="en">${esc(a.original)}</p><p class="muted">승인은 번역이 아닌 원문 대상에 연결됩니다.</p><code>대상 ${a.subject_digest}</code><br><code>원문 ${a.source_digest}</code><br><code>${a.project_id} / ${a.run_id}</code></details></section>${choice?`<div class="result"><strong>예시 선택: ${choice.decision==='approve'?'수용':'수정 요청'}</strong><p>미리보기에서만 기록했습니다. 원본 승인 상태는 pending이며 운영 요청은 전송하지 않았습니다.</p></div>`:`<div class="decision-buttons">${button('후보 수용','review-decision','class="primary" data-decision="approve"')}${button('수정 요청','review-decision','data-decision="reject"')}</div><p class="form-help">다음 화면에서 대상과 영향을 다시 확인합니다.</p>`}</article>`;}
function report(p){if(p.id!=='fixture-pilot'||p.runs.length)return `<article class="reading"><h2>보고</h2><div class="report-block"><small>시스템 집계 · 예시</small><h3>${p.runs.length?'계획 확정, 실제 실행 전':'계획 준비 중'}</h3><p>이 프로젝트에 생성한 예시 실행 ${p.runs.length}건입니다. 실제 작업 결과와 PM 보고는 아직 없습니다.</p></div>${button('매니저로','tab','data-tab="pm"')}</article>`;return `<article class="reading"><h2>보고</h2><div class="report-block"><small>시스템 집계 · 이전 예시 실행 fixture-run-02</small><h3>초안 전달 완료, 검사는 대기</h3><p>${esc(data.report.system)}</p></div><div class="report-block"><small>PM 작성 · 이전 실행에 대한 예시 응답</small><h3>다음 행동</h3><p>${esc(data.report.pm)}</p>${button('PM에게 답하기','tab','data-tab="pm"')}</div><div class="report-block"><h3>내 결정</h3><p>새 계획의 확정과 이전 후보의 수용은 서로 다른 결정입니다.</p>${button('이전 후보 보기','tab','data-tab="approval"')}</div></article>`;}
function projects(){const list=ui.scenario==='empty'?[]:model.state.projects;return `<div class="page-top"><h1>프로젝트</h1>${button('새 프로젝트','new','class="primary"')}</div><label for="lab-search">찾기</label><input id="lab-search" class="search" type="search" data-draft="search" value="${esc(draft('search'))}" placeholder="이름으로 찾기"><div class="project-list" id="lab-project-list">${projectRows(list,draft('search'))}</div>`;}
function projectRows(list,query){const rows=list.filter(p=>p.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));return rows.length?rows.map(p=>`<button type="button" class="project-item" data-action="project" data-project="${esc(p.id)}"><div><strong>${esc(p.name)}</strong><p>${esc(p.goal)}</p></div><span>${esc(next(p))}</span><time class="muted">${esc(p.changed)}</time></button>`).join(''):`<div class="empty"><h2>${query?'일치하는 프로젝트가 없어요':'첫 프로젝트를 시작하세요'}</h2><p>${query?'검색어를 바꾸거나 새 프로젝트를 만들 수 있습니다.':'이름과 하고 싶은 일을 적으면 PM과 대화를 시작합니다.'}</p>${button('새 프로젝트','new')}</div>`;}
function workspace(){const p=current();if(!p||ui.scenario==='missing')return `<div class="empty"><h1>프로젝트가 없어요</h1><p>링크가 잘못됐거나 접근할 수 없는 프로젝트입니다. 기존 프로젝트를 덮어쓰지 않습니다.</p>${button('프로젝트로','projects','class="primary"')}</div>`;const title=ui.scenario==='long'?p.name+' · 처음 쓰는 사람도 이해할 수 있는 역할별 작업 상태 집계와 독립 검사':p.name;
 let body=ui.tab==='pm'?pm(p):ui.tab==='team'?team(p):ui.tab==='approval'?approval(p):report(p);
 if(ui.concept==='a')body=`${tabs()}<div class="workspace">${body}${aside(p)}</div>`;
 else if(ui.concept==='b')body=`${tabs()}${body}`;
 else body=`<div class="inbox"><nav class="inbox-list" aria-label="요청 목록">${[['pm','매니저',next(p)],['approval',p.id==='fixture-pilot'?'후보 검토':'승인',p.id==='fixture-pilot'?'이전 실행 · 결정 필요':'요청 없음'],['team',p.runs.length?'실행 준비':p.id==='fixture-pilot'?'검사 대기':'진행',p.runs.length?'확정한 역할 · 실제 실행 전':p.id==='fixture-pilot'?'공유 한도 · 예약 재개':'아직 시작하지 않음'],['report','보고','완료와 다음 행동']].map(([id,name,sub])=>button(`<strong>${name}</strong><span class="muted">${sub}</span>`,'tab',`data-tab="${id}" class="${ui.tab===id?'selected':''}"`)).join('')}</nav>${body}</div>`;
 return `<div class="crumb">${button('프로젝트','projects','class="quiet"')} <span aria-hidden="true">/</span> <span>작업실</span></div><div class="page-top"><h1>${esc(title)}</h1>${tag('예시','neutral')}</div>${body}`;
}
function render(focusId){const active=document.activeElement,restore=focusId||active?.id,selection=active?.selectionStart;root.dataset.theme=ui.theme;root.dataset.concept=ui.concept;root.querySelectorAll('[data-concept]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.concept===ui.concept)));document.querySelector('#lab-scenario').value=ui.scenario;let banner='';if(['offline','readonly','error'].includes(ui.scenario))banner=`<div class="notice-bar">${{offline:'연결이 끊겼어요. 입력은 이 탭에 보관합니다.',readonly:'읽기 권한입니다. 저장과 확정은 할 수 없습니다.',error:'저장 후 응답이 유실되는 예시입니다. 같은 요청을 다시 보내 결과를 확인하세요.'}[ui.scenario]}</div>`;if(ui.pending)banner+=`<div class="notice-bar"><strong>저장 결과 확인 필요</strong><p>입력을 바꿨어도 처음 보낸 요청의 결과를 먼저 확인합니다.</p><details><summary>처음 보낸 내용</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(JSON.stringify(ui.pending.payload,null,2))}</pre></details>${button('저장 결과 확인','recover')}</div>`;stage.innerHTML=`<div class="shell">${rail()}<main class="app-main" id="lab-main" tabindex="-1">${banner}${ui.view==='projects'?projects():workspace()}</main></div>`;persist();if(restore){const el=document.getElementById(restore);if(el){el.focus({preventScroll:true});if(typeof selection==='number'&&el.setSelectionRange)try{el.setSelectionRange(selection,selection);}catch{}}}}
function modal(html){lastFocus=document.activeElement;dialog.innerHTML=`<div class="dialog-heading"><h2 id="lab-dialog-title">${html.title}</h2>${button('닫기','close','aria-label="창 닫기"')}</div>${html.body}`;dialog.showModal();}
function close(){dialog.close();if(lastFocus?.isConnected)lastFocus.focus();else document.querySelector('#lab-main')?.focus();}
function errorMessage(error){const target=dialog.open?dialog.querySelector('.inline-error'):null;if(target)target.textContent=error.message;else announce(error.message);}
async function runRequest(kind,projectId,payload,recovery=false){
 if(busy)return;
 if(ui.pending&&!recovery){announce('처음 보낸 요청의 저장 결과를 먼저 확인하세요.');return;}
 const request=recovery?ui.pending:{kind,projectId,payload,key:'fixture-'+crypto.randomUUID()};
 if(!request)return;
 ui.pending=request;persist();busy=true;
 root.querySelectorAll('button[type=submit]').forEach(el=>el.disabled=true);
 try {
  const {kind:k,projectId:id,payload:v,key:requestKey}=request;
  const result=await ({create:()=>model.createProject(v.name,v.goal,requestKey,context()),message:()=>model.message(id,v.content,requestKey,context()),spec:()=>model.saveSpec(id,requestKey,context()),plan:()=>model.requestPlan(id,requestKey,context()),confirm:()=>model.confirm(id,{...v,idempotency_key:requestKey},context()),decision:()=>model.decide(id,{...v,idempotency_key:requestKey},context())}[k])();
  ui.pending=null;
  if(k==='create'){
   ui.project=result.project_id;ui.view='workspace';ui.tab='pm';
   if(draft('new-name')===v.name)ui.drafts['new-name']='';
   if(draft('new-goal')===v.goal)ui.drafts['new-goal']='';
  }
  if(k==='message'&&draft('message:'+id)===v.content)ui.drafts['message:'+id]='';
  if(dialog.open)close();render('lab-main');
  announce({create:'예시 프로젝트에서 PM 제안을 확인하세요.',message:'예시 PM 제안이 준비됐습니다.',spec:'명세를 저장했습니다. 실행은 0건입니다.',plan:'새 계획이 준비됐습니다. 직접 확인하고 확정하세요.',confirm:'이 계획에 예시 실행 한 건을 연결했습니다.',decision:'예시 선택을 기록했습니다. 운영 승인은 변경하지 않았습니다.'}[k]);
 }catch(error){
  if(!recovery&&error.code!=='result_unknown')ui.pending=null;
  persist();
  if(dialog.open){errorMessage(error);if(ui.pending&&!dialog.querySelector('[data-action=recover]'))dialog.querySelector('.inline-error').insertAdjacentHTML('afterend',button('저장 결과 확인','recover'));}
  else {render();errorMessage(error);}
 }finally{busy=false;root.querySelectorAll('button[type=submit]').forEach(el=>el.disabled=false);}
}
root.addEventListener('input',event=>{const el=event.target;if(el.dataset.draft){ui.drafts[el.dataset.draft]=el.value;persist();}if(el.id==='lab-search'){document.querySelector('#lab-project-list').innerHTML=projectRows(ui.scenario==='empty'?[]:model.state.projects,el.value);}});
root.addEventListener('change',event=>{if(event.target.id==='lab-scenario'){ui.scenario=event.target.value;render();}});
root.addEventListener('click',event=>{const el=event.target.closest('button');if(!el)return;if(el.dataset.concept){ui.concept=el.dataset.concept;ui.tab=ui.concept==='a'?'pm':ui.concept==='b'?'team':'approval';render();return;}const action=el.dataset.action,p=current();
 if(action==='recover'){runRequest(null,null,null,true);return;}
 if(action==='theme'){ui.theme=ui.theme==='light'?'black':'light';render('lab-theme');}
 if(action==='projects'){ui.view='projects';render('lab-main');}
 if(action==='workspace'){ui.view='workspace';render('lab-main');}
 if(action==='project'){ui.project=el.dataset.project;ui.view='workspace';ui.tab=ui.concept==='b'?'team':ui.concept==='c'?'approval':'pm';render('lab-main');}
 if(action==='tab'){ui.tab=el.dataset.tab;render('lab-main');}
 if(action==='refresh'){render();announce('화면을 갱신했습니다. 작성 중인 내용은 보관했습니다.');}
 if(action==='reset'){resetting=true;try{sessionStorage.removeItem(KEY);}catch{}location.reload();}
 if(action==='close'){close();}
 if(action==='suggest'){ui.drafts['message:'+p.id]=data.pm.suggested;render('lab-message');}
 if(action==='new'){modal({title:'새 프로젝트',body:`<form id="lab-new-form"><div><label for="lab-new-name">이름</label><input id="lab-new-name" data-draft="new-name" maxlength="120" required value="${esc(draft('new-name'))}" placeholder="예: 역할 상태 확인"></div><div><label for="lab-new-goal">목표</label><textarea id="lab-new-goal" data-draft="new-goal" maxlength="8000" required placeholder="무엇을 만들고 싶은가요?">${esc(draft('new-goal'))}</textarea></div><p class="form-help">PM이 역할과 기술 설정을 제안합니다. 이 화면은 예시이며 실제 프로젝트를 생성하지 않습니다.</p><p class="inline-error" role="alert"></p><button type="submit" class="primary">PM과 시작</button></form>`});}
 if(action==='save-spec')runRequest('spec',p.id,{});
 if(action==='request-plan')runRequest('plan',p.id,{});
 if(action==='review-plan'){const plan=p.plan;modal({title:'계획',body:`<p>예시 계획 · 명세 버전 ${p.spec.version}</p>${rolePlan()}<p>완료 조건: 빈 입력·모든 분류·알 수 없는 상태·입력 불변, 같은 후보의 격리 검사·원격 CI·독립 검수·Astra 최종 검수.</p><details class="technical"><summary>원문과 고정 대상</summary><p>${esc(plan.content.summary)}</p><code>계획 ${plan.digest}</code><br><code>명세 ${p.spec.digest}</code><br><code>${p.id} / ${plan.id}</code></details><form id="lab-confirm-form" data-plan="${plan.id}" data-digest="${plan.digest}" data-spec="${p.spec.digest}"><label class="check-label"><input type="checkbox" id="lab-confirm-reviewed" required>역할·완료 조건·두 파일의 실행 범위를 확인했습니다.</label><p class="form-help">확정 시 예시 실행 한 건을 만듭니다. 후보 수용·운영 배포·병합 승인은 포함하지 않습니다.</p><p class="inline-error" role="alert"></p><button type="submit" class="primary">계획 확정</button></form>`});}
 if(action==='role'){const r=data.roles.find(r=>r.id===el.dataset.role);modal({title:r.name,body:`<dl class="facts"><div><dt>책임</dt><dd>${esc(r.responsibility)}</dd></div><div><dt>파일</dt><dd><code>${esc(r.path)}</code></dd></div><div><dt>모델</dt><dd>요청 ${r.provider} · ${r.model} · ${r.effort}<br>실제 적용 미확인</dd></div></dl><p>이관 후보의 적격성은 이 예시에서 검증하지 않았습니다.</p>`});}
 if(action==='artifact'){modal({title:data.transfer.title,body:`<p>${esc(data.transfer.summary)}</p><dl class="facts"><div><dt>연결</dt><dd>개발 → 검사 · 수신 완료</dd></div><div><dt>실행</dt><dd><code>${data.transfer.run}</code></dd></div><div><dt>파일</dt><dd><code>${data.transfer.path}</code></dd></div><div><dt>커밋</dt><dd><code>${data.transfer.sha}</code></dd></div></dl><p class="form-help">실제 전달 형식을 설명하는 예시 기록입니다. 운영 산출물이 아닙니다.</p>`});}
 if(action==='review-decision'){const a=data.approval,decision=el.dataset.decision;modal({title:decision==='approve'?'후보 수용':'수정 요청',body:`<p>${esc(a.impact)}</p><p class="muted">${a.run_id} · ${short(a.artifact_sha)}</p><form id="lab-decision-form" data-decision="${decision}"><label class="check-label"><input type="checkbox" id="lab-decision-reviewed" required>원문 대상과 영향·비용·복구를 확인했습니다.</label><div><label for="lab-decision-comment">${decision==='reject'?'수정 이유':'메모 (선택)'}</label><textarea id="lab-decision-comment" data-draft="decision-comment" ${decision==='reject'?'required':''}>${esc(draft('decision-comment'))}</textarea></div><p class="form-help">예시 선택만 기록합니다. 기존 승인과 PR #10은 변경하지 않습니다.</p><p class="inline-error" role="alert"></p><button type="submit" class="primary">${decision==='approve'?'수용 선택':'수정 요청 선택'}</button></form>`});}
});
root.addEventListener('submit',event=>{event.preventDefault();const form=event.target,p=current();
 if(form.id==='lab-new-form')runRequest('create','new',{name:draft('new-name'),goal:draft('new-goal')});
 if(form.id==='lab-message-form')runRequest('message',p.id,{content:draft('message:'+p.id)});
 if(form.id==='lab-confirm-form')runRequest('confirm',p.id,{plan_id:form.dataset.plan,plan_digest:form.dataset.digest,execution_spec_digest:form.dataset.spec,reviewed:document.querySelector('#lab-confirm-reviewed').checked});
 if(form.id==='lab-decision-form'){const a=data.approval;runRequest('decision',p.id,{approval_id:a.id,subject_digest:a.subject_digest,artifact_sha:a.artifact_sha,decision:form.dataset.decision,comment:draft('decision-comment'),reviewed:document.querySelector('#lab-decision-reviewed').checked});}
});
// Browser reload restores the draft, selection and focused field without re-sending anything.
window.addEventListener('pagehide',()=>{ui.focus=document.activeElement?.id;ui.selection=document.activeElement?.selectionStart;persist();});
render(ui.focus);if(ui.focus&&typeof ui.selection==='number'){try{document.getElementById(ui.focus)?.setSelectionRange(ui.selection,ui.selection);}catch{}}
})();
