import {createDocumentUI} from './documents-ui.js';
import {createCollaborationUI} from './collaboration-ui.js';
import {createManagerUI,managerSnapshot,workspaceIcon} from './manager-ui.js';
const $ = (selector, parent = document) => parent.querySelector(selector);
const app = $('#app');
const dialog = $('#dialog');
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const esc = escapeHTML;
const paths = {manager:['01','매니저'],progress:['02','진행'],approvals:['03','승인'],project:['04','프로젝트']};
const views = {...paths,reports:['02','보고서']};
const labels = {PASS:'통과 의견',REVISE:'수정 의견',PLAN_READY:'계획 제안 완료',CONTRIBUTION_READY:'역할 산출물 준비',WAITING_ROLE_REPAIR:'담당 역할 수정 대기',WAITING_DEPENDENCIES:'선행 산출물 대기',fixture_complete:'모의 자동 흐름 완료',PLAN_CONFIRMED:'계획 확정',plan_proposed:'계획 제안 완료',preparing:'작업 준비',waiting:'예약 대기',awaiting_approval:'승인 대기',proposed:'계획 제안',confirmed:'계획 확정',stale:'이전 요청',completed:'처리 완료',running:'처리 중',blocked:'차단',waiting_quota:'사용량 대기',waiting_retry:'재시도 대기',waiting_capacity:'후보 복귀 대기',IDLE:'배정 대기',MERGE_READY:'검수 통과',expired:'만료',developer:'개발',reviewer:'독립 검수',final_reviewer:'최종 검수',PLANNING:'계획 중',active:'활성',draft:'초안',superseded:'이전 버전',awaiting_worker:'실행기 연결 대기',READY:'준비',RUNNING:'진행 중',ACTIVE:'진행 중',PENDING:'검토 대기',pending:'검토 대기',DRAFT:'초안',WAITING_QUOTA:'사용량 대기',WAITING_CAPACITY:'후보 복귀 대기',WAITING_RETRY:'재시도 대기',WAITING_DEPENDENCY:'산출물 대기',WAITING_APPROVAL:'승인 대기',WAITING_PM:'PM 대기',RECONCILIATION_REQUIRED:'상태 대조 필요',BLOCK:'차단',BLOCKED:'차단',COMPLETE:'완료',COMPLETED:'완료',DONE:'완료',DEMO_READY:'모의 검증 완료',approved:'승인 기록됨',rejected:'반려됨',changes_requested:'수정 요청됨',request_changes:'수정 요청됨',EXPIRED:'만료',awaiting_pm:'PM 응답 대기',queued:'예약됨',unverified:'미검증',fixture:'모의 예시',live:'실제 연결'};
const state = {authenticated:false,loginMethod:'password',passwordChangeRequired:false,changingPassword:false,username:'',csrf:'',projects:[],projectId:new URLSearchParams(location.hash.split('?')[1]||'').get('project')||'',overview:null,view:readView(),connected:navigator.onLine,updatedAt:null,error:'',loading:true,refreshing:false,drafts:{},demo:false};
let lastPayload = '';
let toastTimer;
let requestEpoch = 0;
const busyForms = new Set();
const draftBases = {};
const documentUI=createDocumentUI({esc,readable,stamp,getOverview:()=>state.overview});
const collaborationUI=createCollaborationUI({esc,badge,stamp,readable,evidenceLinks,label,documents:documentUI});
const openDetails=new Map();
const managerUI=createManagerUI({esc,badge,label,stamp,documents:documentUI,planContent});

function readView(){const name = location.hash.slice(1).split('?')[0];return Object.hasOwn(views,name) ? name : 'manager';}
function label(status){return labels[status] || status || '미배정';}
function badge(status){const s=String(status||'');const kind=/WAIT|waiting|PENDING|pending|awaiting|EXPIRED/.test(s)?'waiting':/BLOCK|blocked|RECONCIL|rejected/.test(s)?'blocked':/RUNNING|running|ACTIVE/.test(s)?'running':/COMPLETE|completed|confirmed|DONE|approved/.test(s)?'complete':'';return `<span class="badge ${kind}">${esc(label(status))}</span>`;}
function stamp(value){if(!value)return '미정';const date=new Date(typeof value==='number'?value*1000:value);return Number.isNaN(date.getTime())?'미정':date.toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});}
function readable(value){if(value===null||value===undefined||value==='')return '미확인';if(typeof value==='object')return JSON.stringify(value,null,2);return String(value);}
function safeURL(value){if(typeof value!=='string'||!value.trim())return null;try{const url=new URL(value,location.origin);return ['https:','http:'].includes(url.protocol)?esc(url.href):null;}catch{return null;}}
function evidenceLinks(items=[]){return items.map(item=>{const url=safeURL(item.url);return url?`<a href="${url}" target="_blank" rel="noopener noreferrer">${esc(item.label||'증거 보기')} ↗</a>`:`<span class="muted small">${esc(item.label||'증거')} · 링크 미확인</span>`;}).join('');}
function notify(message){$('#announcer').textContent=message;const node=$('#toast');node.textContent=message;node.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.hidden=true,4500);}
function empty(title,description,action=''){return `<div class="empty"><div class="empty-mark" aria-hidden="true">·</div><h2>${esc(title)}</h2><p>${esc(description)}</p>${action}</div>`;}
function draftKey(name){return `${state.projectId}:${name}`;}
function draft(name,fallback=''){return state.drafts[draftKey(name)] ?? fallback;}

async function api(path,{method='GET',body}={}){
  if(body&&new TextEncoder().encode(JSON.stringify(body)).length>65536)throw new Error('입력 내용이 서버 제한을 초과했습니다. 내용을 줄여 다시 저장해주세요.');
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);
  try{
    const response=await fetch(path,{method,credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{Accept:'application/json',...(body?{'Content-Type':'application/json'}:{}),...(method!=='GET'&&state.csrf?{'X-CSRF-Token':state.csrf}:{})},...(body?{body:JSON.stringify(body)}:{})});
    let data;try{data=await response.json();}catch{throw new Error('서버 응답을 읽을 수 없습니다. 다시 연결해주세요.');}
    if(!response.ok){if(response.status===401&&state.authenticated){state.authenticated=false;state.csrf='';state.overview=null;state.projects=[];state.drafts={};collaborationUI.reset();documentUI.clear();openDetails.clear();for(const key of Object.keys(draftBases))delete draftBases[key];dialog.close();render();}const friendly={unauthorized:'아이디·비밀번호가 올바르지 않거나 로그인이 만료되었습니다.',incorrect_password:'현재 비밀번호가 올바르지 않습니다.',weak_password:'새 비밀번호는 10~128자로 입력해주세요.',password_reused:'현재 비밀번호와 다른 비밀번호를 정해주세요.',password_change_required:'먼저 임시 비밀번호를 변경해주세요.',rate_limited:'로그인 시도가 많습니다. 잠시 뒤 다시 시도해주세요.',translation_mismatch:'표시한 번역과 승인 원문의 연결이 달라졌습니다. 최신 원문과 번역을 다시 확인해주세요.',subject_mismatch:'승인 대상이 변경되었습니다. 최신 실행안을 다시 확인해주세요.',already_decided:'이미 결정된 승인입니다. 최신 상태를 확인해주세요.',expired:'승인 유효 기한이 지났습니다. 새 실행안이 필요합니다.',stale_plan:'목표 또는 하네스가 변경되었습니다. 최신 계획을 다시 검토해주세요.',plan_mismatch:'검토한 계획 내용이 변경되었습니다. 최신 계획을 다시 검토해주세요.',already_confirmed:'이미 확정된 계획입니다. 최신 실행 상태를 확인해주세요.',idempotency_conflict:'저장 요청 식별값이 충돌했습니다. 최신 상태를 확인해주세요.',fixture_only:'모의 예시 계획은 실행할 수 없습니다.',stale_harness:'하네스 기준 버전이 변경되었습니다. 최신 버전을 확인해주세요.',body_too_large:'입력 내용이 너무 깁니다. 내용을 줄여 다시 저장해주세요.',csrf:'로그인 상태 확인이 필요합니다. 다시 로그인해주세요.'};const error=new Error(friendly[data.error?.code]||data.error?.message||`요청 실패 (${response.status})`);error.code=data.error?.code;throw error;}
    state.connected=true;return data;
  }catch(error){if(error.name==='AbortError'||error instanceof TypeError){state.connected=false;throw new Error('서버에 연결할 수 없습니다. 연결을 복구한 뒤 다시 시도해주세요.');}throw error;}
  finally{clearTimeout(timer);}
}

function themeControls(){return `<div class="theme-control" role="group" aria-label="화면 테마">${[['light','Light'],['black','Black']].map(([value,title])=>`<button type="button" data-theme-choice="${value}" aria-pressed="${document.documentElement.dataset.theme===value}">${title}</button>`).join('')}</div>`;}

function accountMenu(){return `<details class="workspace-account-menu" data-persist-key="account-menu"><summary aria-label="계정 메뉴">${workspaceIcon('account')}</summary><div>${state.loginMethod==='password'?'<button type="button" data-action="change-password">비밀번호 변경</button>':''}<button type="button" data-action="logout">로그아웃</button></div></details>`;}
function authScreen(){
  const changing=state.authenticated&&(state.passwordChangeRequired||state.changingPassword);
  const passwordFields=`<div class="form-row"><label for="username">아이디</label><input id="username" name="username" autocomplete="username" value="edward" required maxlength="32"></div><div class="form-row"><label for="password">비밀번호</label><input type="password" id="password" name="password" autocomplete="current-password" required maxlength="128" placeholder="비밀번호 입력"></div>`;
  const changeFields=`<input type="text" name="username" autocomplete="username" value="${esc(state.username)}" hidden><div class="form-row"><label for="current-password">현재 비밀번호</label><input type="password" id="current-password" name="current_password" autocomplete="current-password" required maxlength="128"></div><div class="form-row"><label for="new-password">새 비밀번호</label><input type="password" id="new-password" name="new_password" autocomplete="new-password" required minlength="10" maxlength="128"><small>10자 이상</small></div><div class="form-row"><label for="confirm-password">새 비밀번호 확인</label><input type="password" id="confirm-password" name="confirm_password" autocomplete="new-password" required minlength="10" maxlength="128"></div>`;
  const legacyFields=`<div class="form-row"><label for="access-token">접근 토큰</label><input type="password" id="access-token" name="token" autocomplete="current-password" required></div>`;
  return `<div class="auth-shell"><header class="auth-topbar"><div class="auth-wordmark"><h1>AI Company</h1><span>Aigent workspace</span></div>${themeControls()}</header><main class="auth-form" id="main"><div class="auth-panel-caption">Aigent workspace</div><div class="auth-panel-body"><div class="auth-heading"><h2>${changing?'비밀번호 변경':'로그인'}</h2>${changing?`<p>${state.passwordChangeRequired?'임시 비밀번호를 새 비밀번호로 변경해주세요.':'저장하면 다른 기기에서 로그아웃됩니다.'}</p>`:''}</div><form id="${changing?'password-form':'login-form'}" aria-label="${changing?'비밀번호 변경':'로그인'}">${changing?changeFields:state.loginMethod==='password'?passwordFields:legacyFields}<p class="error-text" role="alert">${esc(state.error)}</p><button class="primary" type="submit">${changing?'비밀번호 변경 후 계속':'로그인'}</button></form>${changing?`<button class="quiet auth-back" data-action="${state.passwordChangeRequired?'logout':'cancel-password'}">${state.passwordChangeRequired?'로그아웃':'취소'}</button>`:''}</div></main><footer class="auth-footer">hyungwon.cloud</footer></div>`;
}
function acceptSession(result){state.authenticated=Boolean(result.authenticated);state.csrf=result.csrf_token||'';state.passwordChangeRequired=Boolean(result.password_change_required);state.username=result.username||'';state.changingPassword=false;}

function shell(){const pending=(state.overview?.approvals||[]).filter(isPending).length;return `<div class="shell"><aside class="sidebar"><div class="workspace-brand"><div class="brand">AI Company</div><div class="workspace-caption">Aigent workspace</div></div><div><nav class="nav" aria-label="주요 화면">${Object.entries(paths).map(([name,[number,title]])=>`<a href="#${name}?project=${esc(state.projectId)}" aria-label="${title}" ${(state.view===name||(name==='progress'&&state.view==='reports'))?'aria-current="page"':''}><span class="nav-icon">${workspaceIcon(name)}</span><span>${title}</span>${name==='approvals'&&pending?`<span class="nav-count">${pending}</span>`:''}</a>`).join('')}</nav></div><div class="sidebar-bottom"><div class="account"><div class="avatar" aria-hidden="true">${esc((state.username||'M').slice(0,1).toUpperCase())}</div><div><strong>${esc(state.username||'마스터')}</strong><span>마스터</span></div></div><button class="quiet logout" data-action="logout">로그아웃 ↗</button></div><button class="quiet mobile-logout" data-action="logout">로그아웃</button></aside><div class="workspace"><header class="topbar"><div class="project-picker"><label for="project-select">프로젝트</label><select id="project-select" aria-label="프로젝트 선택">${state.projects.length?state.projects.map(project=>`<option value="${esc(project.id)}" ${project.id===state.projectId?'selected':''}>${esc(project.name)}</option>`).join(''):'<option>프로젝트 없음</option>'}</select></div><div class="topbar-actions">${themeControls()}${accountMenu()}<div id="connection" class="connection">${connection()}</div></div></header><main class="main" id="main" tabindex="-1">${content()}</main></div></div>`;}
function connection(){return `<span class="dot ${state.connected?'':'offline'}" aria-hidden="true"></span>${state.connected?(state.updatedAt?`${stamp(state.updatedAt)} 동기화`:'서버 연결 중'):`연결 끊김${state.updatedAt?' · 마지막 '+stamp(state.updatedAt):''}`}`;}
function progressTabs(){return `<nav class="progress-tabs" aria-label="진행 보기"><a href="#progress?project=${esc(state.projectId)}" ${state.view==='progress'?'aria-current="page"':''}>협업 흐름</a><a href="#reports?project=${esc(state.projectId)}" ${state.view==='reports'?'aria-current="page"':''}>보고서</a></nav>`;}
function pageHeading(title,description,actions=''){return `<div class="page-heading"><div><div class="eyebrow">${esc(state.overview?.project.name||'AI COMPANY')} / ${esc(views[state.view][1])}</div><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${actions?`<div class="page-actions">${actions}</div>`:''}</div>`;}
function content(){
  const reconnect=state.error?`<div class="banner error" role="alert"><strong>동기화 확인 필요</strong><span>${esc(state.error)}${state.overview?' 마지막으로 받은 상태를 표시합니다.':''}</span><button data-action="refresh">다시 연결</button></div>`:'';
  if(state.loading&&!state.overview)return reconnect+pageHeading('작업 공간을 불러오는 중','서버에 저장된 프로젝트와 역할 상태를 확인합니다.')+'<div class="role-grid" aria-label="불러오는 중"><div class="skeleton"></div><div class="skeleton"></div></div>';
  if(!state.projects.length)return reconnect+pageHeading('프로젝트','프로젝트를 만들고 PM에게 목표와 완료 기준을 전달하세요.')+empty('아직 프로젝트가 없습니다','프로젝트와 대화는 서버에 저장됩니다. 실행은 합의된 하네스와 실제 작업 환경이 준비된 뒤 연결됩니다.','<button class="primary" data-action="create-project">프로젝트 만들기 +</button>');
  if(!state.overview)return reconnect+empty('프로젝트 상태를 불러오지 못했습니다','서버 연결을 확인한 뒤 다시 시도하세요.','<button data-action="refresh">다시 불러오기</button>');
  const fixture=state.overview.readiness?.mode==='fixture'?(state.view==='manager'?'<div class="manager-fixture"><strong>모의 예시 데이터</strong><span>실제 실행 아님</span></div>':'<div class="banner"><strong>모의 예시 데이터</strong><span>화면·상태 전이 확인용입니다. 실제 에이전트 실행이나 배포 완료를 뜻하지 않습니다.</span></div>'):'';
  const provenance=state.overview.readiness?.mode==='fixture'&&state.overview.readiness?.fixture_provenance?`<div class="banner neutral recorded-provenance" role="note">${esc(state.overview.readiness.fixture_provenance)}</div>`:'';
  return reconnect+fixture+provenance+({progress:progress,manager:manager,reports:reports,approvals:approvals,project:project}[state.view])();
}
function progress(){
  const {roles=[],tasks=[],approvals=[]}=state.overview;
  const running=roles.filter(role=>/RUNNING|running|ACTIVE/.test(role.status)).length;
  const waiting=roles.filter(role=>/WAIT|waiting/.test(role.status)).length;
  const completed=tasks.filter(task=>/^(COMPLETE|COMPLETED|DONE)$/.test(task.status)).length;
  const board=state.overview.collaboration?collaborationUI.render(state.overview,state.projectId):`<p class="small muted">협업 전달 기록 미연결 · 저장된 역할 요약을 표시합니다.</p>${roles.length?`<div class="role-grid">${roles.map((role,index)=>roleCard(role,index,tasks)).join('')}</div>`:empty('역할 배치를 기다리고 있습니다','매니저에게 필요한 역할과 책임을 전달하세요.')}`;
  return pageHeading('역할별 진행','각 역할의 현재 업무와 실제 전달 관계를 확인합니다.','<button data-action="refresh">새로고침 ↻</button><button class="primary" data-action="create-project">새 프로젝트 +</button>')+progressTabs()+`<div class="metrics" aria-label="프로젝트 상태 요약">${[[running,'진행 중인 역할','역할'],[waiting,'대기 중인 역할','역할'],[completed,'완료한 작업','작업'],[approvals.filter(isPending).length,'마스터 승인 대기','건']].map(([count,title,unit])=>`<div class="metric"><span class="metric-label">${title}</span><span class="metric-value">${count.toString().padStart(2,'0')}</span><span class="metric-unit">${unit}</span></div>`).join('')}</div>${board}${runList()}<p class="footer-note">요청 설정과 관측 근거를 구분합니다. 번역 대기는 독립 작업이나 기존 승인 처리를 막지 않습니다.</p>`;
}
function roleCard(role,index,tasks){
  const own=tasks.filter(task=>task.role_id===role.id);
  const current=tasks.find(task=>task.id===role.current_task_id)||own.find(task=>task.status==='RUNNING')||own.find(task=>/^WAITING_|RECONCILIATION_REQUIRED/.test(task.status));
  const next=tasks.find(task=>task.id===role.next_task_id)||own.find(task=>task.id!==current?.id&&/^(READY|QUEUED|WAITING_DEPENDENCY)$/.test(task.status));
  const taskName=id=>tasks.find(task=>task.id===id)?.title||id;
  const handoffs=role.handoffs||[];
  return `<article class="role"><header class="role-heading"><div class="role-top"><h3><span class="role-number">R${String(index+1).padStart(2,'0')}</span>${esc(role.name)}</h3>${badge(role.status)}</div><p>${esc(role.responsibility||'책임 범위 미정')}</p></header><div class="role-body"><div class="agent-row"><span class="agent-token" aria-hidden="true">${role.assigned_model?'AI':'—'}</span><div><strong>${esc(role.assigned_model||'담당 모델 미배정')}</strong><span class="mono">${role.session_id?`SESSION ${esc(role.session_id)}`:'세션 미시작'}</span></div></div><div class="task-row"><div class="eyebrow">현재 작업</div><div class="task-title">${esc(current?.title||'진행 중인 작업 없음')}</div>${current?`<div class="task-meta">${badge(current.status)}<span>${esc(label(current.stage)||'단계 미정')}</span></div>`:'<p>준비된 작업의 배정을 기다립니다.</p>'}${current?.dependencies?.length?`<p class="mt-8">필요한 결과 · ${esc(current.dependencies.map(taskName).join(', '))}</p>`:''}${current?.repair_reason?.length?`<div class="role-note">수정 요청 · ${esc(readable(current.repair_reason))}</div>`:''}${current?.worktree?`<p class="mono mt-8">${esc(current.worktree)}</p>`:''}</div><div class="task-row"><div class="eyebrow">다음 작업</div><p>${esc(next?.title||'등록된 다음 작업 없음')}</p>${next?.dependencies?.length?`<p>의존 작업 · ${esc(next.dependencies.map(taskName).join(', '))}</p>`:''}</div>${role.wait_reason||role.resume_at?`<div class="role-note">${esc(role.wait_reason||label(role.status))}${role.resume_at?`<br>재확인 예약 · ${stamp(role.resume_at)}`:''}</div>`:''}${handoffs.length?`<details><summary>담당자 이관 이력 ${handoffs.length}건</summary><div class="verification">${esc(handoffs.map(readable).join('\n'))}</div></details>`:''}</div><footer class="role-footer"><span>작업 ${own.length}개${handoffs.length?` · 이관 ${handoffs.length}회`:''}</span><span>${esc(role.evidence_state?label(role.evidence_state):'실행 증거 미확인')}</span></footer></article>`;
}
function listText(items){return Array.isArray(items)?items.map(readable).join(' · '):readable(items);}
function requestedPM(){
  const requested=state.overview.pm_requests?.at(-1)?.requested_configuration||state.overview.readiness?.pm_requested;
  return requested?`PM 요청 구성: ${esc(readable(requested))}`:'PM 구성 확인 중';
}
function pmRequests(){
  const requests=state.overview.pm_requests||[];
  if(!requests.length)return '';
  return `<section class="pm-status" aria-label="PM 요청 상태"><h3>PM 요청 처리</h3>${requests.slice(-3).map(request=>`<div class="request-row"><div class="task-meta">${badge(request.state)}<span>요청 ${esc(request.request_revision??'—')} · ${stamp(request.updated_at||request.created_at)}</span></div>${request.wait_reason?`<p>${esc(request.wait_reason)}</p>`:''}${request.resume_at?`<p>재확인 예약 · ${stamp(request.resume_at)}</p>`:''}${request.configuration_evidence?`<details><summary>서버가 기록한 PM 설정 근거</summary><div class="verification">${esc(readable(request.configuration_evidence))}</div></details>`:''}</div>`).join('')}<p class="small muted">PM 응답을 기다리는 동안에도 <a href="#reports">보고서</a>와 <a href="#approvals">승인</a>을 확인할 수 있습니다.</p></section>`;
}
function planContent(plan){
  const content=plan.content||{};
  return `<p class="report-summary">${esc(content.summary||'요약 미등록')}</p><div class="plan-roles">${(content.roles||[]).map(role=>`<section class="role-config"><h3>${esc(role.name||role.key)}</h3><p>${esc(role.responsibility)}</p><dl class="detail-grid"><div><dt>목표</dt><dd>${esc(role.goal)}</dd></div><div><dt>완료 기준</dt><dd>${esc(listText(role.acceptance))}</dd></div><div><dt>허용 경로</dt><dd class="mono">${esc(listText(role.allowed_paths))}</dd></div><div><dt>먼저 필요한 역할</dt><dd>${role.depends_on?.length?esc(listText(role.depends_on)):'없음 · 독립 진행'}</dd></div></dl></section>`).join('')}</div><div class="plan-completion"><strong>전체 완료 기준</strong><p>${esc(listText(content.completion_criteria))}</p></div>`;
}
function planList(excludeId){
  const plans=(state.overview.plans||[]).filter(plan=>plan.id!==excludeId);
  if(!plans.length)return '';
  return `<section class="plan-list" aria-label="PM 계획"><div class="section-line"><h2>검토할 계획</h2><span>확정한 범위에서 작업 생성</span></div>${plans.map(plan=>`<article class="panel plan" data-plan-id="${esc(plan.id)}"><div class="section-line"><h3>PM 계획 · 요청 ${esc(plan.request_revision??'—')}</h3><div>${badge(plan.status)} ${badge(plan.mode||'unverified')}</div></div>${planContent(plan)}<details><summary>계획 식별값과 설정 근거</summary><dl class="detail-grid mt-8"><div><dt>기준 하네스</dt><dd>버전 ${esc(plan.base_harness_version)}</dd></div><div><dt>계획 식별값</dt><dd class="mono">${esc(plan.digest)}</dd></div></dl><div class="verification">${esc(readable(plan.evidence||plan.configuration_evidence))}</div></details>${plan.status==='proposed'?`<div class="form-actions mt-20"><span class="hint">${state.overview.project.source==='fixture'?'모의 예시 · 실행 불가':'역할과 완료 기준을 확인한 뒤 확정하세요.'}</span><button class="primary" data-action="review-plan" data-id="${esc(plan.id)}" ${!state.connected||!plan.digest||state.overview.project.source==='fixture'?'disabled':''}>계획 검토·확정 →</button></div>`:''}</article>`).join('')}</section>`;
}
function delegationDetails(run){
  if(!run.delegation_id)return '';
  const record=state.overview.delegations?.find(item=>item.id===run.delegation_id&&item.run_id===run.id);
  const parent=state.overview.runs?.find(item=>item.id===run.parent_run_id);
  const authorization=record?.authorization||{};
  return `<section class="delegation-record"><p class="role-note"><strong>위임받은 검증 클라이언트</strong><br>실제 마스터의 화면 조작과 구분하여 기록합니다.</p>${run.parent_run_id?`<dl class="detail-grid mt-8"><div><dt>이전 실행</dt><dd class="mono">${esc(run.parent_run_id)}</dd></div><div><dt>이전 실행의 현재 기록</dt><dd>${parent?badge(parent.state):'이력 미확인'}</dd></div></dl>`:''}${record?`<details><summary>위임 원문과 승인 범위 확인</summary><p class="small muted mt-8">이 위임은 지정 계획의 새 검증에만 연결됩니다. 이전 차단 결과는 그대로 보존됩니다.</p><dl class="detail-grid"><div><dt>원문 수신 시각</dt><dd>${esc(readable(authorization.received_at))}</dd></div><div><dt>새 검증 허용</dt><dd>${authorization.max_new_validations===undefined?'미확인':`${esc(authorization.max_new_validations)}회`}</dd></div><div><dt>승인된 계획 해시</dt><dd class="mono">${esc(authorization.plan_digest||record.plan_digest||'미확인')}</dd></div><div><dt>허용 경로</dt><dd class="mono">${esc(listText(authorization.allowed_paths))}</dd></div><div><dt>승인 원문 식별값</dt><dd class="mono">${esc(record.authorization_digest||'미확인')}</dd></div><div><dt>위임 기록 식별값</dt><dd class="mono">${esc(record.digest||'미확인')}</dd></div></dl><div class="verification delegation-original">${esc(authorization.original_text||'원문 미확인')}</div></details>`:'<p class="small muted">이 실행에 연결된 위임 근거를 불러오지 못했습니다.</p>'}</section>`;
}
function runList(){
  const runs=state.overview.runs||[];
  if(!runs.length)return '';
  return `<section class="run-list" aria-label="자동 실행"><div class="section-line"><h2>자동 실행</h2><span>검사와 검수의 대상 확인</span></div>${runs.map(run=>`<article class="panel" data-run-id="${esc(run.id)}"><div class="section-line"><h3>실행 <span class="mono">${esc(run.id)}</span></h3><div>${badge(run.state)} ${badge(run.mode||'unverified')}</div></div><dl class="detail-grid"><div><dt>계획</dt><dd class="mono">${esc(run.plan_id)}</dd></div><div><dt>후보 커밋</dt><dd class="mono">${esc(run.integration?.candidate_sha||run.candidate_sha||'아직 기록되지 않음')}</dd></div><div><dt>하네스 버전</dt><dd>${esc(run.harness_version)}</dd></div><div><dt>최근 기록</dt><dd>${stamp(run.updated_at)}</dd></div></dl>${delegationDetails(run)}${run.integration?.pr_url?`<div class="evidence-links">${evidenceLinks([{url:run.integration.pr_url,label:'후보 PR'}])}</div>`:''}${run.wait_reason?`<p class="role-note">${esc(run.wait_reason)}</p>`:''}${run.resume_at?`<p class="small">재확인 예약 · ${stamp(run.resume_at)}</p>`:''}${Array.isArray(run.evidence)&&run.evidence.length?`<div class="evidence-links">${evidenceLinks(run.evidence)}</div>`:'<p class="small muted">연결된 검사·독립 검수·원격 CI·최종 검수 근거는 보고서에서 확인하세요.</p>'}</article>`).join('')}</section>`;
}
function manager(){
  const {messages=[]}=state.overview;
  const composer=`<form id="message-form" class="composer"><div class="form-row"><label class="sr-only" for="message-content">PM에게 전달할 내용</label><textarea id="message-content" name="content" data-draft="message" rows="3" required maxlength="30000" placeholder="하고 싶은 일을 한글로 적어주세요.">${esc(draft('message'))}</textarea></div><p class="error-text" id="message-error" role="alert"></p><div class="form-actions"><span class="hint">먼저 계획을 확인하고, 확정하면 시작합니다.</span><button class="primary" type="submit" ${state.connected?'':'disabled'}>메시지 저장 ${workspaceIcon('arrow')}</button></div></form>`;
  const history=`<div class="conversation" aria-label="저장된 대화">${messages.length?messages.map(message=>`<article class="message ${message.role==='user'?'user':''}"><div class="message-heading"><strong>${message.role==='user'?'마스터':message.role==='assistant'?'PM 응답':'시스템 상태 안내'}</strong><time>${stamp(message.created_at)}</time>${message.status?badge(message.status):''}</div><div class="message-content">${esc(documentUI.text(`message:${message.id}`,'content',message.content))}</div>${documentUI.meta(`message:${message.id}`)}</article>`).join(''):'<p class="manager-empty">아직 대화가 없습니다.</p>'}</div>`;
  return managerUI.render(state.overview,{connected:state.connected,composer,history,technical:`<p class="small muted">${requestedPM()} · 실제 적용 설정은 아래 근거에서 확인합니다.</p>${pmRequests()}`,archive:planList(managerSnapshot(state.overview).plan?.id)});
}
function reviewDetails(reviews,reportId){
  const entries=Object.entries(reviews||{}).filter(([,review])=>review&&typeof review==='object');
  if(!entries.length)return '';
  return `<details class="review-reports mt-20"><summary>모델 검수 의견 ${entries.length}건</summary><p class="small muted mt-8">각 모델이 기록한 판단입니다. 시스템 집계와 실행 승인은 별도로 확인하세요.</p>${entries.map(([role,review])=>`<section class="role-config"><div class="section-line"><h3>${esc({reviewer:'독립 검수 의견',final:'Astra 최종 검수 의견',developer:'개발 역할 의견'}[role]||label(role))}</h3>${badge(review.verdict)}</div>${documentUI.meta(`review:${reportId}:${role}`)}<p class="report-summary">${esc(documentUI.text(`review:${reportId}:${role}`,'summary',review.summary||'검수 요약 미등록'))}</p><dl class="detail-grid mt-8"><div><dt>검수 대상 커밋</dt><dd class="mono">${esc(review.candidate_sha||'미확인')}</dd></div><div><dt>실행 식별값</dt><dd class="mono">${esc(review.execution_id||'미확인')}</dd></div></dl>${review.findings?.length?`<div class="review-findings">${review.findings.map((finding,index)=>`<div class="role-note"><strong>${esc(finding.finding_id||'검수 지적')}</strong><p>${esc(documentUI.text(`review:${reportId}:${role}`,`finding:${index}:detail`,finding.detail))}</p><p>근거 · ${esc(documentUI.text(`review:${reportId}:${role}`,`finding:${index}:evidence`,finding.evidence))}</p></div>`).join('')}</div>`:'<p class="small muted">기록된 지적 사항 없음</p>'}${review.resolved_findings?.length?`<p class="small">해결했다고 보고한 항목 · ${esc(listText(review.resolved_findings))}</p>`:''}</section>`).join('')}</details>`;
}
function reports(){const items=state.overview.reports||[];return pageHeading('보고서','시스템이 정리한 실행 사실과 PM의 판단을 구분해 확인합니다.')+progressTabs()+(items.length?`<div class="report-list">${items.map(report=>`<article class="panel"><div class="report-heading"><div><h2>${esc(documentUI.text(`report:${report.id}`,'title',report.title))}</h2><span class="badge">${esc(report.source==='system'?'시스템 집계':report.source==='fixture'?'모의 예시':report.source==='pm'?'PM 작성':`출처: ${report.source||'미확인'}`)}</span></div><time>${stamp(report.created_at)}</time></div>${documentUI.meta(`report:${report.id}`)}<p class="report-summary">${esc(documentUI.text(`report:${report.id}`,'summary',report.summary))}</p>${report.evidence?.length?`<div class="evidence-links">${evidenceLinks(report.evidence)}</div>`:'<p class="small muted">연결된 검사·CI 증거가 없습니다.</p>'}${reviewDetails(report.review_reports,report.id)}</article>`).join('')}</div>`:empty('아직 저장된 보고서가 없습니다','작업과 검수 결과가 기록되면 완료·진행·차단 상황과 연결된 증거를 여기서 확인할 수 있습니다.'));}
function isPending(approval){return ['pending','PENDING','WAITING_APPROVAL'].includes(approval.status);}
function approvals(){const items=state.overview.approvals||[];return pageHeading('승인','모델 검수와 마스터의 실행 권한은 별도입니다. 승인 대상과 조건을 확인하고 결정을 기록하세요.')+(items.length?`<div class="approval-list">${items.map(approval=>{const expired=approval.expires_at&&new Date(typeof approval.expires_at==='number'?approval.expires_at*1000:approval.expires_at).getTime()<=Date.now();return `<article class="panel"><div class="approval-head"><div><h2>${esc(documentUI.text(`approval:${approval.id}`,'title',approval.title))}</h2><p class="muted small">${esc(documentUI.text(`approval:${approval.id}`,'action',approval.action||'실행 유형 미정'))}</p></div>${badge(expired&&isPending(approval)?'EXPIRED':approval.status)}</div>${documentUI.meta(`approval:${approval.id}`)}<dl class="approval-grid"><div><dt>대상 환경</dt><dd>${esc(approval.environment||'미확인')}</dd></div><div><dt>비용 상한</dt><dd>${approval.cost_usd!==undefined&&approval.cost_usd!==null?`USD ${esc(approval.cost_usd)}`:'미확인'}</dd></div><div><dt>유효 기한</dt><dd>${stamp(approval.expires_at)}</dd></div></dl><dl class="detail-grid"><div><dt>실행 식별자 원문</dt><dd class="mono">${esc(approval.action)}</dd></div><div><dt>산출물 / 커밋</dt><dd class="mono">${esc(approval.artifact_sha||'미확인')}</dd></div><div><dt>승인 대상 식별값</dt><dd class="mono">${esc(approval.subject_digest||'미확인')}</dd></div><div><dt>변경 영향</dt><dd>${esc(documentUI.text(`approval:${approval.id}`,'impact',readable(approval.impact)))}</dd></div><div><dt>되돌리기</dt><dd>${esc(documentUI.text(`approval:${approval.id}`,'rollback',readable(approval.rollback)))}</dd></div></dl><details><summary>검수 근거 확인</summary><div class="verification">${esc(readable(approval.verification))}</div></details><div class="approval-actions"><p>${expired&&isPending(approval)?'유효 기한이 지났습니다. 새 실행안을 요청하세요.':isPending(approval)?'대상 변경 시 새 승인이 필요합니다.':'서버에 저장된 결정 상태입니다.'}</p>${isPending(approval)?`<button data-decision="reject" data-id="${esc(approval.id)}" ${state.connected?'':'disabled'}>반려</button><button data-decision="request_changes" data-id="${esc(approval.id)}" ${state.connected?'':'disabled'}>수정 요청</button><button class="primary" data-decision="approve" data-id="${esc(approval.id)}" ${!state.connected||expired||!approval.subject_digest?'disabled':''}>승인 검토 →</button>`:''}</div></article>`;}).join('')}</div>`:empty('검토를 기다리는 실행이 없습니다','실행 승인이 필요한 작업이 생기면 환경·비용·영향·되돌리기와 검수 근거가 함께 표시됩니다.'));}
function project(){const {project,roles=[],harnesses=[]}=state.overview;return pageHeading('프로젝트의 실행 기준','목표와 역할은 유지하고, 하네스 변경은 버전으로 검토합니다.','<button data-action="create-project">새 프로젝트 +</button>')+`<div class="project-layout"><section class="panel"><div class="section-line"><h2>${esc(project.name)}</h2>${badge(project.status)}</div><p>${esc(project.goal)}</p><div class="section-line mt-28"><h2>역할과 책임</h2><span>${roles.length}개 역할</span></div>${roles.length?roles.map(role=>`<div class="role-config"><strong>${esc(role.name)}</strong><p>${esc(role.responsibility||'책임 범위 미정')}</p><p>담당 후보 · ${esc(role.assigned_model||'미배정')}</p></div>`).join(''):'<p class="muted small">합의된 역할이 아직 없습니다.</p>'}<p class="status-note">계정별 공유 한도·자원·예산은 서버 정책으로 적용됩니다. 표시된 역할 수가 실제 동시 실행 수를 뜻하지 않습니다.</p></section><section class="panel"><div class="section-line"><h2>하네스</h2><span>활성 버전 ${esc(project.harness_version||'없음')}</span></div><p class="small muted">목표·완료 조건·허용 도구와 경로·검수 기준을 기록하세요. 저장한 초안은 자동으로 실행에 적용되지 않습니다.</p><form id="harness-form"><div class="form-row"><label for="harness-content">하네스 초안</label><textarea id="harness-content" name="content" data-draft="harness" rows="12" required maxlength="100000" placeholder="목표, 역할별 책임, 입력·출력, 검수 기준과 승인 범위를 정의하세요.">${esc(draft('harness',project.harness_content||''))}</textarea></div><p id="harness-error" class="error-text" role="alert"></p><div class="form-actions"><span class="hint">기준 버전 ${esc(project.harness_version||0)}</span><button class="primary" type="submit" ${state.connected?'':'disabled'}>초안 저장</button></div></form>${harnesses.length?`<details class="mt-20"><summary>저장된 하네스 ${harnesses.length}개</summary>${harnesses.map(harness=>`<div class="role-config"><strong>버전 ${esc(harness.version)}</strong> ${badge(harness.status)}<p>${stamp(harness.created_at)}</p><details><summary>내용 보기</summary><div class="verification">${esc(harness.content)}</div></details></div>`).join('')}</details>`:''}</section></div>`;}

function render(){
  if(state.authenticated&&state.projectId)history.replaceState(null,'',`#${state.view}?project=${encodeURIComponent(state.projectId)}`);
  const active=document.activeElement;const focusId=active?.id;const selection=active&&typeof active.selectionStart==='number'?[active.selectionStart,active.selectionEnd]:null;
  for(const detail of app.querySelectorAll('details[data-persist-key]'))openDetails.set(`${state.projectId}:${detail.dataset.persistKey}`,detail.open);
  const scroll=window.scrollY;app.innerHTML=state.authenticated&&!state.passwordChangeRequired&&!state.changingPassword?shell():authScreen();
  for(const id of busyForms){const submit=document.querySelector(`#${id} button[type=submit]`);if(submit){submit.disabled=true;submit.textContent='저장 중…';}}
  if(focusId){const replacement=document.getElementById(focusId);if(replacement){replacement.focus({preventScroll:true});if(selection&&replacement.setSelectionRange)replacement.setSelectionRange(...selection);}}
  for(const detail of app.querySelectorAll('details[data-persist-key]'))detail.open=Boolean(openDetails.get(`${state.projectId}:${detail.dataset.persistKey}`));
  if(state.overview)collaborationUI.mount(app,state.overview,state.projectId);
  window.scrollTo(0,scroll);
}
async function refresh({projects=false,silent=false}={}){
  if(!state.authenticated||state.passwordChangeRequired||state.changingPassword)return;
  if(state.refreshing){if(silent)return;while(state.refreshing)await new Promise(resolve=>setTimeout(resolve,50));}
  if(!state.authenticated||state.passwordChangeRequired||state.changingPassword)return;
  state.refreshing=true;const epoch=requestEpoch;
  try{
    if(projects||!state.projects.length){const result=await api('/api/projects');if(epoch!==requestEpoch)return;state.projects=result.projects||[];if(!state.projects.some(project=>project.id===state.projectId))state.projectId=state.projects[0]?.id||'';}
    if(state.projectId){const result=await api(`/api/projects/${encodeURIComponent(state.projectId)}/overview`);if(epoch!==requestEpoch)return;if(!collaborationUI.ingest(result,state.projectId)){state.error='이전 순서의 응답을 받았습니다. 마지막으로 확인한 상태를 유지합니다.';state.loading=false;render();return;}const serialized=JSON.stringify(result);const changed=serialized!==lastPayload||state.error||state.loading;state.overview=result;lastPayload=serialized;state.updatedAt=Date.now()/1000;state.error='';state.loading=false;if(changed||!silent)render();else if($('#connection'))$('#connection').innerHTML=connection();}
    else{state.loading=false;state.error='';render();}
  }catch(error){if(epoch!==requestEpoch)return;collaborationUI.disconnect(state.projectId);state.error=error.message;state.loading=false;render();}
  finally{state.refreshing=false;}
}
function openDialog(markup){dialog.innerHTML=markup;dialog.showModal();}
function closeButton(){return '<button type="button" class="quiet" data-action="close-dialog" aria-label="대화상자 닫기">×</button>';}
function createProject(){openDialog(`<div class="dialog-head"><h2 id="dialog-title">새 프로젝트</h2>${closeButton()}</div><p>목표와 초기 역할을 저장합니다. 실제 실행은 하네스 합의와 실행기 연결 이후 시작합니다.</p><form id="create-form"><div class="form-row"><label for="project-name">프로젝트 이름</label><input id="project-name" name="name" required maxlength="120" autofocus placeholder="예: AI Company 구축"></div><div class="form-row"><label for="project-goal">목표와 완료 기준</label><textarea id="project-goal" name="goal" required maxlength="20000" rows="4" placeholder="어떤 결과가 나오면 완료인지 적어주세요."></textarea></div><div class="form-row"><label for="project-roles">초기 역할 (선택)</label><textarea id="project-roles" name="roles" rows="3" placeholder="화면 개발: 관리 화면과 모바일 접근성&#10;서버 개발: 역할별 큐와 관리 API"></textarea><small>한 줄에 역할명: 책임을 입력하세요. 비워두면 PM과 역할을 정할 수 있습니다.</small></div><p class="error-text" id="create-error" role="alert"></p><div class="form-actions"><button type="button" data-action="close-dialog">취소</button><button class="primary" type="submit">프로젝트 만들기</button></div></form>`);}
function reviewPlan(id){
  const plan=state.overview.plans?.find(item=>item.id===id);
  if(!plan||plan.status!=='proposed'||!state.connected)return;
  openDialog(`<div class="dialog-head"><h2 id="dialog-title">계획 확정 검토</h2>${closeButton()}</div><p>이 계획을 확정하면 표시된 역할의 작업이 생성됩니다. 배포·호스트 변경 승인은 별도로 검토합니다.</p>${plan.mode==='fixture'?'<div class="banner">모의 계획 · 실제 모델 실행 없이 모의 실행 기록을 생성합니다.</div>':''}${planContent(plan)}<p class="mono">${esc(plan.digest)}</p><form id="plan-form" data-id="${esc(id)}" data-project="${esc(state.projectId)}" data-digest="${esc(plan.digest)}" data-base="${esc(plan.base_harness_version)}" data-key="${crypto.randomUUID()}"><label class="plan-ack"><input type="checkbox" name="reviewed" required>역할·허용 경로·완료 기준을 확인했습니다.</label><p class="error-text" id="plan-error" role="alert"></p><div class="form-actions"><button type="button" data-action="close-dialog">취소</button><button class="primary" type="submit">이 계획 확정</button></div></form>`);
}
function decide(id,decision){const approval=state.overview.approvals.find(item=>item.id===id);if(!approval)return;const displayedTranslation=documentUI.translationRef(`approval:${approval.id}`);const verb={approve:'승인',reject:'반려',request_changes:'수정 요청'}[decision];openDialog(`<div class="dialog-head"><h2 id="dialog-title">실행 ${verb} 기록</h2>${closeButton()}</div><p>아래 대상에만 결정을 기록합니다. 승인 기록 자체가 배포나 호스트 변경을 실행하지는 않습니다.</p><div class="dialog-artifact"><p class="small muted">${displayedTranslation?'한국어 번역 표시 · 원문 대상에 결정 연결':'원문 표시 · 번역 참조 없음'}</p><strong>${esc(documentUI.text(`approval:${approval.id}`,'title',approval.title))}</strong><p>${esc(approval.environment)} · 비용 상한 USD ${esc(approval.cost_usd??'미확인')}</p><p>유효 기한 ${stamp(approval.expires_at)}</p><p class="mono">${esc(approval.artifact_sha||'산출물 미확인')}</p><p class="mono">${esc(approval.subject_digest)}</p></div><form id="decision-form" data-translation-id="${esc(displayedTranslation?.id||'')}" data-translation-digest="${esc(displayedTranslation?.source_digest||'')}" data-project="${esc(state.projectId)}" data-id="${esc(id)}" data-decision="${decision}" data-digest="${esc(approval.subject_digest)}" data-key="${crypto.randomUUID()}"><div class="form-row"><label for="decision-comment">${decision==='approve'?'검토 의견 (선택)':'사유와 필요한 변경'}</label><textarea id="decision-comment" name="comment" rows="3" ${decision==='approve'?'':'required'} maxlength="8000" autofocus></textarea></div><p id="decision-error" class="error-text" role="alert"></p><div class="form-actions"><button type="button" data-action="close-dialog">취소</button><button type="submit" class="${decision==='approve'?'primary':'danger'}">${verb} 기록</button></div></form>`);}

document.addEventListener('input',event=>{const name=event.target.dataset.draft;if(name){const key=draftKey(name);if(name==='harness'&&draftBases[key]===undefined)draftBases[key]=state.overview?.project.harness_version;state.drafts[key]=event.target.value;}});
document.addEventListener('change',async event=>{if(event.target.id==='project-select'){dialog.close();requestEpoch++;state.projectId=event.target.value;state.overview=null;lastPayload='';state.loading=true;render();while(state.refreshing)await new Promise(resolve=>setTimeout(resolve,50));refresh();}});
document.addEventListener('click',async event=>{const nodeTarget=event.target.closest('[data-collaboration-node]'),transferTarget=event.target.closest('[data-collaboration-transfer]'),languageTarget=event.target.closest('[data-document-toggle]');if(nodeTarget||transferTarget){collaborationUI.select(state.projectId,nodeTarget?'node':'transfer',nodeTarget?.dataset.collaborationNode||transferTarget.dataset.collaborationTransfer);render();return;}if(event.target.closest('[data-collaboration-clear]')){collaborationUI.clear(state.projectId);render();return;}if(languageTarget){documentUI.toggle(languageTarget.dataset.documentToggle);render();return;}const navigation=event.target.closest('.nav a, .progress-tabs a');if(navigation&&!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&!event.altKey&&event.button===0){event.preventDefault();location.hash=navigation.getAttribute('href');state.view=readView();render();$('#main')?.focus({preventScroll:true});window.scrollTo(0,0);return;}const button=event.target.closest('button');if(!button)return;if(button.dataset.decision){decide(button.dataset.id,button.dataset.decision);return;}switch(button.dataset.action){case 'focus-message':$('#message-content')?.focus();$('#message-form')?.scrollIntoView({block:'center',behavior:'auto'});break;case 'change-password':requestEpoch++;state.changingPassword=true;state.error='';render();break;case 'cancel-password':state.changingPassword=false;render();refresh();break;case 'review-plan':reviewPlan(button.dataset.id);break;case 'close-dialog':dialog.close();break;case 'create-project':createProject();break;case 'refresh':await refresh({projects:true});if(!state.error)notify('서버 상태를 새로 불러왔습니다.');break;case 'logout':button.disabled=true;try{await api('/api/logout',{method:'POST',body:{}});requestEpoch++;state.authenticated=false;state.csrf='';state.overview=null;state.projects=[];state.drafts={};collaborationUI.reset();documentUI.clear();openDetails.clear();for(const key of Object.keys(draftBases))delete draftBases[key];state.error='';lastPayload='';render();}catch(error){notify(error.message);button.disabled=false;}break;}});
document.addEventListener('submit',async event=>{
  const form=event.target;if(!['login-form','password-form','message-form','harness-form','create-form','decision-form','plan-form'].includes(form.id))return;event.preventDefault();const submit=$('button[type="submit"]',form);if(submit.disabled||busyForms.has(form.id)||(!state.connected&&!['login-form','password-form'].includes(form.id)))return;busyForms.add(form.id);const submitProject=form.dataset.project||state.projectId;const original=submit.textContent;submit.disabled=true;submit.textContent='저장 중…';const values=Object.fromEntries(new FormData(form));const errorNode=$('.error-text',form);if(errorNode)errorNode.textContent='';
  try{
    if(form.id==='login-form'){const result=await api('/api/login',{method:'POST',body:state.loginMethod==='password'?{username:values.username,password:values.password}:{token:values.token}});form.reset();acceptSession(result);state.loading=true;state.error='';render();await refresh({projects:true});}
    else if(form.id==='password-form'){if(values.new_password!==values.confirm_password)throw new Error('새 비밀번호가 서로 일치하지 않습니다.');const result=await api('/api/password',{method:'POST',body:{current_password:values.current_password,new_password:values.new_password}});form.reset();acceptSession(result);state.error='';state.loading=true;render();await refresh({projects:true});notify('비밀번호를 변경했습니다.');}
    else if(form.id==='create-form'){const roles=values.roles.split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const split=line.indexOf(':');return {name:(split<0?line:line.slice(0,split)).trim(),responsibility:split<0?'':line.slice(split+1).trim()};});if(roles.some(role=>!role.name||!role.responsibility))throw new Error('각 역할을 역할명: 책임 형식으로 입력해주세요.');const result=await api('/api/projects',{method:'POST',body:{name:values.name.trim(),goal:values.goal.trim(),roles}});requestEpoch++;state.projectId=result.project.id;state.overview=null;lastPayload='';state.loading=true;dialog.close();await refresh({projects:true});notify('프로젝트를 서버에 저장했습니다.');}
    else if(form.id==='message-form'){await api(`/api/projects/${submitProject}/messages`,{method:'POST',body:{content:values.content}});if(state.drafts[`${submitProject}:message`]===values.content)delete state.drafts[`${submitProject}:message`];await refresh();notify('메시지를 저장했습니다. PM 응답을 기다립니다.');}
    else if(form.id==='harness-form'){await api(`/api/projects/${submitProject}/harness`,{method:'POST',body:{content:values.content,base_version:draftBases[`${submitProject}:harness`]??state.overview.project.harness_version}});await refresh();notify('하네스 초안을 저장했습니다. 아직 활성화되지 않았습니다.');}
    else if(form.id==='plan-form'){await api(`/api/projects/${encodeURIComponent(submitProject)}/plans/${encodeURIComponent(form.dataset.id)}/confirm`,{method:'POST',body:{plan_digest:form.dataset.digest,base_harness_version:Number(form.dataset.base),idempotency_key:form.dataset.key}});if(dialog.contains(form))dialog.close();await refresh();notify('계획을 확정했습니다. 역할별 작업은 자동 실행 대기열에서 이어집니다.');}
    else if(form.id==='decision-form'){await api(`/api/projects/${submitProject}/approvals/${form.dataset.id}/decisions`,{method:'POST',body:{decision:form.dataset.decision,comment:values.comment,subject_digest:form.dataset.digest,idempotency_key:form.dataset.key,displayed_translation:form.dataset.translationId?{id:form.dataset.translationId,source_digest:form.dataset.translationDigest}:null}});dialog.close();await refresh();notify('결정을 서버에 기록했습니다.');}
  }catch(error){if(form.id==='plan-form'&&['stale_plan','plan_mismatch','already_confirmed','idempotency_conflict','fixture_only'].includes(error.code)){form.dataset.stale='true';await refresh();}if(errorNode?.isConnected)errorNode.textContent=error.message;else notify(error.message);}
  finally{busyForms.delete(form.id);const current=document.querySelector(`#${form.id} button[type=submit]`);if(current){current.disabled=Boolean(form.dataset.stale)||(!state.connected&&!['login-form','password-form'].includes(form.id));current.textContent=original;}}
});
window.addEventListener('hashchange',()=>{const requested=new URLSearchParams(location.hash.split('?')[1]||'').get('project');if(requested&&requested!==state.projectId){dialog.close();requestEpoch++;state.projectId=requested;state.overview=null;lastPayload='';state.loading=true;refresh();}state.view=readView();document.title=`AI Company · ${views[state.view][1]}`;render();$('#main')?.focus({preventScroll:true});window.scrollTo(0,0);});
window.addEventListener('offline',()=>{state.connected=false;collaborationUI.disconnect(state.projectId);state.error='네트워크 연결이 끊겼습니다. 저장된 마지막 상태만 표시합니다.';render();});
window.addEventListener('online',()=>{refresh({projects:true});});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh({silent:true});});
setInterval(()=>{if(!document.hidden)refresh({silent:true});},5000);

async function boot(){try{const session=await api('/api/session');state.loginMethod=session.login_method||'token';acceptSession(session);state.loading=state.authenticated;render();if(state.authenticated)await refresh({projects:true});}catch(error){state.loading=false;state.error=error.message;render();}if('serviceWorker'in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{/* Optional offline shell; live requests remain usable. */});}}
boot();
