const $ = (selector, parent = document) => parent.querySelector(selector);
const app = $('#app');
const dialog = $('#dialog');
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const esc = escapeHTML;
const paths = {manager:['01','매니저'],progress:['02','역할별 진행'],reports:['03','보고서'],approvals:['04','승인'],project:['05','프로젝트']};
const labels = {IDLE:'배정 대기',MERGE_READY:'검수 통과',expired:'만료',developer:'개발',reviewer:'독립 검수',final_reviewer:'최종 검수',PLANNING:'계획 중',active:'활성',draft:'초안',superseded:'이전 버전',awaiting_worker:'실행기 연결 대기',READY:'준비',RUNNING:'진행 중',ACTIVE:'진행 중',PENDING:'검토 대기',pending:'검토 대기',DRAFT:'초안',WAITING_QUOTA:'사용량 대기',WAITING_CAPACITY:'후보 복귀 대기',WAITING_RETRY:'재시도 대기',WAITING_DEPENDENCY:'산출물 대기',WAITING_APPROVAL:'승인 대기',WAITING_PM:'PM 대기',RECONCILIATION_REQUIRED:'상태 대조 필요',BLOCK:'차단',BLOCKED:'차단',COMPLETE:'완료',COMPLETED:'완료',DONE:'완료',DEMO_READY:'모의 검증 완료',approved:'승인 기록됨',rejected:'반려됨',changes_requested:'수정 요청됨',request_changes:'수정 요청됨',EXPIRED:'만료',awaiting_pm:'PM 응답 대기',queued:'예약됨',unverified:'미검증',fixture:'모의 예시',live:'실제 연결'};
const state = {authenticated:false,csrf:'',projects:[],projectId:new URLSearchParams(location.hash.split('?')[1]||'').get('project')||'',overview:null,view:readView(),connected:navigator.onLine,updatedAt:null,error:'',loading:true,refreshing:false,drafts:{},demo:false};
let lastPayload = '';
let toastTimer;
let requestEpoch = 0;
const busyForms = new Set();
const draftBases = {};

function readView(){const name = location.hash.slice(1).split('?')[0];return Object.hasOwn(paths,name) ? name : 'progress';}
function label(status){return labels[status] || status || '미배정';}
function badge(status){const s=String(status||'');const kind=/WAIT|PENDING|pending|awaiting|EXPIRED/.test(s)?'waiting':/BLOCK|RECONCIL|rejected/.test(s)?'blocked':/RUNNING|ACTIVE/.test(s)?'running':/COMPLETE|DONE|approved/.test(s)?'complete':'';return `<span class="badge ${kind}">${esc(label(status))}</span>`;}
function stamp(value){if(!value)return '미정';const date=new Date(typeof value==='number'?value*1000:value);return Number.isNaN(date.getTime())?'미정':date.toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});}
function readable(value){if(value===null||value===undefined||value==='')return '미확인';if(typeof value==='object')return JSON.stringify(value,null,2);return String(value);}
function safeURL(value){if(typeof value!=='string'||!value.trim())return null;try{const url=new URL(value,location.origin);return ['https:','http:'].includes(url.protocol)?esc(url.href):null;}catch{return null;}}
function evidenceLinks(items=[]){return items.map(item=>{const url=safeURL(item.url);return url?`<a href="${url}" target="_blank" rel="noopener noreferrer">${esc(item.label||'증거 보기')} ↗</a>`:`<span class="muted small">${esc(item.label||'증거')} · 링크 미확인</span>`;}).join('');}
function notify(message){$('#announcer').textContent=message;const node=$('#toast');node.textContent=message;node.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.hidden=true,4500);}
function empty(title,description,action=''){return `<div class="empty"><div class="empty-mark" aria-hidden="true">·</div><h2>${esc(title)}</h2><p>${esc(description)}</p>${action}</div>`;}
function draftKey(name){return `${state.projectId}:${name}`;}
function draft(name,fallback=''){return state.drafts[draftKey(name)] ?? fallback;}

async function api(path,{method='GET',body}={}){
  if(body&&new TextEncoder().encode(JSON.stringify(body)).length>65536)throw new Error('입력 내용이 서버 제한을 초과했습니다. 내용을 줄여 다시 저장해주세요.');
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);
  try{
    const response=await fetch(path,{method,credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{Accept:'application/json',...(body?{'Content-Type':'application/json'}:{}),...(method!=='GET'&&state.csrf?{'X-CSRF-Token':state.csrf}:{})},...(body?{body:JSON.stringify(body)}:{})});
    let data;try{data=await response.json();}catch{throw new Error('서버 응답을 읽을 수 없습니다. 다시 연결해주세요.');}
    if(!response.ok){if(response.status===401&&state.authenticated){state.authenticated=false;state.csrf='';state.overview=null;state.projects=[];state.drafts={};for(const key of Object.keys(draftBases))delete draftBases[key];dialog.close();render();}const friendly={unauthorized:'접근 토큰이 올바르지 않거나 로그인이 만료되었습니다.',rate_limited:'로그인 시도가 많습니다. 잠시 뒤 다시 시도해주세요.',subject_mismatch:'승인 대상이 변경되었습니다. 최신 실행안을 다시 확인해주세요.',already_decided:'이미 결정된 승인입니다. 최신 상태를 확인해주세요.',expired:'승인 유효 기한이 지났습니다. 새 실행안이 필요합니다.',stale_harness:'하네스 기준 버전이 변경되었습니다. 최신 버전을 확인해주세요.',body_too_large:'입력 내용이 너무 깁니다. 내용을 줄여 다시 저장해주세요.',csrf:'로그인 상태 확인이 필요합니다. 다시 로그인해주세요.'};const error=new Error(friendly[data.error?.code]||data.error?.message||`요청 실패 (${response.status})`);error.code=data.error?.code;throw error;}
    state.connected=true;return data;
  }catch(error){if(error.name==='AbortError'||error instanceof TypeError){state.connected=false;throw new Error('서버에 연결할 수 없습니다. 연결을 복구한 뒤 다시 시도해주세요.');}throw error;}
  finally{clearTimeout(timer);}
}

function authScreen(){return `<div class="auth-shell"><section class="auth-story"><div class="brand"><div class="brand-mark" aria-hidden="true">a.</div>AI Company</div><div class="eyebrow">A workspace for your agents</div><h1>하나의 목표.<br>함께 움직이는 역할들.</h1><p>마스터와 PM이 방향을 정하고,<br>각 역할이 자기 일을 이어갑니다.</p></section><main class="auth-form" id="main"><div class="auth-inner"><div class="eyebrow mb-12">Master workspace</div><h2>작업 공간에 연결</h2><p>서버 관리자가 발급한 접근 토큰으로 로그인하세요.</p><form id="login-form"><div class="form-row"><label for="access-token">접근 토큰</label><input type="password" id="access-token" name="token" autocomplete="current-password" required autofocus placeholder="접근 토큰 입력"><small>토큰은 브라우저 저장소에 보관하지 않습니다.</small></div><p id="login-error" class="error-text" role="alert">${esc(state.error)}</p><button class="primary" type="submit">작업 공간 열기 <span aria-hidden="true">→</span></button></form><div class="auth-footer">진행 보고와 실행 승인을 분리해 관리합니다.<br>연결이 끊긴 동안에는 변경 요청을 전송할 수 없습니다.</div></div></main></div>`;}
function shell(){const pending=(state.overview?.approvals||[]).filter(isPending).length;return `<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark" aria-hidden="true">a.</div>AI Company</div><div><div class="workspace-caption">WORKSPACE</div><nav class="nav" aria-label="주요 화면">${Object.entries(paths).map(([name,[number,title]])=>`<a href="#${name}?project=${esc(state.projectId)}" aria-label="${title}" ${state.view===name?'aria-current="page"':''}><span class="nav-number" aria-hidden="true">${number}</span><span>${title}</span>${name==='approvals'&&pending?`<span class="nav-count">${pending}</span>`:''}</a>`).join('')}</nav></div><div class="sidebar-bottom"><div class="account"><div class="avatar" aria-hidden="true">M</div><div><strong>마스터</strong><span>프로젝트 관리</span></div></div><button class="quiet logout" data-action="logout">로그아웃 ↗</button></div><button class="quiet mobile-logout" data-action="logout">로그아웃</button></aside><div class="workspace"><header class="topbar"><div class="project-picker"><label for="project-select">프로젝트</label><select id="project-select" aria-label="프로젝트 선택">${state.projects.length?state.projects.map(project=>`<option value="${esc(project.id)}" ${project.id===state.projectId?'selected':''}>${esc(project.name)}</option>`).join(''):'<option>프로젝트 없음</option>'}</select></div><div id="connection" class="connection">${connection()}</div></header><main class="main" id="main" tabindex="-1">${content()}</main></div></div>`;}
function connection(){return `<span class="dot ${state.connected?'':'offline'}" aria-hidden="true"></span>${state.connected?(state.updatedAt?`${stamp(state.updatedAt)} 동기화`:'서버 연결 중'):'연결 끊김'}`;}
function pageHeading(title,description,actions=''){return `<div class="page-heading"><div><div class="eyebrow">${esc(state.overview?.project.name||'AI COMPANY')} / ${esc(paths[state.view][1])}</div><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${actions?`<div class="page-actions">${actions}</div>`:''}</div>`;}
function content(){
  const reconnect=state.error?`<div class="banner error" role="alert"><strong>동기화 확인 필요</strong><span>${esc(state.error)}${state.overview?' 마지막으로 받은 상태를 표시합니다.':''}</span><button data-action="refresh">다시 연결</button></div>`:'';
  if(state.loading&&!state.overview)return reconnect+pageHeading('작업 공간을 불러오는 중','서버에 저장된 프로젝트와 역할 상태를 확인합니다.')+'<div class="role-grid" aria-label="불러오는 중"><div class="skeleton"></div><div class="skeleton"></div></div>';
  if(!state.projects.length)return reconnect+pageHeading('첫 목표를 정해볼까요?','프로젝트를 만들고 PM에게 목표와 완료 기준을 전달하세요.')+empty('아직 프로젝트가 없습니다','프로젝트와 대화는 서버에 저장됩니다. 실행은 합의된 하네스와 실제 작업 환경이 준비된 뒤 연결됩니다.','<button class="primary" data-action="create-project">프로젝트 만들기 +</button>');
  if(!state.overview)return reconnect+empty('프로젝트 상태를 불러오지 못했습니다','서버 연결을 확인한 뒤 다시 시도하세요.','<button data-action="refresh">다시 불러오기</button>');
  const fixture=state.overview.readiness?.mode==='fixture'?'<div class="banner"><strong>모의 예시 데이터</strong><span>화면·상태 전이 확인용입니다. 실제 에이전트 실행이나 배포 완료를 뜻하지 않습니다.</span></div>':'';
  return reconnect+fixture+({progress:progress,manager:manager,reports:reports,approvals:approvals,project:project}[state.view])();
}
function progress(){
  const {roles=[],tasks=[],approvals=[]}=state.overview;
  const running=roles.filter(role=>/RUNNING|ACTIVE/.test(role.status)).length;
  const waiting=roles.filter(role=>/WAIT/.test(role.status)).length;
  const completed=tasks.filter(task=>/^(COMPLETE|COMPLETED|DONE)$/.test(task.status)).length;
  return pageHeading('각자의 흐름으로, 같은 목표를 향해','한 역할이 기다리는 동안에도 준비된 독립 작업은 계속합니다.','<button data-action="refresh">새로고침 ↻</button><button class="primary" data-action="create-project">새 프로젝트 +</button>')+`<div class="metrics" aria-label="프로젝트 상태 요약">${[[running,'진행 중인 역할','역할'],[waiting,'대기 중인 역할','역할'],[completed,'완료한 작업','작업'],[approvals.filter(isPending).length,'마스터 승인 대기','건']].map(([count,title,unit])=>`<div class="metric"><span class="metric-label">${title}</span><span class="metric-value">${count.toString().padStart(2,'0')}</span><span class="metric-unit">${unit}</span></div>`).join('')}</div><div class="section-line"><h2>역할별 흐름 <span class="muted">${roles.length}</span></h2><span>역할별 독립 큐 · 서버 상태 기준</span></div>${roles.length?`<div class="role-grid">${roles.map((role,index)=>roleCard(role,index,tasks)).join('')}</div>`:empty('역할 배치를 기다리고 있습니다','매니저에게 필요한 역할과 책임을 전달하세요. 합의된 역할이 여기에 표시됩니다.','<a href="#manager">매니저에서 목표 정하기 →</a>')}<p class="footer-note">모델 이름은 배정 정보입니다. 실제 적용 설정과 검수 완료 여부는 연결된 증거로 확인합니다.</p>`;
}
function roleCard(role,index,tasks){
  const own=tasks.filter(task=>task.role_id===role.id);
  const current=tasks.find(task=>task.id===role.current_task_id)||own.find(task=>task.status==='RUNNING');
  const next=tasks.find(task=>task.id===role.next_task_id)||own.find(task=>task.id!==current?.id&&/^(READY|QUEUED|WAITING_DEPENDENCY)$/.test(task.status));
  const taskName=id=>tasks.find(task=>task.id===id)?.title||id;
  const handoffs=role.handoffs||[];
  return `<article class="role"><header class="role-heading"><div class="role-top"><h3><span class="role-number">R${String(index+1).padStart(2,'0')}</span>${esc(role.name)}</h3>${badge(role.status)}</div><p>${esc(role.responsibility||'책임 범위 미정')}</p></header><div class="role-body"><div class="agent-row"><span class="agent-token" aria-hidden="true">${role.assigned_model?'AI':'—'}</span><div><strong>${esc(role.assigned_model||'담당 모델 미배정')}</strong><span class="mono">${role.session_id?`SESSION ${esc(role.session_id)}`:'세션 미시작'}</span></div></div><div class="task-row"><div class="eyebrow">현재 작업</div><div class="task-title">${esc(current?.title||'진행 중인 작업 없음')}</div>${current?`<div class="task-meta">${badge(current.status)}<span>${esc(label(current.stage)||'단계 미정')}</span></div>`:'<p>준비된 작업의 배정을 기다립니다.</p>'}${current?.dependencies?.length?`<p class="mt-8">필요한 결과 · ${esc(current.dependencies.map(taskName).join(', '))}</p>`:''}${current?.repair_reason?.length?`<div class="role-note">수정 요청 · ${esc(readable(current.repair_reason))}</div>`:''}${current?.worktree?`<p class="mono mt-8">${esc(current.worktree)}</p>`:''}</div><div class="task-row"><div class="eyebrow">다음 작업</div><p>${esc(next?.title||'등록된 다음 작업 없음')}</p>${next?.dependencies?.length?`<p>의존 작업 · ${esc(next.dependencies.map(taskName).join(', '))}</p>`:''}</div>${role.wait_reason?`<div class="role-note">${esc(role.wait_reason)}${role.resume_at?`<br>재확인 예약 · ${stamp(role.resume_at)}`:''}</div>`:''}${handoffs.length?`<details><summary>담당자 이관 이력 ${handoffs.length}건</summary><div class="verification">${esc(handoffs.map(readable).join('\n'))}</div></details>`:''}</div><footer class="role-footer"><span>작업 ${own.length}개${handoffs.length?` · 이관 ${handoffs.length}회`:''}</span><span>${esc(role.evidence_state?label(role.evidence_state):'실행 증거 미확인')}</span></footer></article>`;
}
function manager(){const {messages=[],project,readiness={}}=state.overview;return pageHeading('목표를 정하고, 다음 판단을 함께','마스터의 대화 창구는 Astra Ultra PM입니다. 역할별 상태는 진행 화면에서 확인하세요.')+`<div class="split"><section class="panel"><div class="section-line"><h2>Astra Ultra <span class="muted small">프로젝트 매니저</span></h2>${badge(readiness.pm||'unverified')}</div><div class="banner neutral"><span>PM 요청 구성: GPT-6 Astra Ultra. 실제 모델·추론 적용은 별도 확인이 필요합니다. 시스템 상태 안내는 PM의 답변으로 표시하지 않습니다.</span></div><div class="conversation" aria-label="저장된 대화">${messages.length?messages.map(message=>`<article class="message ${message.role==='user'?'user':''}"><div class="message-heading"><strong>${message.role==='user'?'마스터':message.role==='assistant'?'PM 응답':'시스템 상태 안내'}</strong><time>${stamp(message.created_at)}</time>${message.status?badge(message.status):''}</div><div class="message-content">${esc(message.content)}</div></article>`).join(''):empty('첫 목표를 남겨주세요','만들고 싶은 결과, 역할별 책임, 완료 기준을 전달하세요. 요청은 서버에 저장되어 PM 연결을 기다립니다.')}</div><form id="message-form" class="composer"><div class="form-row"><label for="message-content">PM에게 전달할 내용</label><textarea id="message-content" name="content" data-draft="message" rows="3" required maxlength="30000" placeholder="이번 프로젝트의 목표와 완료 기준을 적어주세요.">${esc(draft('message'))}</textarea></div><p class="error-text" id="message-error" role="alert"></p><div class="form-actions"><span class="hint">저장 완료와 PM 응답 완료는 구분됩니다.</span><button class="primary" type="submit" ${state.connected?'':'disabled'}>메시지 저장 →</button></div></form></section><aside class="panel"><h2>합의의 기준</h2><dl class="side-facts"><div class="fact"><dt>프로젝트 목표</dt><dd>${esc(project.goal)}</dd></div><div class="fact"><dt>활성 하네스</dt><dd>${project.harness_version?`버전 ${esc(project.harness_version)}`:'활성 버전 없음'}</dd></div><div class="fact"><dt>PM이 대기하는 동안</dt><dd>이미 합의한 범위의 독립 작업은 계속합니다. 새로운 판단은 PM 복귀를 기다립니다.</dd></div><div class="fact"><dt>실행 승인</dt><dd>배포·호스트 변경 등 구체적인 실행 대상은 <a href="#approvals">승인 화면</a>에서 검토합니다.</dd></div></dl></aside></div>`;}
function reports(){const items=state.overview.reports||[];return pageHeading('진행 상황을, 근거와 함께','시스템이 정리한 실행 사실과 PM의 판단을 구분해 확인합니다.')+(items.length?`<div class="report-list">${items.map(report=>`<article class="panel"><div class="report-heading"><div><h2>${esc(report.title)}</h2><span class="badge">${esc(report.source==='system'?'시스템 집계':report.source==='fixture'?'모의 예시':report.source==='pm'?'PM 작성':`출처: ${report.source||'미확인'}`)}</span></div><time>${stamp(report.created_at)}</time></div><p class="report-summary">${esc(report.summary)}</p>${report.evidence?.length?`<div class="evidence-links">${evidenceLinks(report.evidence)}</div>`:'<p class="small muted">연결된 검사·CI 증거가 없습니다.</p>'}</article>`).join('')}</div>`:empty('아직 저장된 보고서가 없습니다','작업과 검수 결과가 기록되면 완료·진행·차단 상황과 연결된 증거를 여기서 확인할 수 있습니다.'));}
function isPending(approval){return ['pending','PENDING','WAITING_APPROVAL'].includes(approval.status);}
function approvals(){const items=state.overview.approvals||[];return pageHeading('검토할 실행만, 한곳에','모델 검수와 마스터의 실행 권한은 별도입니다. 승인 대상과 조건을 확인하고 결정을 기록하세요.')+(items.length?`<div class="approval-list">${items.map(approval=>{const expired=approval.expires_at&&new Date(typeof approval.expires_at==='number'?approval.expires_at*1000:approval.expires_at).getTime()<=Date.now();return `<article class="panel"><div class="approval-head"><div><h2>${esc(approval.title)}</h2><p class="muted small">${esc(approval.action||'실행 유형 미정')}</p></div>${badge(expired&&isPending(approval)?'EXPIRED':approval.status)}</div><dl class="approval-grid"><div><dt>대상 환경</dt><dd>${esc(approval.environment||'미확인')}</dd></div><div><dt>비용 상한</dt><dd>${approval.cost_usd!==undefined&&approval.cost_usd!==null?`USD ${esc(approval.cost_usd)}`:'미확인'}</dd></div><div><dt>유효 기한</dt><dd>${stamp(approval.expires_at)}</dd></div></dl><dl class="detail-grid"><div><dt>산출물 / 커밋</dt><dd class="mono">${esc(approval.artifact_sha||'미확인')}</dd></div><div><dt>승인 대상 식별값</dt><dd class="mono">${esc(approval.subject_digest||'미확인')}</dd></div><div><dt>변경 영향</dt><dd>${esc(readable(approval.impact))}</dd></div><div><dt>되돌리기</dt><dd>${esc(readable(approval.rollback))}</dd></div></dl><details><summary>검수 근거 확인</summary><div class="verification">${esc(readable(approval.verification))}</div></details><div class="approval-actions"><p>${expired&&isPending(approval)?'유효 기한이 지났습니다. 새 실행안을 요청하세요.':isPending(approval)?'대상 변경 시 새 승인이 필요합니다.':'서버에 저장된 결정 상태입니다.'}</p>${isPending(approval)?`<button data-decision="reject" data-id="${esc(approval.id)}" ${state.connected?'':'disabled'}>반려</button><button data-decision="request_changes" data-id="${esc(approval.id)}" ${state.connected?'':'disabled'}>수정 요청</button><button class="primary" data-decision="approve" data-id="${esc(approval.id)}" ${!state.connected||expired||!approval.subject_digest?'disabled':''}>승인 검토 →</button>`:''}</div></article>`;}).join('')}</div>`:empty('검토를 기다리는 실행이 없습니다','실행 승인이 필요한 작업이 생기면 환경·비용·영향·되돌리기와 검수 근거가 함께 표시됩니다.'));}
function project(){const {project,roles=[],harnesses=[]}=state.overview;return pageHeading('프로젝트의 실행 기준','목표와 역할은 유지하고, 하네스 변경은 버전으로 검토합니다.','<button data-action="create-project">새 프로젝트 +</button>')+`<div class="project-layout"><section class="panel"><div class="section-line"><h2>${esc(project.name)}</h2>${badge(project.status)}</div><p>${esc(project.goal)}</p><div class="section-line mt-28"><h2>역할과 책임</h2><span>${roles.length}개 역할</span></div>${roles.length?roles.map(role=>`<div class="role-config"><strong>${esc(role.name)}</strong><p>${esc(role.responsibility||'책임 범위 미정')}</p><p>담당 후보 · ${esc(role.assigned_model||'미배정')}</p></div>`).join(''):'<p class="muted small">합의된 역할이 아직 없습니다.</p>'}<p class="status-note">계정별 공유 한도·자원·예산은 서버 정책으로 적용됩니다. 표시된 역할 수가 실제 동시 실행 수를 뜻하지 않습니다.</p></section><section class="panel"><div class="section-line"><h2>하네스</h2><span>활성 버전 ${esc(project.harness_version||'없음')}</span></div><p class="small muted">목표·완료 조건·허용 도구와 경로·검수 기준을 기록하세요. 저장한 초안은 자동으로 실행에 적용되지 않습니다.</p><form id="harness-form"><div class="form-row"><label for="harness-content">하네스 초안</label><textarea id="harness-content" name="content" data-draft="harness" rows="12" required maxlength="100000" placeholder="목표, 역할별 책임, 입력·출력, 검수 기준과 승인 범위를 정의하세요.">${esc(draft('harness',project.harness_content||''))}</textarea></div><p id="harness-error" class="error-text" role="alert"></p><div class="form-actions"><span class="hint">기준 버전 ${esc(project.harness_version||0)}</span><button class="primary" type="submit" ${state.connected?'':'disabled'}>초안 저장</button></div></form>${harnesses.length?`<details class="mt-20"><summary>저장된 하네스 ${harnesses.length}개</summary>${harnesses.map(harness=>`<div class="role-config"><strong>버전 ${esc(harness.version)}</strong> ${badge(harness.status)}<p>${stamp(harness.created_at)}</p><details><summary>내용 보기</summary><div class="verification">${esc(harness.content)}</div></details></div>`).join('')}</details>`:''}</section></div>`;}

function render(){
  if(state.authenticated&&state.projectId)history.replaceState(null,'',`#${state.view}?project=${encodeURIComponent(state.projectId)}`);
  const active=document.activeElement;const focusId=active?.id;const selection=active&&typeof active.selectionStart==='number'?[active.selectionStart,active.selectionEnd]:null;
  const scroll=window.scrollY;app.innerHTML=state.authenticated?shell():authScreen();
  for(const id of busyForms){const submit=document.querySelector(`#${id} button[type=submit]`);if(submit){submit.disabled=true;submit.textContent='저장 중…';}}
  if(focusId){const replacement=document.getElementById(focusId);if(replacement){replacement.focus({preventScroll:true});if(selection&&replacement.setSelectionRange)replacement.setSelectionRange(...selection);}}
  window.scrollTo(0,scroll);
}
async function refresh({projects=false,silent=false}={}){
  if(!state.authenticated)return;
  if(state.refreshing){if(silent)return;while(state.refreshing)await new Promise(resolve=>setTimeout(resolve,50));}
  if(!state.authenticated)return;
  state.refreshing=true;const epoch=requestEpoch;
  try{
    if(projects||!state.projects.length){const result=await api('/api/projects');if(epoch!==requestEpoch)return;state.projects=result.projects||[];if(!state.projects.some(project=>project.id===state.projectId))state.projectId=state.projects[0]?.id||'';}
    if(state.projectId){const result=await api(`/api/projects/${encodeURIComponent(state.projectId)}/overview`);if(epoch!==requestEpoch)return;const serialized=JSON.stringify(result);const changed=serialized!==lastPayload||state.error||state.loading;state.overview=result;lastPayload=serialized;state.updatedAt=Date.now()/1000;state.error='';state.loading=false;if(changed||!silent)render();else if($('#connection'))$('#connection').innerHTML=connection();}
    else{state.loading=false;state.error='';render();}
  }catch(error){if(epoch!==requestEpoch)return;state.error=error.message;state.loading=false;render();}
  finally{state.refreshing=false;}
}
function openDialog(markup){dialog.innerHTML=markup;dialog.showModal();}
function closeButton(){return '<button type="button" class="quiet" data-action="close-dialog" aria-label="대화상자 닫기">×</button>';}
function createProject(){openDialog(`<div class="dialog-head"><h2 id="dialog-title">새 프로젝트</h2>${closeButton()}</div><p>목표와 초기 역할을 저장합니다. 실제 실행은 하네스 합의와 실행기 연결 이후 시작합니다.</p><form id="create-form"><div class="form-row"><label for="project-name">프로젝트 이름</label><input id="project-name" name="name" required maxlength="120" autofocus placeholder="예: AI Company 구축"></div><div class="form-row"><label for="project-goal">목표와 완료 기준</label><textarea id="project-goal" name="goal" required maxlength="20000" rows="4" placeholder="어떤 결과가 나오면 완료인지 적어주세요."></textarea></div><div class="form-row"><label for="project-roles">초기 역할 (선택)</label><textarea id="project-roles" name="roles" rows="3" placeholder="화면 개발: 관리 화면과 모바일 접근성&#10;서버 개발: 역할별 큐와 관리 API"></textarea><small>한 줄에 역할명: 책임을 입력하세요. 비워두면 PM과 역할을 정할 수 있습니다.</small></div><p class="error-text" id="create-error" role="alert"></p><div class="form-actions"><button type="button" data-action="close-dialog">취소</button><button class="primary" type="submit">프로젝트 만들기</button></div></form>`);}
function decide(id,decision){const approval=state.overview.approvals.find(item=>item.id===id);if(!approval)return;const verb={approve:'승인',reject:'반려',request_changes:'수정 요청'}[decision];openDialog(`<div class="dialog-head"><h2 id="dialog-title">실행 ${verb} 기록</h2>${closeButton()}</div><p>아래 대상에만 결정을 기록합니다. 승인 기록 자체가 배포나 호스트 변경을 실행하지는 않습니다.</p><div class="dialog-artifact"><strong>${esc(approval.title)}</strong><p>${esc(approval.environment)} · 비용 상한 USD ${esc(approval.cost_usd??'미확인')}</p><p>유효 기한 ${stamp(approval.expires_at)}</p><p class="mono">${esc(approval.artifact_sha||'산출물 미확인')}</p><p class="mono">${esc(approval.subject_digest)}</p></div><form id="decision-form" data-id="${esc(id)}" data-decision="${decision}" data-digest="${esc(approval.subject_digest)}" data-key="${crypto.randomUUID()}"><div class="form-row"><label for="decision-comment">${decision==='approve'?'검토 의견 (선택)':'사유와 필요한 변경'}</label><textarea id="decision-comment" name="comment" rows="3" ${decision==='approve'?'':'required'} maxlength="8000" autofocus></textarea></div><p id="decision-error" class="error-text" role="alert"></p><div class="form-actions"><button type="button" data-action="close-dialog">취소</button><button type="submit" class="${decision==='approve'?'primary':'danger'}">${verb} 기록</button></div></form>`);}

document.addEventListener('input',event=>{const name=event.target.dataset.draft;if(name){const key=draftKey(name);if(name==='harness'&&draftBases[key]===undefined)draftBases[key]=state.overview?.project.harness_version;state.drafts[key]=event.target.value;}});
document.addEventListener('change',async event=>{if(event.target.id==='project-select'){requestEpoch++;state.projectId=event.target.value;state.overview=null;lastPayload='';state.loading=true;render();while(state.refreshing)await new Promise(resolve=>setTimeout(resolve,50));refresh();}});
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.decision){decide(button.dataset.id,button.dataset.decision);return;}switch(button.dataset.action){case 'close-dialog':dialog.close();break;case 'create-project':createProject();break;case 'refresh':await refresh({projects:true});if(!state.error)notify('서버 상태를 새로 불러왔습니다.');break;case 'logout':button.disabled=true;try{await api('/api/logout',{method:'POST',body:{}});requestEpoch++;state.authenticated=false;state.csrf='';state.overview=null;state.projects=[];state.drafts={};for(const key of Object.keys(draftBases))delete draftBases[key];state.error='';lastPayload='';render();}catch(error){notify(error.message);button.disabled=false;}break;}});
document.addEventListener('submit',async event=>{
  const form=event.target;if(!['login-form','message-form','harness-form','create-form','decision-form'].includes(form.id))return;event.preventDefault();const submit=$('button[type="submit"]',form);if(submit.disabled||busyForms.has(form.id))return;busyForms.add(form.id);const submitProject=state.projectId;const original=submit.textContent;submit.disabled=true;submit.textContent='저장 중…';const values=Object.fromEntries(new FormData(form));const errorNode=$('.error-text',form);if(errorNode)errorNode.textContent='';
  try{
    if(form.id==='login-form'){const result=await api('/api/login',{method:'POST',body:{token:values.token}});state.csrf=result.csrf_token||'';state.authenticated=true;state.loading=true;state.error='';$('#access-token').value='';render();await refresh({projects:true});}
    else if(form.id==='create-form'){const roles=values.roles.split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const split=line.indexOf(':');return {name:(split<0?line:line.slice(0,split)).trim(),responsibility:split<0?'':line.slice(split+1).trim()};});if(roles.some(role=>!role.name||!role.responsibility))throw new Error('각 역할을 역할명: 책임 형식으로 입력해주세요.');const result=await api('/api/projects',{method:'POST',body:{name:values.name.trim(),goal:values.goal.trim(),roles}});requestEpoch++;state.projectId=result.project.id;state.overview=null;lastPayload='';state.loading=true;dialog.close();await refresh({projects:true});notify('프로젝트를 서버에 저장했습니다.');}
    else if(form.id==='message-form'){await api(`/api/projects/${submitProject}/messages`,{method:'POST',body:{content:values.content}});if(state.drafts[`${submitProject}:message`]===values.content)delete state.drafts[`${submitProject}:message`];await refresh();notify('메시지를 저장했습니다. PM 응답을 기다립니다.');}
    else if(form.id==='harness-form'){await api(`/api/projects/${submitProject}/harness`,{method:'POST',body:{content:values.content,base_version:draftBases[`${submitProject}:harness`]??state.overview.project.harness_version}});await refresh();notify('하네스 초안을 저장했습니다. 아직 활성화되지 않았습니다.');}
    else if(form.id==='decision-form'){await api(`/api/projects/${submitProject}/approvals/${form.dataset.id}/decisions`,{method:'POST',body:{decision:form.dataset.decision,comment:values.comment,subject_digest:form.dataset.digest,idempotency_key:form.dataset.key}});dialog.close();await refresh();notify('결정을 서버에 기록했습니다.');}
  }catch(error){if(errorNode?.isConnected)errorNode.textContent=error.message;else notify(error.message);}
  finally{busyForms.delete(form.id);const current=document.querySelector(`#${form.id} button[type=submit]`);if(current){current.disabled=!state.connected&&form.id!=='login-form';current.textContent=original;}}
});
window.addEventListener('hashchange',()=>{const requested=new URLSearchParams(location.hash.split('?')[1]||'').get('project');if(requested&&requested!==state.projectId){requestEpoch++;state.projectId=requested;state.overview=null;lastPayload='';state.loading=true;refresh();}state.view=readView();document.title=`AI Company · ${paths[state.view][1]}`;render();$('#main')?.focus({preventScroll:true});window.scrollTo(0,0);});
window.addEventListener('offline',()=>{state.connected=false;state.error='네트워크 연결이 끊겼습니다. 저장된 마지막 상태만 표시합니다.';render();});
window.addEventListener('online',()=>{refresh({projects:true});});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh({silent:true});});
setInterval(()=>{if(!document.hidden)refresh({silent:true});},5000);

async function boot(){try{const session=await api('/api/session');state.authenticated=Boolean(session.authenticated);state.csrf=session.csrf_token||'';state.loading=state.authenticated;render();if(state.authenticated)await refresh({projects:true});}catch(error){state.loading=false;state.error=error.message;render();}if('serviceWorker'in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{/* Optional offline shell; live requests remain usable. */});}}
boot();
