const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search),project=params.get('project'),snapshot=params.get('snapshot'),fingerprint=params.get('fingerprint');
const valid=/^[a-f0-9]{32}$/.test(project||'')&&snapshot?.length<=400&&/^[a-f0-9]{64}$/.test(fingerprint||'');
const endpoint=`/api/projects/${encodeURIComponent(project)}/diagrams`,storageKey=`diagram-request:${project}:${snapshot}:${fingerprint}`;
let csrf='',busy=false,items=[],selected=null,requestKey=null;
const time=v=>new Date(v*1000).toLocaleString('ko-KR');
function notice(message,error=false){$('#notice').textContent=message;$('#notice').classList.toggle('error',error);}
async function api(path,body){let response;try{response=await fetch(path,{credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},...(body?{method:'POST',body:JSON.stringify(body)}:{})});}catch{throw new Error('연결을 확인하지 못했습니다. 같은 요청으로 다시 확인해 주세요.');}let data;try{data=await response.json();}catch{throw new Error('응답을 읽지 못했습니다. 같은 요청으로 다시 확인해 주세요.');}if(!response.ok){const error=new Error(({unauthorized:'다시 로그인한 뒤 같은 요청을 확인해 주세요.',invalid_csrf:'로그인 상태가 바뀌었습니다. 새로고침 후 같은 요청을 확인해 주세요.'}[data.error?.code]||data.error?.message||'요청을 확인하지 못했습니다.'));error.code=data.error?.code;throw error;}return data;}
function actions(){ $('#actions').innerHTML=csrf?`<button class="primary" type="button" id="generate" ${busy?'disabled':''}>${busy?'생성 중':requestKey?'같은 요청 확인':'그림 만들기'}</button><a class="button" href="/?workspace=integrated#progress?project=${encodeURIComponent(project)}">진행</a>`:'';$('#generate')?.addEventListener('click',generate);}
function file(receipt,name){return `${endpoint}/${receipt.id}/${name}`;}
function show(document){selected=document?.request_key;if(!document||document.status!=='completed')return;const r=document.receipt;if(r.project_id!==project)return;const old=r.snapshot_id!==snapshot||r.snapshot_fingerprint!==fingerprint;$('#result').innerHTML=`<h2>저장본</h2><p>${esc(time(r.observed_at))} 기준 · ${r.source==='fixture'?'예시 기록 · 실제 실행 아님':r.mode==='planned'?'계획 · 실행 전':'저장된 실행 기록'}${old?' · 선택한 현재 자료와 다름':''}</p>${r.renderer_exclusions?.length?`<p>이관 관계 ${r.renderer_exclusions.length}건은 그림 아래 관계 목록에 표시됩니다.</p>`:''}<nav class="downloads" aria-label="그림 다운로드">${[['index.html','HTML'],['diagram.svg','SVG'],['input.json','원본 JSON'],['receipt.json','생성 근거']].map(([name,title])=>`<a class="button" href="${file(r,name)}?download=1" download>${title}</a>`).join('')}</nav><iframe title="한국어 고정 그림 · 실행 권한 없음" sandbox="" src="${file(r,'index.html')}"></iframe><details><summary>기준</summary><dl>${[['프로젝트',r.project_id],['계획',r.plan_id],['계획 digest',r.plan_digest],['실행',r.run_id||'없음'],['입력 SHA-256',r.input_sha256],['Archify 커밋',r.archify_commit]].map(([k,v])=>`<dt>${k}</dt><dd><code>${esc(v)}</code></dd>`).join('')}</dl><p>그림 생성 검사는 작업 검사·독립 검수·승인 결과와 다릅니다.</p></details>`;}
async function load(){const data=await api(endpoint);if(data.project_id!==project)throw new Error('다른 프로젝트의 응답입니다.');items=data.items;const resume=items.find(x=>x.status==='prepared'&&x.request_key===params.get('resume')&&x.snapshot_id===snapshot&&x.snapshot_fingerprint===fingerprint);if(resume){requestKey=resume.request_key;try{sessionStorage.setItem(storageKey,requestKey);}catch{}actions();notice('중단된 요청입니다. 같은 요청 확인을 누르면 처음 저장한 자료로 이어갑니다.');}$('#history-list').innerHTML=items.length?items.map((item,index)=>item.status==='prepared'?`<a class="button" href="/diagram-view.html?project=${encodeURIComponent(project)}&snapshot=${encodeURIComponent(item.snapshot_id)}&fingerprint=${encodeURIComponent(item.snapshot_fingerprint)}&resume=${encodeURIComponent(item.request_key)}">${esc(time(item.created_at))} · 중단 요청 확인</a>`:item.status==='failed'?`<details><summary>${esc(time(item.created_at))} · 생성 실패</summary><p>${esc(item.error?.message||'그림을 만들지 못했습니다.')}</p><p>원인: ${esc(item.error?.code||'미기록')}</p><p>대상: ${esc(item.snapshot_id)}</p></details>`:`<button type="button" data-record="${index}" ${item.status!=='completed'?'disabled':''}>${esc(time(item.created_at))} · ${item.status==='completed'?'저장됨':item.status==='failed'?'생성 실패':'중단 후 확인 필요'}</button>`).join(''):'<p>저장된 그림이 없습니다.</p>';$('#history-list').querySelectorAll('[data-record]').forEach(el=>el.addEventListener('click',()=>show(items[Number(el.dataset.record)])));if(!selected)show(items.find(x=>x.status==='completed'&&x.snapshot_id===snapshot)||items.find(x=>x.status==='completed'));const failed=items.find(x=>x.snapshot_id===snapshot&&x.status==='failed');const good=items.find(x=>x.snapshot_id===snapshot&&x.status==='completed');if(failed&&(!good||failed.created_at>=good.created_at))notice(`${failed.error?.message||'최근 그림 생성에 실패했습니다.'}\n${$('#result iframe')?'보이는 저장본은 이전 시점의 자료입니다.':'저장된 그림이 없습니다.'} 원본과 실패 이력은 유지됩니다.`,true);}
async function generate(){if(busy)return;busy=true;if(!requestKey){requestKey=crypto.randomUUID();try{sessionStorage.setItem(storageKey,requestKey);}catch{}}actions();notice('선택한 자료를 고정해 그림을 만듭니다. 작업 실행이나 승인은 시작되지 않습니다.');try{const result=await api(endpoint,{snapshot_id:snapshot,fingerprint,idempotency_key:requestKey});if(result.project_id!==project||result.snapshot_id!==snapshot||result.snapshot_fingerprint!==fingerprint)throw new Error('그림 응답의 대상이 다릅니다.');if(result.status==='failed')notice(result.error?.message||'그림 생성에 실패했습니다. 이전 그림과 원본은 유지합니다.',true);else if(result.status==='completed'){show(result);notice('그림을 저장했습니다. 자료 기준 시각을 확인하세요.');}if(result.status!=='prepared'){requestKey=null;try{sessionStorage.removeItem(storageKey);}catch{}}await load();}catch(error){notice(error.message,true);if(['snapshot_changed','invalid_diagram','idempotency_conflict'].includes(error.code)){requestKey=null;try{sessionStorage.removeItem(storageKey);}catch{}}}finally{busy=false;actions();}}
function theme(value){document.documentElement.dataset.theme=value;document.querySelectorAll('header [data-theme]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.theme===value)));try{localStorage.setItem('ai-company-theme',value);}catch{}}
document.querySelectorAll('header [data-theme]').forEach(el=>el.addEventListener('click',()=>theme(el.dataset.theme)));let initial='light';try{initial=localStorage.getItem('ai-company-theme')==='black'?'black':'light';requestKey=sessionStorage.getItem(storageKey);}catch{}theme(initial);
async function start(){if(!valid){$('#subject').textContent='그림 대상을 찾을 수 없습니다.';notice('진행 화면에서 계획이나 실행을 선택한 뒤 그림을 열어 주세요.',true);return;}$('#back').href=`/?workspace=integrated#progress?project=${encodeURIComponent(project)}`;try{const session=await api('/api/session');if(!session.authenticated||session.password_change_required){$('#subject').textContent='로그인이 필요합니다.';$('#actions').innerHTML='<a class="button" href="/">로그인</a>';return;}csrf=session.csrf_token;$('#subject').textContent='선택한 계획·실행 기록을 한 시점의 그림으로 보관합니다.';actions();await load();}catch(error){notice(error.message,true);}}
start();
