/* Reading language never supplies executable fields or confirmation digests. */
export function createPlanUI({esc, documents}) {
  const skillStates={recommended:'추천',reviewed:'내용 검토',assigned:'계획 배정',delivered:'실행 전달',rejected:'보류',unavailable:'사용 불가',approved_document:'내용 검토 완료',review_pending:'검토 전'};
  const list=value=>Array.isArray(value)?value:[];
  const skillState=(item,selection)=>skillStates[item.status]||skillStates[selection.status]||'상태 확인 중';
  function roleSkills(selection,role) {
    if(!selection)return '';
    const items=list(selection.roles?.[role.key]);
    const roleOutcome=selection.role_outcomes?.[role.key]||selection.outcome;
    const fallback=roleOutcome==='not_allowlisted'?'이 역할에 허용된 공개 조사어가 없습니다. 현재 지침으로 진행합니다.'
      :roleOutcome==='lookup_failed'
      ?`조회 실패 · ${esc(selection.reason||'원인을 확인해 주세요.')} ${selection.can_continue===true?'기존 지침으로 진행할 수 있습니다.':'진행 가능 여부는 계획 검토에서 확인합니다.'}`
      :roleOutcome==='review_pending'?'후보를 검토 중입니다.'
      :['lookup_pending','search_found_unpinned','lookup_not_configured','no_results','no_matching_document'].includes(roleOutcome)
        ?esc(selection.reason||'조사 상태를 확인해 주세요.'):'현재 지침으로 진행합니다.';
    return `<section class="role-skills" aria-label="${esc(role.name||role.key)} 작업 지침"><h4>작업 지침</h4>${items.length?`<ul class="role-skill-list">${items.map(item=>`<li><div class="role-skill-heading"><strong>${esc(item.name)}</strong><span>${esc(skillState(item,selection))} · ${item.selected?'선택됨':'미선택'}</span></div><p>${esc(item.reason||'추천 근거 확인 중')}</p><details class="plan-scope" data-persist-key="skill:${esc(role.key)}:${esc(item.name)}"><summary>${esc(item.name)} 상세</summary><dl class="detail-grid"><div><dt>출처</dt><dd class="mono">${esc(item.source_url||'확인 중')}</dd></div><div><dt>버전</dt><dd>${esc(item.version||'확인 중')}</dd></div><div><dt>파일 묶음 해시</dt><dd class="mono">${esc(item.bundle_sha256||'확인 중')}</dd></div><div><dt>관련 요구사항</dt><dd>${esc(list(item.requirements).join(' · ')||'연결 없음')}</dd></div><div><dt>필요한 도구·의존성</dt><dd>${esc(list(item.dependencies).join(' · ')||'추가 없음')}</dd></div><div><dt>필요 권한</dt><dd>${esc(list(item.permissions).join(' · ')||'추가 없음')}</dd></div></dl></details></li>`).join('')}</ul>`:`<p>${fallback}</p>`}</section>`;
  }
  function render(plan) {
    const content=plan.content||{}, id=`plan:${plan.id}`;
    const text=(field,original)=>esc(documents.text(id,field,original||''));
    const criteria=(values,field)=>values?.length?`<ul class="plan-criteria">${values.map((value,index)=>`<li>${text(`${field}:${index}`,value)}</li>`).join('')}</ul>`:'미등록';
    const spec=content.requirements_review;
    const requirements=spec?`<details class="plan-scope"><summary>요구사항 · 검증</summary><p>${esc(spec.problem)}</p><dl class="detail-grid"><div><dt>사용자·흐름</dt><dd>${esc(spec.users_and_flow)}</dd></div><div><dt>범위</dt><dd>${criteria(spec.scope,'scope')}</dd></div><div><dt>제외</dt><dd>${criteria(spec.exclusions,'exclusions')}</dd></div><div><dt>가정</dt><dd>${criteria(spec.assumptions,'assumptions')}</dd></div></dl><ul class="plan-criteria">${spec.requirements.map(item=>`<li><strong>${esc(item.id)}</strong> · ${esc(item.acceptance)}<br>출처: ${esc(item.source)}<br>확인: ${esc(item.verification)} · 담당 ${esc(item.role_keys.join(', '))}</li>`).join('')}</ul>${spec.questions.length?`<details><summary>질문 · 결정 ${spec.questions.length}개</summary><ul class="plan-criteria">${spec.questions.map(item=>`<li><strong>${esc(item.prompt)}</strong> · ${esc(({open:'답변 필요',answered:'답변됨',assumed:'가정',excluded:'범위 제외'})[item.status]||item.status)}<br>${esc(item.resolution||item.reason)}</li>`).join('')}</ul></details>`:''}${spec.findings.length?`<details><summary>발견한 문제 ${spec.findings.length}개</summary><ul class="plan-criteria">${spec.findings.map(item=>`<li><strong>${esc(item.id)}</strong> · ${esc(item.impact)}<br>근거: ${esc(item.evidence)}<br>추천: ${esc(item.recommendation)}<br>처리: ${esc(item.resolution||item.status)}</li>`).join('')}</ul></details>`:''}</details>`:'';
    return `<section class="plan-reading" aria-label="계획 내용">${documents.meta(id)}<p class="report-summary">${text('summary',content.summary)}</p>${requirements}<div class="plan-roles">${(content.roles||[]).map((role,index)=>`<section class="role-config"><h3>${text(`role:${index}:name`,role.name||role.key)}</h3><p>${text(`role:${index}:responsibility`,role.responsibility)}</p><dl class="detail-grid"><div><dt>목표</dt><dd>${text(`role:${index}:goal`,role.goal)}</dd></div><div><dt>완료 조건</dt><dd>${criteria(role.acceptance,`role:${index}:acceptance`)}</dd></div><div><dt>선행 역할</dt><dd>${role.depends_on?.length?esc(role.depends_on.join(' · ')):'없음 · 독립 진행'}</dd></div><div><dt>작업 범위</dt><dd>${esc((role.allowed_paths||[]).length)}개 경로</dd></div></dl>${roleSkills(content.skill_selection,role)}<details class="plan-scope"><summary>허용 경로</summary><ul>${(role.allowed_paths||[]).map(path=>`<li class="mono">${esc(path)}</li>`).join('')}</ul><p class="small muted">역할 ID · ${esc(role.key)}</p></details></section>`).join('')}</div><div class="plan-completion"><strong>완료 조건</strong>${criteria(content.completion_criteria,'completion')}</div>${plan.review?`<details class="plan-scope"><summary>계획 검수 · ${esc(({PASS:'통과',REVISE:'수정 필요',BLOCK:'확인 필요'})[plan.review.verdict]||plan.review.verdict)} · ${plan.review.mode==='fixture'?'모의':'실제 세션'}</summary><p>${esc(plan.review.summary)}</p>${plan.review.findings?.length?`<ul class="plan-criteria">${plan.review.findings.map(item=>`<li>${esc(item.detail)}<br>근거: ${esc(item.evidence)}</li>`).join('')}</ul>`:''}</details>`:''}</section>`;
  }
  return {render};
}
