/* Reading language never supplies executable fields or confirmation digests. */
export function createPlanUI({esc, documents}) {
  function render(plan) {
    const content=plan.content||{}, id=`plan:${plan.id}`;
    const text=(field,original)=>esc(documents.text(id,field,original||''));
    const criteria=(values,field)=>values?.length?`<ul class="plan-criteria">${values.map((value,index)=>`<li>${text(`${field}:${index}`,value)}</li>`).join('')}</ul>`:'미등록';
    const spec=content.requirements_review;
    const requirements=spec?`<details class="plan-scope"><summary>요구사항 · 검증</summary><p>${esc(spec.problem)}</p><dl class="detail-grid"><div><dt>사용자·흐름</dt><dd>${esc(spec.users_and_flow)}</dd></div><div><dt>범위</dt><dd>${criteria(spec.scope,'scope')}</dd></div><div><dt>제외</dt><dd>${criteria(spec.exclusions,'exclusions')}</dd></div><div><dt>가정</dt><dd>${criteria(spec.assumptions,'assumptions')}</dd></div></dl><ul class="plan-criteria">${spec.requirements.map(item=>`<li><strong>${esc(item.id)}</strong> · ${esc(item.acceptance)}<br>출처: ${esc(item.source)}<br>확인: ${esc(item.verification)} · 담당 ${esc(item.role_keys.join(', '))}</li>`).join('')}</ul>${spec.questions.length?`<details><summary>질문 · 결정 ${spec.questions.length}개</summary><ul class="plan-criteria">${spec.questions.map(item=>`<li><strong>${esc(item.prompt)}</strong> · ${esc(({open:'답변 필요',answered:'답변됨',assumed:'가정',excluded:'범위 제외'})[item.status]||item.status)}<br>${esc(item.resolution||item.reason)}</li>`).join('')}</ul></details>`:''}${spec.findings.length?`<details><summary>발견한 문제 ${spec.findings.length}개</summary><ul class="plan-criteria">${spec.findings.map(item=>`<li><strong>${esc(item.id)}</strong> · ${esc(item.impact)}<br>근거: ${esc(item.evidence)}<br>추천: ${esc(item.recommendation)}<br>처리: ${esc(item.resolution||item.status)}</li>`).join('')}</ul></details>`:''}</details>`:'';
    return `<section class="plan-reading" aria-label="계획 내용">${documents.meta(id)}<p class="report-summary">${text('summary',content.summary)}</p>${requirements}<div class="plan-roles">${(content.roles||[]).map((role,index)=>`<section class="role-config"><h3>${text(`role:${index}:name`,role.name||role.key)}</h3><p>${text(`role:${index}:responsibility`,role.responsibility)}</p><dl class="detail-grid"><div><dt>목표</dt><dd>${text(`role:${index}:goal`,role.goal)}</dd></div><div><dt>완료 조건</dt><dd>${criteria(role.acceptance,`role:${index}:acceptance`)}</dd></div><div><dt>선행 역할</dt><dd>${role.depends_on?.length?esc(role.depends_on.join(' · ')):'없음 · 독립 진행'}</dd></div><div><dt>작업 범위</dt><dd>${esc((role.allowed_paths||[]).length)}개 경로</dd></div></dl><details class="plan-scope"><summary>허용 경로</summary><ul>${(role.allowed_paths||[]).map(path=>`<li class="mono">${esc(path)}</li>`).join('')}</ul><p class="small muted">역할 ID · ${esc(role.key)}</p></details></section>`).join('')}</div><div class="plan-completion"><strong>완료 조건</strong>${criteria(content.completion_criteria,'completion')}</div>${plan.review?`<details class="plan-scope"><summary>계획 검수 · ${esc(({PASS:'통과',REVISE:'수정 필요',BLOCK:'확인 필요'})[plan.review.verdict]||plan.review.verdict)} · ${plan.review.mode==='fixture'?'모의':'실제 세션'}</summary><p>${esc(plan.review.summary)}</p>${plan.review.findings?.length?`<ul class="plan-criteria">${plan.review.findings.map(item=>`<li>${esc(item.detail)}<br>근거: ${esc(item.evidence)}</li>`).join('')}</ul>`:''}</details>`:''}</section>`;
  }
  return {render};
}
