/* System aggregation and PM-authored prose remain separate sources. */
export function createReportUI({esc,badge,stamp,documents,approvalDisplay=()=>({actionable:false}),roleStatus=()=>({group:'unknown',label:'상태 미확인',next:'원문 상태와 실행 근거를 확인하세요.'})}) {
  const groups=items=>[['완료','done'],['진행','active'],['대기','waiting'],['확인 필요','operator'],['미확인','unknown']].map(([title,group])=>[title,items.filter(item=>roleStatus(item.status).group===group)]);
  function render(overview,{href,compact=false}={}) {
    const report=overview.project_report;if(!report)return '';
    const roleItems=[...report.completed,...report.in_progress],actions=[...roleItems,...report.blockers].map(item=>roleStatus(item.status));
    const intervention=actions.find(item=>item.group==='operator')||actions.find(item=>item.group==='unknown');
    const nextActions=intervention?[{view:'progress',text:intervention.next}]:report.next_actions;
    const pid=encodeURIComponent(overview.project.id),plan=overview.plans?.find(p=>p.id===report.plan_id);
    const rows=items=>items.length?`<ul class="summary-list">${items.map(item=>`<li><div><strong>${esc(item.role_index===undefined?item.title:documents.text(`plan:${report.plan_id}`,`role:${item.role_index}:name`,item.title))}</strong>${badge(item.status)}</div>${item.reason?`<p>${esc(documents.text(`task:${item.task_id}:reason`,'reason',item.reason))}</p>`:''}${item.resume_at?`<small>예약 · ${stamp(item.resume_at)}</small>`:''}<details><summary>원문 상태</summary><code>${esc(item.status??'미기록')}</code></details></li>`).join('')}</ul>`:'<p class="muted small">없음</p>';
    const decisions=report.decisions.map(item=>item.kind==='plan_confirmed'?`<li><strong>계획 확정</strong><span>${item.delegated?'위임 검증 · 실제 UI 확인과 구분':'저장된 확정 기록'}</span><time>${stamp(item.at)}</time></li>`:`<li><strong>후보 수용</strong>${badge(item.status)}${item.comment?`<p>${esc(item.comment)}</p>`:''}${item.at?`<time>${stamp(item.at)}</time>`:''}</li>`).join('');
    return `<section class="panel project-summary" aria-label="프로젝트 종합 보고"><header class="section-line"><h2>종합</h2><span class="badge">시스템 집계</span></header><h3>목표</h3><p>${esc(documents.text(`project:${report.project_id}`,'goal',report.goal))}</p><p class="small muted">${report.candidate_verified?'같은 후보의 검수 통과 기록이 있습니다.':'후보 검수 완료 전입니다.'} 목표 달성 판단과 마스터 수용은 별도입니다.</p>${compact?'':`<div class="summary-grid">${groups(roleItems).map(([title,items])=>`<section><h3>${title} <span>${items.length}</span></h3>${items.length?rows(items):''}</section>`).join('')}<section><h3>차단·대기 근거 <span>${report.blockers.length}</span></h3>${rows(report.blockers)}</section><section><h3>다음</h3><ul class="summary-list">${nextActions.map(item=>`<li><a href="${href?href(item.view):`#${esc(item.view)}?project=${pid}`}">${esc(item.text)}</a></li>`).join('')}</ul></section></div>`}${intervention?`<details><summary>시스템 원문 안내</summary><p class="small muted">저장된 집계의 안내입니다. 현재 상태에 따른 조치는 위의 다음 항목을 확인하세요.</p><ul>${report.next_actions.map(item=>`<li>${esc(item.text)}</li>`).join('')}</ul></details>`:''}<h3>결정</h3>${decisions?`<ul class="summary-list summary-decisions">${decisions}</ul>`:'<p class="muted small">기록 없음</p>'}<details><summary>근거</summary><dl class="detail-grid"><div><dt>계획</dt><dd class="mono">${esc(report.plan_digest||'미제안')}</dd></div><div><dt>실행</dt><dd class="mono">${esc(report.run_id||'미생성')}</dd></div><div><dt>후보</dt><dd class="mono">${esc(report.candidate_sha||'미생성')}</dd></div><div><dt>집계</dt><dd class="mono">${esc(report.digest)}</dd></div></dl>${plan?`<strong>완료 조건</strong><ul>${report.completion_criteria.map((text,index)=>`<li>${esc(documents.text(`plan:${plan.id}`,`completion:${index}`,text))}</li>`).join('')}</ul>`:''}</details></section><section class="panel pm-report-summary" aria-label="PM 작성 보고"><div class="section-line"><h2>PM</h2><span class="badge">${report.pm_report_ids.length?'PM 작성':'보고 없음'}</span></div>${report.pm_report_ids.length?'<p class="small">PM 작성 문서는 아래 보고서에서 확인하세요.</p>':`<p class="muted small">PM이 작성한 종합 보고는 아직 없습니다.</p>${plan?`<details><summary>제안</summary><p>${esc(documents.text(`plan:${plan.id}`,'summary',plan.content.summary))}</p><span class="small muted">계획 제안 · 완료 보고 아님</span></details>`:''}`}</section>`;
  }
  function execution(overview,{snapshot,run,status,href,approvals=[],reports=overview.reports||[],now=Date.now()}) {
    if(!snapshot)return '';
    const plan=(overview.plans||[]).find(item=>item.id===snapshot.plan_id&&item.digest===snapshot.plan_digest);
    const roles=(snapshot.nodes||[]).filter(node=>node.kind==='role'&&['project_id','plan_id','plan_digest','run_id'].every(key=>node[key]===snapshot[key]));
    const rows=items=>items.length?`<ul class="summary-list">${items.map(node=>{const projected=roleStatus(node.status);return `<li><div><strong>${esc(node.name)}</strong>${badge(node.status)}</div>${node.wait_reason?`<p>${esc(node.wait_reason)}</p>`:''}${node.resume_at?`<p>재개 예약 · ${stamp(node.resume_at)}</p>`:''}${['operator','unknown'].includes(projected.group)?`<p>${esc(projected.next)}</p>`:''}<details><summary>원문 상태</summary><code>${esc(node.status??'미기록')}</code></details></li>`;}).join('')}</ul>`:'<p class="muted">기록 없음</p>';
    const linked=overview.project_report,exact=linked&&linked.project_id===snapshot.project_id&&linked.plan_id===snapshot.plan_id&&linked.plan_digest===snapshot.plan_digest&&linked.run_id===snapshot.run_id;
    const pending=approvals.find(item=>approvalDisplay(item,now).actionable),classified=groups(roles);
    const outstanding=classified.filter(([title,items])=>title!=='완료'&&items.length).map(([title,items])=>`${title} ${items.length}개`);
    const remaining=run?.wait_reason|| (outstanding.length?outstanding.join(' · '):roles.length?'역할 기록은 모두 완료입니다. 통합 검수와 후보 수용은 별도로 확인하세요.':'역할 기록이 없어 남은 작업을 확인할 수 없습니다.');
    const pmIds=reports.filter(item=>item.source==='pm'&&(!item.project_id||item.project_id===snapshot.project_id)&&(!item.run_id||item.run_id===snapshot.run_id)&&(!item.plan_digest||item.plan_digest===snapshot.plan_digest)&&(snapshot.report_refs||[]).some(ref=>ref.id===item.id&&['project_id','plan_id','plan_digest','run_id'].every(key=>ref[key]===snapshot[key]))).map(item=>item.id);
    return `<section class="panel journey-result" aria-label="선택한 실행의 결과" data-result-run="${esc(snapshot.run_id||'')}"><header class="section-line" aria-label="현재 결론"><h2>${esc(status.title)}</h2><span class="badge">시스템 집계</span></header><dl class="journey-result-summary"><div><dt>남은 일</dt><dd>${esc(remaining)}${run?.resume_at?`<p>재개 예약 · ${stamp(run.resume_at)}</p>`:''}</dd></div><div><dt>다음 행동</dt><dd>${esc(status.next)}</dd></div></dl><div class="journey-result-links"><a href="${href('progress')}">진행 확인</a>${pending?`<a href="${href('approvals')}&approval=${encodeURIComponent(pending.id)}">승인 요청 확인</a>`:''}</div><div class="summary-grid role-counts" aria-label="역할 집계">${classified.map(([title,items])=>`<section><h3>${title} <span>${items.length}</span></h3></section>`).join('')}</div>${roles.length?`<details class="result-role-details" data-persist-key="result-roles:${esc(snapshot.id)}"><summary>역할별 내역 ${roles.length}개</summary>${classified.filter(([,items])=>items.length).map(([title,items])=>`<section><h3>${title}</h3>${rows(items)}</section>`).join('')}</details>`:''}${plan?`<details data-persist-key="result-plan:${esc(plan.id)}"><summary>완료 조건</summary><ul>${(plan.content?.completion_criteria||[]).map((text,index)=>`<li>${esc(documents.text('plan:'+plan.id,'completion:'+index,text))}</li>`).join('')}</ul></details>`:'<p class="muted">선택한 실행의 계획 원문 미확인</p>'}<details data-persist-key="result-candidate:${esc(snapshot.id)}"><summary>후보·실행 원문</summary><p>실행 상태 · <code>${esc(run?.state??'미기록')}</code></p><p class="mono">${esc(run?.integration?.candidate_sha||run?.candidate_sha||'후보 미확인')}</p></details></section>${exact?`<details class="result-system-details" data-persist-key="result-system:${esc(snapshot.id)}"><summary>시스템 집계 근거·결정</summary>${render({...overview,project_report:{...linked,pm_report_ids:pmIds}},{href,compact:true})}</details>`:'<p class="journey-report-note">이 실행의 종합 보고는 아직 없습니다. 연결된 문서만 아래에 표시합니다.</p>'}<p class="journey-pm-source">${pmIds.length?`PM 작성 보고 ${pmIds.length}건 · 아래 문서에서 확인하세요.`:'PM 작성 보고 없음 · 위 요약은 시스템 집계입니다.'}</p>`;
  }

  function workers(overview){
    const names={automation:'PM · 조정기',translation:'번역'},states={starting:'시작 중',busy:'처리 중',idle:'가동 신호',stopped:'중지',error:'오류',stale:'신호 끊김',unavailable:'미확인'};
    return `<section class="worker-summary" aria-label="실행기 가동 신호"><h3>운영</h3><ul class="summary-list">${Object.entries(names).map(([key,name])=>{const row=overview.workers?.[key]||{state:'unavailable'};return `<li><div><strong>${name}</strong>${badge(states[row.state]||'미확인')}</div>${row.heartbeat_at?`<small>최근 신호 · ${stamp(row.heartbeat_at)}</small>`:''}${row.last_completed_at?`<small> · 처리 확인 · ${stamp(row.last_completed_at)}</small>`:''}</li>`;}).join('')}</ul><p class="small muted">서버가 기록한 가동 신호입니다. PM과 조정기는 같은 실행기에서 동작합니다.</p></section>`;
  }
  return {render,execution,workers};
}
