/* System aggregation and PM-authored prose remain separate sources. */
export function createReportUI({esc,badge,stamp,documents}) {
  function render(overview) {
    const report=overview.project_report;if(!report)return '';
    const pid=encodeURIComponent(overview.project.id),plan=overview.plans?.find(p=>p.id===report.plan_id);
    const rows=items=>items.length?`<ul class="summary-list">${items.map(item=>`<li><div><strong>${esc(item.role_index===undefined?item.title:documents.text(`plan:${report.plan_id}`,`role:${item.role_index}:name`,item.title))}</strong>${badge(item.status)}</div>${item.reason?`<p>${esc(documents.text(`task:${item.task_id}:reason`,'reason',item.reason))}</p>`:''}${item.resume_at?`<small>예약 · ${stamp(item.resume_at)}</small>`:''}</li>`).join('')}</ul>`:'<p class="muted small">없음</p>';
    const decisions=report.decisions.map(item=>item.kind==='plan_confirmed'?`<li><strong>계획 확정</strong><span>${item.delegated?'위임 검증 · 실제 UI 확인과 구분':'저장된 확정 기록'}</span><time>${stamp(item.at)}</time></li>`:`<li><strong>후보 수용</strong>${badge(item.status)}${item.comment?`<p>${esc(item.comment)}</p>`:''}${item.at?`<time>${stamp(item.at)}</time>`:''}</li>`).join('');
    return `<section class="panel project-summary" aria-label="프로젝트 종합 보고"><header class="section-line"><h2>종합</h2><span class="badge">시스템 집계</span></header><h3>목표</h3><p>${esc(documents.text(`project:${report.project_id}`,'goal',report.goal))}</p><p class="small muted">${report.candidate_verified?'같은 후보의 검수 통과 기록이 있습니다.':'후보 검수 완료 전입니다.'} 목표 달성 판단과 마스터 수용은 별도입니다.</p><div class="summary-grid"><section><h3>완료 <span>${report.completed.length}</span></h3>${rows(report.completed)}</section><section><h3>진행 <span>${report.in_progress.length}</span></h3>${rows(report.in_progress)}</section><section><h3>차단 <span>${report.blockers.length}</span></h3>${rows(report.blockers)}</section><section><h3>다음</h3><ul class="summary-list">${report.next_actions.map(item=>`<li><a href="#${esc(item.view)}?project=${pid}">${esc(item.text)}</a></li>`).join('')}</ul></section></div><h3>결정</h3>${decisions?`<ul class="summary-list summary-decisions">${decisions}</ul>`:'<p class="muted small">기록 없음</p>'}<details><summary>근거</summary><dl class="detail-grid"><div><dt>계획</dt><dd class="mono">${esc(report.plan_digest||'미제안')}</dd></div><div><dt>실행</dt><dd class="mono">${esc(report.run_id||'미생성')}</dd></div><div><dt>후보</dt><dd class="mono">${esc(report.candidate_sha||'미생성')}</dd></div><div><dt>집계</dt><dd class="mono">${esc(report.digest)}</dd></div></dl>${plan?`<strong>완료 조건</strong><ul>${report.completion_criteria.map((text,index)=>`<li>${esc(documents.text(`plan:${plan.id}`,`completion:${index}`,text))}</li>`).join('')}</ul>`:''}</details></section><section class="panel pm-report-summary" aria-label="PM 작성 보고"><div class="section-line"><h2>PM</h2><span class="badge">${report.pm_report_ids.length?'PM 작성':'보고 없음'}</span></div>${report.pm_report_ids.length?'<p class="small">PM 작성 문서는 아래 보고서에서 확인하세요.</p>':`<p class="muted small">PM이 작성한 종합 보고는 아직 없습니다.</p>${plan?`<details><summary>제안</summary><p>${esc(documents.text(`plan:${plan.id}`,'summary',plan.content.summary))}</p><span class="small muted">계획 제안 · 완료 보고 아님</span></details>`:''}`}</section>`;
  }
  function workers(overview){
    const names={automation:'PM · 조정기',translation:'번역'},states={starting:'시작 중',busy:'처리 중',idle:'가동 신호',stopped:'중지',error:'오류',stale:'신호 끊김',unavailable:'미확인'};
    return `<section class="worker-summary" aria-label="실행기 가동 신호"><h3>운영</h3><ul class="summary-list">${Object.entries(names).map(([key,name])=>{const row=overview.workers?.[key]||{state:'unavailable'};return `<li><div><strong>${name}</strong>${badge(states[row.state]||'미확인')}</div>${row.heartbeat_at?`<small>최근 신호 · ${stamp(row.heartbeat_at)}</small>`:''}${row.last_completed_at?`<small> · 처리 확인 · ${stamp(row.last_completed_at)}</small>`:''}</li>`;}).join('')}</ul><p class="small muted">서버가 기록한 가동 신호입니다. PM과 조정기는 같은 실행기에서 동작합니다.</p></section>`;
  }
  return {render,workers};
}
