/* System aggregation and PM-authored prose remain separate sources. */
export function createReportUI({esc,badge,stamp,documents,roleStatus=()=>({group:'unknown',label:'상태 미확인',next:'원문 상태와 실행 근거를 확인하세요.'})}) {
  const groups=items=>[['완료','done'],['진행','active'],['대기','waiting'],['확인 필요','operator'],['미확인','unknown']].map(([title,group])=>[title,items.filter(item=>roleStatus(item.status).group===group)]);
  function render(overview,{href}={}) {
    const report=overview.project_report;if(!report)return '';
    const roleItems=[...report.completed,...report.in_progress],actions=[...roleItems,...report.blockers].map(item=>roleStatus(item.status));
    const intervention=actions.find(item=>item.group==='operator')||actions.find(item=>item.group==='unknown');
    const nextActions=intervention?[{view:'progress',text:intervention.next}]:report.next_actions;
    const pid=encodeURIComponent(overview.project.id),plan=overview.plans?.find(p=>p.id===report.plan_id);
    const rows=items=>items.length?`<ul class="summary-list">${items.map(item=>`<li><div><strong>${esc(item.role_index===undefined?item.title:documents.text(`plan:${report.plan_id}`,`role:${item.role_index}:name`,item.title))}</strong>${badge(item.status)}</div>${item.reason?`<p>${esc(documents.text(`task:${item.task_id}:reason`,'reason',item.reason))}</p>`:''}${item.resume_at?`<small>예약 · ${stamp(item.resume_at)}</small>`:''}<details><summary>원문 상태</summary><code>${esc(item.status??'미기록')}</code></details></li>`).join('')}</ul>`:'<p class="muted small">없음</p>';
    const decisions=report.decisions.map(item=>item.kind==='plan_confirmed'?`<li><strong>계획 확정</strong><span>${item.delegated?'위임 검증 · 실제 UI 확인과 구분':'저장된 확정 기록'}</span><time>${stamp(item.at)}</time></li>`:`<li><strong>후보 수용</strong>${badge(item.status)}${item.comment?`<p>${esc(item.comment)}</p>`:''}${item.at?`<time>${stamp(item.at)}</time>`:''}</li>`).join('');
    return `<section class="panel project-summary" aria-label="프로젝트 종합 보고"><header class="section-line"><h2>종합</h2><span class="badge">시스템 집계</span></header><h3>목표</h3><p>${esc(documents.text(`project:${report.project_id}`,'goal',report.goal))}</p><p class="small muted">${report.candidate_verified?'같은 후보의 검수 통과 기록이 있습니다.':'후보 검수 완료 전입니다.'} 목표 달성 판단과 마스터 수용은 별도입니다.</p><div class="summary-grid">${groups(roleItems).map(([title,items])=>`<section><h3>${title} <span>${items.length}</span></h3>${rows(items)}</section>`).join('')}<section><h3>차단·대기 근거 <span>${report.blockers.length}</span></h3>${rows(report.blockers)}</section><section><h3>다음</h3><ul class="summary-list">${nextActions.map(item=>`<li><a href="${href?href(item.view):`#${esc(item.view)}?project=${pid}`}">${esc(item.text)}</a></li>`).join('')}</ul></section></div>${intervention?`<details><summary>시스템 원문 안내</summary><p class="small muted">저장된 집계의 안내입니다. 현재 상태에 따른 조치는 위의 다음 항목을 확인하세요.</p><ul>${report.next_actions.map(item=>`<li>${esc(item.text)}</li>`).join('')}</ul></details>`:''}<h3>결정</h3>${decisions?`<ul class="summary-list summary-decisions">${decisions}</ul>`:'<p class="muted small">기록 없음</p>'}<details><summary>근거</summary><dl class="detail-grid"><div><dt>계획</dt><dd class="mono">${esc(report.plan_digest||'미제안')}</dd></div><div><dt>실행</dt><dd class="mono">${esc(report.run_id||'미생성')}</dd></div><div><dt>후보</dt><dd class="mono">${esc(report.candidate_sha||'미생성')}</dd></div><div><dt>집계</dt><dd class="mono">${esc(report.digest)}</dd></div></dl>${plan?`<strong>완료 조건</strong><ul>${report.completion_criteria.map((text,index)=>`<li>${esc(documents.text(`plan:${plan.id}`,`completion:${index}`,text))}</li>`).join('')}</ul>`:''}</details></section><section class="panel pm-report-summary" aria-label="PM 작성 보고"><div class="section-line"><h2>PM</h2><span class="badge">${report.pm_report_ids.length?'PM 작성':'보고 없음'}</span></div>${report.pm_report_ids.length?'<p class="small">PM 작성 문서는 아래 보고서에서 확인하세요.</p>':`<p class="muted small">PM이 작성한 종합 보고는 아직 없습니다.</p>${plan?`<details><summary>제안</summary><p>${esc(documents.text(`plan:${plan.id}`,'summary',plan.content.summary))}</p><span class="small muted">계획 제안 · 완료 보고 아님</span></details>`:''}`}</section>`;
  }
  function execution(overview,{snapshot,run,status,href,approvals=[]}) {
    if(!snapshot)return '';
    const plan=(overview.plans||[]).find(item=>item.id===snapshot.plan_id&&item.digest===snapshot.plan_digest);
    const roles=(snapshot.nodes||[]).filter(node=>node.kind==='role'&&['project_id','plan_id','plan_digest','run_id'].every(key=>node[key]===snapshot[key]));
    const rows=items=>items.length?`<ul class="summary-list">${items.map(node=>{const projected=roleStatus(node.status);return `<li><div><strong>${esc(node.name)}</strong>${badge(node.status)}</div>${node.wait_reason?`<p>${esc(node.wait_reason)}</p>`:''}${node.resume_at?`<p>재개 예약 · ${stamp(node.resume_at)}</p>`:''}${['operator','unknown'].includes(projected.group)?`<p>${esc(projected.next)}</p>`:''}<details><summary>원문 상태</summary><code>${esc(node.status??'미기록')}</code></details></li>`;}).join('')}</ul>`:'<p class="muted">기록 없음</p>';
    const linked=overview.project_report,exact=linked&&linked.project_id===snapshot.project_id&&linked.plan_id===snapshot.plan_id&&linked.plan_digest===snapshot.plan_digest&&linked.run_id===snapshot.run_id;
    const pending=approvals.find(item=>['pending','PENDING','WAITING_APPROVAL'].includes(item.status)&&(!item.expires_at||new Date(typeof item.expires_at==='number'?item.expires_at*1000:item.expires_at).getTime()>Date.now()));
    return `<section class="panel journey-result" aria-label="선택한 실행의 결과" data-result-run="${esc(snapshot.run_id||'')}"><header class="section-line"><h2>${esc(status.title)}</h2><span class="badge">실행 기록 요약</span></header><p>${esc(status.next)}</p>${run?.wait_reason?`<p class="role-note">${esc(run.wait_reason)}</p>`:''}${run?.resume_at?`<p>재개 예약 · ${stamp(run.resume_at)}</p>`:''}<div class="journey-result-links"><a href="${href('progress')}">진행 확인</a>${pending?`<a href="${href('approvals')}&approval=${encodeURIComponent(pending.id)}">승인 요청 확인</a>`:''}</div><div class="summary-grid">${groups(roles).map(([title,items])=>`<section><h3>${title} <span>${items.length}</span></h3>${rows(items)}</section>`).join('')}</div><p class="small muted">역할 기록의 분류입니다. 역할 완료와 통합 검사·검수 통과는 구별합니다.</p>${plan?`<details data-persist-key="result-plan:${esc(plan.id)}"><summary>완료 조건</summary><ul>${(plan.content?.completion_criteria||[]).map((text,index)=>`<li>${esc(documents.text('plan:'+plan.id,'completion:'+index,text))}</li>`).join('')}</ul></details>`:'<p class="muted">선택한 실행의 계획 원문 미확인</p>'}<details data-persist-key="result-candidate:${esc(snapshot.id)}"><summary>후보·실행 원문</summary><p>실행 상태 · <code>${esc(run?.state??'미기록')}</code></p><p class="mono">${esc(run?.integration?.candidate_sha||run?.candidate_sha||'후보 미확인')}</p></details></section>${exact?render({...overview,project_report:{...linked,pm_report_ids:(linked.pm_report_ids||[]).filter(id=>(snapshot.report_refs||[]).some(ref=>ref.id===id))}},{href}):'<p class="journey-report-note">선택한 실행의 종합 보고는 아직 없습니다. 아래에는 이 실행에 연결된 문서만 표시합니다.</p>'}`;
  }
  function workers(overview){
    const names={automation:'PM · 조정기',translation:'번역'},states={starting:'시작 중',busy:'처리 중',idle:'가동 신호',stopped:'중지',error:'오류',stale:'신호 끊김',unavailable:'미확인'};
    return `<section class="worker-summary" aria-label="실행기 가동 신호"><h3>운영</h3><ul class="summary-list">${Object.entries(names).map(([key,name])=>{const row=overview.workers?.[key]||{state:'unavailable'};return `<li><div><strong>${name}</strong>${badge(states[row.state]||'미확인')}</div>${row.heartbeat_at?`<small>최근 신호 · ${stamp(row.heartbeat_at)}</small>`:''}${row.last_completed_at?`<small> · 처리 확인 · ${stamp(row.last_completed_at)}</small>`:''}</li>`;}).join('')}</ul><p class="small muted">서버가 기록한 가동 신호입니다. PM과 조정기는 같은 실행기에서 동작합니다.</p></section>`;
  }
  return {render,execution,workers};
}
